/*
 * Geolite - EL CRUPIER (v0.10). El "jefe" de la mesa: un croupier de pixel art que habla con sonidos arcade (una silaba por letra),
 * anuncia los retos, se rie cuando fallas, se sorprende con una diana y protesta cuando lo esquivas con una reliquia.
 *   A.dealer.say(linea, {mood, hold})   A.dealer.react(tipo, datos)   A.dealer.intro(host, lineas)   A.dealer.enable(on)
 */
window.AIQ = window.AIQ || {};
(function (A) {
  const $ = id => document.getElementById(id);
  const L6 = s => { const [es, en, fr, pt, de, it] = s.split("|"); return { es, en, fr, pt, de, it: it || en }; };
  const FACE = { sly: "dealer_neutral", boss: "dealer_neutral", laugh: "dealer_laugh", angry: "dealer_angry", shock: "dealer_shock" };

  /* frases: es | en | fr | pt | de | it */
  const LINES = {
    hello: ["¡Bienvenido a mi mesa, explorador! Aquí manda el mapa… y yo cambio las reglas.|Welcome to my table, explorer! The map rules here… and I change the rules.|Bienvenue à ma table, explorateur ! Ici la carte est reine… et je change les règles.|Bem-vindo à minha mesa, explorador! Aqui o mapa manda… e eu mudo as regras.|Willkommen an meinem Tisch, Entdecker! Hier regiert die Karte… und ich ändere die Regeln.|Benvenuto al mio tavolo, esploratore! Qui comanda la mappa… e io cambio le regole."],
    calm: ["Calentamos: esta ronda, sin trucos. Disfrútala.|Warm-up: no tricks this round. Enjoy it.|On s'échauffe : pas de tours cette manche. Profites-en.|Aquecimento: sem truques nesta rodada. Aproveite.|Aufwärmen: keine Tricks in dieser Runde. Viel Spaß.|Riscaldamento: niente trucchi in questo round. Goditelo."],
    deal: ["Nueva mano… y he tocado la mesa. Mira lo que te reparto.|New hand… and I touched the table. Look what I deal you.|Nouvelle donne… et j'ai touché à la table. Regarde.|Nova mão… e eu mexi na mesa. Veja o que distribuí.|Neue Runde… und ich habe am Tisch gedreht. Sieh, was ich austeile.|Nuova mano… e ho toccato il tavolo. Guarda cosa ti do."],
    boss: ["¡Mi apuesta grande! Todo o nada, explorador.|My big bet! All or nothing, explorer.|Ma grosse mise ! Tout ou rien, explorateur.|Minha grande aposta! Tudo ou nada, explorador.|Mein großer Einsatz! Alles oder nichts, Entdecker.|La mia puntata grossa! Tutto o niente, esploratore."],
    good: ["Mmm… suerte de principiante.|Hmm… beginner's luck.|Mmm… la chance du débutant.|Hmm… sorte de principiante.|Hmm… Anfängerglück.|Mmm… fortuna del principiante.", "¡No está mal, no está mal!|Not bad, not bad!|Pas mal, pas mal !|Nada mal, nada mal!|Nicht schlecht, nicht schlecht!|Non male, non male!"],
    bull: ["¡¿Cómo lo has hecho?! ¡Eso no estaba en el guion!|How did you do that?! That wasn't in the script!|Comment as-tu fait ?! Ce n'était pas prévu !|Como você fez isso?! Isso não estava no roteiro!|Wie hast du das gemacht?! Das stand nicht im Drehbuch!|Come hai fatto?! Non era nel copione!", "¡Ay, mi corazón de crupier!|Oh, my dealer's heart!|Oh, mon cœur de croupier !|Ai, meu coração de crupiê!|Oh, mein Croupier-Herz!|Oh, il mio cuore da croupier!"],
    miss: ["¡Ja, ja, ja! ¡Ni de lejos!|Ha ha ha! Not even close!|Ha ha ha ! Même pas près !|Ha ha ha! Nem perto!|Ha ha ha! Nicht mal annähernd!|Ah ah ah! Neanche vicino!", "Buen intento… para otro mapa. ¡Ja!|Nice try… for another map. Ha!|Bel essai… pour une autre carte. Ha !|Boa tentativa… para outro mapa. Ha!|Netter Versuch… für eine andere Karte. Ha!|Bel tentativo… per un'altra mappa. Ah!"],
    timeout: ["El tiempo vuela… y tú no.|Time flies… and you don't.|Le temps vole… pas toi.|O tempo voa… e você não.|Die Zeit fliegt… du nicht.|Il tempo vola… tu no."],
    streak: ["¿Racha? No te acostumbres.|A streak? Don't get used to it.|Une série ? Ne t'y habitue pas.|Sequência? Não se acostume.|Eine Serie? Gewöhn dich nicht daran.|Una serie? Non abituarti."],
    counter: ["¿Un perk contra mi truco? Qué falta de deportividad…|A perk against my trick? How unsporting…|Un atout contre mon tour ? Quel manque de fair-play…|Um perk contra meu truque? Que falta de esportividade…|Ein Perk gegen meinen Trick? Wie unsportlich…|Un perk contro il mio trucco? Che poca sportività…"],
    roundWin: ["Esta vez ganas tú… esta vez.|You win this one… this time.|Cette fois tu gagnes… cette fois.|Desta vez você ganha… desta vez.|Diesmal gewinnst du… diesmal.|Stavolta vinci tu… stavolta."],
    roundFail: ["La banca siempre gana. Otra vez.|The house always wins. Again.|La banque gagne toujours. Encore.|A banca sempre ganha. De novo.|Die Bank gewinnt immer. Nochmal.|Il banco vince sempre. Di nuovo."],
    runWin: ["¡Imposible! Me has vaciado la mesa…|Impossible! You've cleaned out my table…|Impossible ! Tu as vidé ma table…|Impossível! Você limpou minha mesa…|Unmöglich! Du hast meinen Tisch leergeräumt…|Impossibile! Mi hai svuotato il tavolo…"],
    runLose: ["Fin de la partida. Vuelve cuando quieras… ¡Ja!|Game over. Come back any time… Ha!|Fin de partie. Reviens quand tu veux… Ha !|Fim de jogo. Volte quando quiser… Ha!|Spiel vorbei. Komm wieder, wann du willst… Ha!|Fine della partita. Torna quando vuoi… Ah!"],
    shaky: ["¿Te tiemblan las letras? A mí me tiembla la risa.|Letters trembling? I'm the one shaking with laughter.|Les lettres tremblent ? C'est moi qui tremble de rire.|As letras tremem? Eu é que tremo de rir.|Zittern die Buchstaben? Ich zittere vor Lachen.|Le lettere tremano? Io tremo dalle risate."],
    missing: ["Me he comido unas letras. Perdón. Ja.|I ate a few letters. Oops. Ha.|J'ai mangé quelques lettres. Oups. Ha.|Comi algumas letras. Ops. Ha.|Ich habe ein paar Buchstaben gegessen. Huch. Ha.|Ho mangiato qualche lettera. Ops. Ah."],
    swap: ["Las he barajado un poquito. Es mi trabajo.|I shuffled them a bit. It's my job.|Je les ai un peu mélangées. C'est mon métier.|Embaralhei um pouquinho. É meu trabalho.|Ich habe sie ein wenig gemischt. Das ist mein Job.|Le ho mescolate un po'. È il mio lavoro."],
    mirror: ["Hoy leemos al revés. ¡Qué divertido!|Today we read backwards. How fun!|Aujourd'hui on lit à l'envers. Amusant !|Hoje lemos ao contrário. Divertido!|Heute lesen wir rückwärts. Lustig!|Oggi leggiamo al contrario. Che divertente!"],
    nocountry: ["¿El país? Se me ha caído por la ventana.|The country? It fell out of the window.|Le pays ? Il est tombé par la fenêtre.|O país? Caiu pela janela.|Das Land? Ist aus dem Fenster gefallen.|Il paese? È caduto dalla finestra."],
    memory: ["Mira bien… porque esto se borra.|Look closely… it fades away.|Regarde bien… ça s'efface.|Olhe bem… isso some.|Schau genau hin… es verblasst.|Guarda bene… svanisce."],
    blur: ["¿Ves borroso? Es el humo de mi puro.|Blurry? That's the smoke from my cigar.|Flou ? C'est la fumée de mon cigare.|Turvo? É a fumaça do meu charuto.|Verschwommen? Das ist der Rauch meiner Zigarre.|Sfocato? È il fumo del mio sigaro."],
    dark: ["Ups, un cortocircuito. Qué casualidad…|Oops, a short circuit. What a coincidence…|Oups, un court-circuit. Quelle coïncidence…|Ops, um curto-circuito. Que coincidência…|Huch, ein Kurzschluss. Welch Zufall…|Ops, un cortocircuito. Che coincidenza…"],
    flicker: ["Las luces de este casino son… temperamentales.|The lights in this casino are… temperamental.|Les lumières de ce casino sont… capricieuses.|As luzes deste cassino são… temperamentais.|Die Lichter in diesem Casino sind… launisch.|Le luci di questo casinò sono… capricciose."],
    wrongborders: ["Estas fronteras las he dibujado yo. Confía en mí.|I drew these borders myself. Trust me.|J'ai dessiné ces frontières moi-même. Fais-moi confiance.|Eu mesmo desenhei essas fronteiras. Confie em mim.|Diese Grenzen habe ich selbst gezeichnet. Vertrau mir.|Questi confini li ho disegnati io. Fidati."],
    noborders: ["Fronteras fuera. ¿Quién las necesita?|Borders? Who needs them.|Les frontières ? Qui en a besoin.|Fronteiras? Quem precisa delas.|Grenzen? Wer braucht die schon.|I confini? Chi ne ha bisogno."],
    pangea: ["Bienvenido a Pangea: los continentes vuelven a estar juntos.|Welcome to Pangaea: the continents are back together.|Bienvenue en Pangée : les continents sont de nouveau réunis.|Bem-vindo à Pangeia: os continentes estão juntos de novo.|Willkommen in Pangäa: die Kontinente sind wieder vereint.|Benvenuto in Pangea: i continenti sono di nuovo uniti."],
    shuffle: ["He cambiado los continentes de sitio. Sorpresa.|I moved the continents around. Surprise.|J'ai déplacé les continents. Surprise.|Troquei os continentes de lugar. Surpresa.|Ich habe die Kontinente verschoben. Überraschung.|Ho spostato i continenti. Sorpresa."],
    flip: ["Hoy el Sur manda. ¡Bienvenido al revés!|Today the South is on top. Welcome upside down!|Aujourd'hui le Sud est en haut. Bienvenue à l'envers !|Hoje o Sul manda. Bem-vindo de cabeça para baixo!|Heute ist der Süden oben. Willkommen auf dem Kopf!|Oggi comanda il Sud. Benvenuto a testa in giù!"],
    clouds: ["Un poco de humo de sala. No tosas… mira.|A bit of smoke in the room. Don't cough… look.|Un peu de fumée dans la salle. Ne tousse pas… regarde.|Um pouco de fumaça na sala. Não tussa… olhe.|Etwas Rauch im Saal. Nicht husten… schau.|Un po' di fumo in sala. Non tossire… guarda."],
    upside: ["Hoy el mundo está cabeza abajo. ¡Y tú también!|Today the world is upside down. And so are you!|Aujourd'hui le monde est à l'envers. Et toi aussi !|Hoje o mundo está de cabeça para baixo. E você também!|Heute steht die Welt Kopf. Und du auch!|Oggi il mondo è capovolto. E anche tu!"],
    runes: ["Escribo en runas antiguas. ¿No las entiendes? Qué pena.|I write in ancient runes. Can't read them? Shame.|J'écris en runes anciennes. Tu ne comprends pas ? Dommage.|Escrevo em runas antigas. Não entende? Que pena.|Ich schreibe in alten Runen. Kannst du sie nicht lesen? Schade.|Scrivo in rune antiche. Non le capisci? Peccato."],
    scroll: ["¡Un letrero de neón! Tú lee rápido.|A neon sign! Read fast.|Une enseigne néon ! Lis vite.|Um letreiro de neon! Leia rápido.|Eine Neonschrift! Lies schnell.|Un'insegna al neon! Leggi in fretta."],
    novowels: ["Las vocales están en huelga. Ni una.|The vowels are on strike. Not one.|Les voyelles font grève. Pas une.|As vogais estão em greve. Nenhuma.|Die Vokale streiken. Kein einziger.|Le vocali sono in sciopero. Nemmeno una."],
    anagram: ["Agité las letras como un cóctel. ¡Ja!|I shook the letters like a cocktail. Ha!|J'ai secoué les lettres comme un cocktail. Ha !|Chacoalhei as letras como um coquetel. Ha!|Ich habe die Buchstaben wie einen Cocktail geschüttelt. Ha!|Ho shakerato le lettere come un cocktail. Ah!"],
    dance: ["¡Que baile el abecedario!|Let the alphabet dance!|Que l'alphabet danse !|Que o alfabeto dance!|Lasst das Alphabet tanzen!|Che l'alfabeto balli!"],
    riddle: ["Hoy no hay nombre. Solo una adivinanza.|No name today. Just a riddle.|Pas de nom aujourd'hui. Juste une devinette.|Hoje não há nome. Só uma adivinha.|Heute kein Name. Nur ein Rätsel.|Oggi niente nome. Solo un indovinello."],
    babel: ["Hoy hablamos todos los idiomas. Buena suerte.|Today we speak every language. Good luck.|Aujourd'hui on parle toutes les langues. Bonne chance.|Hoje falamos todos os idiomas. Boa sorte.|Heute sprechen wir alle Sprachen. Viel Glück.|Oggi parliamo tutte le lingue. Buona fortuna."],
    spread: ["Los continentes necesitaban espacio. Big bang.|The continents needed space. Big bang.|Les continents avaient besoin d'espace. Big bang.|Os continentes precisavam de espaço. Big bang.|Die Kontinente brauchten Platz. Urknall.|I continenti volevano spazio. Big bang."],
    tilt: ["Endereza los continentes tú, si puedes.|Straighten the continents yourself, if you can.|Redresse les continents toi-même, si tu peux.|Endireite os continentes você mesmo, se puder.|Richte die Kontinente selbst auf, wenn du kannst.|Raddrizza i continenti da solo, se ci riesci."],
    spin: ["¡Ruleta! El mapa gira… y tú con él.|Roulette! The map spins… and so do you.|Roulette ! La carte tourne… et toi aussi.|Roleta! O mapa gira… e você junto.|Roulette! Die Karte dreht sich… und du mit.|Roulette! La mappa gira… e tu con lei."],
    mirrorx: ["Este es Oeste, Oeste es Este. Simple.|East is West, West is East. Simple.|L'Est est l'Ouest, l'Ouest est l'Est. Simple.|Leste é Oeste, Oeste é Leste. Simples.|Ost ist West, West ist Ost. Einfach.|Est è Ovest, Ovest è Est. Semplice."],
    myopia: ["Ay, no ves bien justo donde miras. Qué mala suerte.|Oh, you can't see well right where you look. Bad luck.|Oh, tu ne vois pas bien là où tu regardes. Pas de chance.|Ah, você não vê bem onde olha. Azar.|Oh, du siehst genau dort schlecht, wo du hinschaust. Pech.|Oh, non vedi bene proprio dove guardi. Sfortuna."],
    blindspot: ["Tengo un punto ciego… justo donde apuntas.|I have a blind spot… right where you aim.|J'ai un angle mort… juste là où tu vises.|Tenho um ponto cego… bem onde você mira.|Ich habe einen blinden Fleck… genau dort, wo du zielst.|Ho un punto cieco… proprio dove mira."],
    mosaic: ["Ahorro en resolución. Píxeles gordos para todos.|Saving on resolution. Chunky pixels for everyone.|J'économise sur la résolution. Gros pixels pour tous.|Economizo na resolução. Pixels gordos para todos.|Ich spare an Auflösung. Grobe Pixel für alle.|Risparmio sulla risoluzione. Pixel giganti per tutti."],
    negative: ["Todo al revés… hasta los colores.|Everything backwards… even the colors.|Tout à l'envers… même les couleurs.|Tudo ao contrário… até as cores.|Alles verkehrt… sogar die Farben.|Tutto al contrario… anche i colori."],
    quake: ["¿Has notado el temblor? Yo no he sido.|Did you feel the tremor? Wasn't me.|Tu as senti la secousse ? Ce n'était pas moi.|Sentiu o tremor? Não fui eu.|Hast du das Beben gespürt? Ich war's nicht.|Hai sentito il tremore? Non sono stato io."],
    drift: ["El mapa se va solo. Sigue el ritmo.|The map slips away. Keep up.|La carte s'en va toute seule. Suis le rythme.|O mapa vai embora sozinho. Acompanhe.|Die Karte gleitet davon. Halt mit.|La mappa se ne va da sola. Tieni il passo."],
    decoys: ["Puse unas chinchetas de más. Por si acaso.|I put a few extra pins. Just in case.|J'ai mis quelques épingles en trop. Au cas où.|Coloquei uns pinos a mais. Por via das dúvidas.|Ich habe ein paar Pins zu viel gesetzt. Für alle Fälle.|Ho messo qualche pin in più. Non si sa mai."],
    lightning: ["¡Rayos! Qué efecto tan… iluminador.|Lightning! What an… illuminating effect.|Des éclairs ! Un effet… éclairant.|Raios! Que efeito… iluminador.|Blitze! Ein wahrlich… erleuchtender Effekt.|Fulmini! Che effetto… illuminante."],
    rain: ["Llueve en el casino. Ups.|It's raining in the casino. Oops.|Il pleut dans le casino. Oups.|Chove no cassino. Ops.|Es regnet im Casino. Huch.|Piove nel casinò. Ops."],
    tremble: ["¿Te tiembla el pulso? A mí me encanta.|Does your hand shake? I love it.|Ta main tremble ? J'adore.|Sua mão treme? Eu adoro.|Zittert deine Hand? Ich liebe es.|Ti trema la mano? Adoro."],
    blink: ["Ahora me ves… ahora no.|Now you see me… now you don't.|Maintenant tu me vois… maintenant non.|Agora você me vê… agora não.|Jetzt siehst du mich… jetzt nicht.|Ora mi vedi… ora no."],
    ghost: ["Tu puntero se ha ido de paseo. Ja.|Your pointer went for a walk. Ha.|Ton pointeur est parti se promener. Ha.|Seu ponteiro saiu para passear. Ha.|Dein Zeiger ist spazieren gegangen. Ha.|Il tuo puntatore è andato a spasso. Ah."],
    cblur: ["Le he quitado el foco a tu puntero.|I took the focus off your pointer.|J'ai retiré la mise au point de ton pointeur.|Tirei o foco do seu ponteiro.|Ich habe deinen Zeiger unscharf gestellt.|Ho tolto la messa a fuoco al tuo puntatore."],
    lag: ["Ups, ¿va lento el internet del casino?|Oops, is the casino Wi-Fi slow?|Oups, le Wi-Fi du casino est lent ?|Ops, o Wi-Fi do cassino está lento?|Huch, ist das Casino-WLAN langsam?|Ops, il Wi-Fi del casinò è lento?"],
    cmirror: ["Derecha es izquierda. Izquierda es derecha. ¡Ja!|Right is left. Left is right. Ha!|La droite est la gauche. La gauche est la droite. Ha !|Direita é esquerda. Esquerda é direita. Ha!|Rechts ist links. Links ist rechts. Ha!|Destra è sinistra. Sinistra è destra. Ah!"],
    dizzy: ["Un cóctel de más y todo da vueltas.|One cocktail too many and everything spins.|Un cocktail de trop et tout tourne.|Um coquetel a mais e tudo gira.|Ein Cocktail zu viel und alles dreht sich.|Un cocktail di troppo e tutto gira."],
    bribe: ["¿Sobornarme? Qué poco elegante… Acepto.|Bribe me? How tacky… I accept.|Me soudoyer ? Quelle vulgarité… J'accepte.|Me subornar? Que deselegante… Aceito.|Mich bestechen? Wie stillos… Ich nehme an.|Corrompermi? Che volgarità… Accetto."],
    reroll: ["Barajo de nuevo. La suerte es mía.|Shuffling again. Luck is mine.|Je mélange à nouveau. La chance est à moi.|Embaralho de novo. A sorte é minha.|Ich mische neu. Das Glück gehört mir.|Rimescolo. La fortuna è mia."],
    wind: ["¡Vendaval! Apunta con la cabeza.|Gale! Aim with your head.|Rafale ! Vise avec la tête.|Vendaval! Mire com a cabeça.|Sturm! Ziel mit dem Kopf.|Bufera! Mira con la testa."],
    storm: ["El reloj corre más rápido esta noche.|The clock runs faster tonight.|L'horloge tourne plus vite ce soir.|O relógio corre mais rápido esta noite.|Die Uhr läuft heute schneller.|L'orologio corre più veloce stasera."],
    silence: ["Shhh. Tus juguetes se quedan en silencio.|Shhh. Your toys stay silent.|Chut. Tes jouets restent muets.|Shhh. Seus brinquedos ficam em silêncio.|Pssst. Deine Spielzeuge bleiben stumm.|Shhh. I tuoi giocattoli restano muti."],

    /* ---------------------------------------------------------------- pantalla principal: apariciones al azar mientras eliges modo (nunca durante una partida) */
    homeTaunt: [
      "¿A que no sabes ni dónde queda esto? Adelante, sorpréndeme.|Bet you don't even know where this is. Go on, surprise me.|Je parie que tu ne sais même pas où c'est. Vas-y, surprends-moi.|Aposto que nem sabe onde fica isso. Vamos, me surpreenda.|Wetten, du weißt nicht mal, wo das liegt? Los, überrasch mich.|Scommetto che non sai nemmeno dove si trova. Forza, sorprendimi.",
      "Ese país de ahí… ni idea, ¿eh? Tranquilo, a nadie le importa.|That country over there… no clue, huh? Relax, nobody's judging.|Ce pays-là… aucune idée, hein ? Tranquille, personne ne juge.|Aquele país ali… nem ideia, né? Relaxa, ninguém está julgando.|Dieses Land dort drüben… keine Ahnung, oder? Entspann dich, keiner urteilt.|Quel paese laggiù… nessuna idea, eh? Tranquillo, nessuno giudica.",
      "Vamos, atrévete a sentarte. O sigue mirando el mapa desde ahí, cobarde.|Come on, dare to sit down. Or keep staring at the map from over there, coward.|Allez, ose t'asseoir. Ou continue à fixer la carte de loin, peureux.|Vamos, tenha coragem de sentar. Ou fique só olhando o mapa daí, covarde.|Los, trau dich zu setzen. Oder starr weiter von dort auf die Karte, Feigling.|Dai, osa sederti. O continua a fissare la mappa da lì, coniglio.",
      "¿Miedo a fallar? Aquí todos fallan. Yo me río igual.|Scared of missing? Everyone misses here. I laugh either way.|Peur de te tromper ? Tout le monde se trompe ici. Je ris quand même.|Medo de errar? Todo mundo erra aqui. Eu rio de qualquer jeito.|Angst vor Fehlern? Hier scheitert jeder. Ich lache trotzdem.|Paura di sbagliare? Qui sbagliano tutti. Io rido comunque.",
      "Seguro que confundes un continente con otro. Es un clásico.|I bet you mix up continents. It's a classic.|Je parie que tu confonds les continents. Un classique.|Aposto que você confunde continentes. É clássico.|Wetten, du verwechselst Kontinente. Ein Klassiker.|Scommetto che confondi i continenti. Un classico.",
      "¿Sabes jugarte unos doblones o solo mirar el escaparate?|Do you know how to bet a few doubloons, or just window-shop?|Tu sais miser quelques doublons, ou juste lécher la vitrine ?|Sabe apostar uns dobrões ou só olhar a vitrine?|Kannst du ein paar Dublonen setzen, oder nur Schaufenster gucken?|Sai puntare qualche dobbline o guardi solo la vetrina?",
      "La mesa lleva rato esperándote. No le hagas el feo.|The table's been waiting a while. Don't leave it hanging.|La table t'attend depuis un moment. Ne la laisse pas en plan.|A mesa está esperando faz tempo. Não deixe ela na mão.|Der Tisch wartet schon eine Weile. Lass ihn nicht hängen.|Il tavolo aspetta da un po'. Non lasciarlo in sospeso.",
      "¿Y si empezamos con algo fácil? Ah, no, contigo nunca es fácil.|How about we start with something easy? Oh wait, nothing's easy with you.|Et si on commençait facile ? Ah non, rien n'est facile avec toi.|Que tal começarmos fácil? Ah, nada é fácil com você.|Fangen wir mit etwas Leichtem an? Ach nein, bei dir ist nichts leicht.|Iniziamo con qualcosa di facile? Ah no, con te niente è facile.",
      "Tu geografía y mi paciencia se parecen: las dos son cortas.|Your geography and my patience have one thing in common: both are short.|Ta géographie et ma patience ont un point commun : les deux sont courtes.|Sua geografia e minha paciência têm algo em comum: as duas são curtas.|Deine Geografie und meine Geduld haben eins gemeinsam: beide sind kurz.|La tua geografia e la mia pazienza hanno una cosa in comune: sono entrambe corte.",
      "No hace falta que finjas que sabes. Aquí todos sabemos que no.|No need to pretend you know. We all know you don't.|Pas besoin de faire semblant de savoir. On sait tous que non.|Não precisa fingir que sabe. Todos aqui sabemos que não.|Du musst nicht so tun, als wüsstest du es. Wir alle wissen es besser.|Non serve fingere di saperlo. Sappiamo tutti che non è così.",
      "Un mapa, un puntero y tu ego. A ver cuál se rompe antes.|A map, a pointer and your ego. Let's see which one breaks first.|Une carte, un pointeur et ton ego. Voyons lequel craque en premier.|Um mapa, um ponteiro e o seu ego. Vamos ver qual quebra primeiro.|Eine Karte, ein Zeiger und dein Ego. Mal sehen, was zuerst zerbricht.|Una mappa, un puntatore e il tuo ego. Vediamo chi si rompe prima.",
      "Relájate. Total, ya sabemos cómo va a acabar esto.|Relax. We both know how this ends.|Détends-toi. On sait déjà comment ça va finir.|Relaxa. A gente já sabe como isso termina.|Entspann dich. Wir wissen beide, wie das endet.|Rilassati. Sappiamo già come andrà a finire.",
      "¿Nervioso? El mapa no muerde. Yo, un poco sí.|Nervous? The map doesn't bite. Me, a little bit.|Nerveux ? La carte ne mord pas. Moi, un peu quand même.|Nervoso? O mapa não morde. Eu, um pouquinho sim.|Nervös? Die Karte beißt nicht. Ich schon ein bisschen.|Nervoso? La mappa non morde. Io un po' sì.",
      "Cada clic tuyo es una pequeña obra de arte… del fracaso.|Every click of yours is a tiny work of art… of failure.|Chacun de tes clics est une petite œuvre d'art… de l'échec.|Cada clique seu é uma pequena obra de arte… do fracasso.|Jeder deiner Klicks ist ein kleines Kunstwerk… des Scheiterns.|Ogni tuo clic è una piccola opera d'arte… del fallimento.",
      "No sé qué me da más pena, el mapa o tu cara ahora mismo.|Not sure what's sadder right now, the map or your face.|Je ne sais pas ce qui est le plus triste, la carte ou ton visage.|Não sei o que é mais triste agora, o mapa ou sua cara.|Ich weiß nicht, was trauriger ist, die Karte oder dein Gesicht gerade.|Non so cosa sia più triste ora, la mappa o la tua faccia.",
      "Adelante, haz como que lo piensas. A mí no me engañas.|Go on, pretend you're thinking it over. You're not fooling me.|Vas-y, fais semblant de réfléchir. Tu ne me trompes pas.|Vá, finja que está pensando. Não me engana.|Los, tu so, als würdest du nachdenken. Mich täuschst du nicht.|Dai, fai finta di pensarci. Non inganni me.",
      "Cuánta confianza para alguien que aún no ha hecho clic.|Such confidence for someone who hasn't even clicked yet.|Quelle assurance pour quelqu'un qui n'a même pas encore cliqué.|Que confiança para quem ainda nem clicou.|So viel Selbstvertrauen für jemanden, der noch nicht mal geklickt hat.|Che sicurezza per uno che non ha ancora nemmeno cliccato.",
      "Yo aquí, tú ahí mirando. Alguno de los dos tiene que moverse.|Me here, you there staring. One of us has to move.|Moi ici, toi là à regarder. Il faut bien que l'un de nous bouge.|Eu aqui, você aí olhando. Alguém tem que se mexer.|Ich hier, du dort am Starren. Einer von uns muss sich bewegen.|Io qui, tu lì che guardi. Qualcuno di noi due deve muoversi.",
      "¿Sabes lo que más me gusta de ti? Que siempre vuelves a intentarlo.|You know what I like most about you? You always try again.|Tu sais ce que je préfère chez toi ? Tu réessaies toujours.|Sabe o que eu mais gosto em você? Você sempre tenta de novo.|Weißt du, was ich an dir am meisten mag? Du versuchst es immer wieder.|Sai cosa mi piace di più di te? Che ci riprovi sempre.",
      "Ya verás qué fácil es… decir eso y luego fallar estrepitosamente.|You'll see how easy it is… to say that and then fail spectacularly.|Tu vas voir comme c'est facile… de dire ça et d'échouer lamentablement.|Você vai ver como é fácil… dizer isso e depois falhar feio.|Du wirst sehen, wie leicht es ist… das zu sagen und dann grandios zu scheitern.|Vedrai com'è facile… dirlo e poi fallire clamorosamente.",
    ],
    homeTempt: [
      "Psst… una partida rápida. Nadie tiene por qué enterarse.|Psst… one quick round. No one has to know.|Psst… une partie rapide. Personne n'a besoin de savoir.|Psst… uma partida rápida. Ninguém precisa saber.|Psst… eine schnelle Runde. Keiner muss es wissen.|Psst… una partita veloce. Nessuno deve saperlo.",
      "Los doblones no se ganan solos, explorador.|Doubloons don't win themselves, explorer.|Les doublons ne se gagnent pas tout seuls, explorateur.|Os dobrões não se ganham sozinhos, explorador.|Dublonen gewinnen sich nicht von selbst, Entdecker.|I dobloni non si vincono da soli, esploratore.",
      "El mapa está calentito. Ven a tocarlo.|The map's still warm. Come touch it.|La carte est encore chaude. Viens la toucher.|O mapa ainda está quentinho. Venha tocar.|Die Karte ist noch warm. Komm, berühr sie.|La mappa è ancora calda. Vieni a toccarla.",
      "Una manita más y lo dejamos… como todos dicen.|Just one more hand and we stop… like everyone says.|Encore une main et on arrête… comme tout le monde dit.|Só mais uma mão e paramos… como todo mundo diz.|Nur noch eine Runde, dann hören wir auf… wie alle sagen.|Ancora una mano e la finiamo… come dicono tutti.",
      "Tengo una silla libre en mi mesa. Con tu nombre.|I've got an empty seat at my table. With your name on it.|J'ai une place libre à ma table. À ton nom.|Tenho uma cadeira livre na minha mesa. Com seu nome.|Ich habe einen freien Platz an meinem Tisch. Mit deinem Namen drauf.|Ho un posto libero al mio tavolo. Con il tuo nome.",
      "¿Y si esta vez me ganas de verdad? Casi me lo creo.|What if you actually beat me this time? I almost believe it.|Et si cette fois tu me battais vraiment ? J'y crois presque.|E se desta vez você realmente me vencer? Quase acredito.|Was, wenn du mich diesmal wirklich schlägst? Fast glaube ich das.|E se stavolta mi battessi davvero? Quasi ci credo.",
      "El casino nunca cierra. Tú tampoco deberías.|The casino never closes. Neither should you.|Le casino ne ferme jamais. Toi non plus, tu ne devrais pas.|O cassino nunca fecha. Você também não deveria.|Das Casino schließt nie. Du solltest das auch nicht.|Il casinò non chiude mai. Nemmeno tu dovresti.",
      "Solo una partidita. Como las patatas fritas, nunca es solo una.|Just one little round. Like chips, it's never just one.|Juste une petite partie. Comme les chips, jamais une seule.|Só uma partidinha. Como batata frita, nunca é só uma.|Nur eine kleine Runde. Wie Chips, nie bleibt es bei einer.|Solo una partitella. Come le patatine, non è mai una sola.",
      "Mira el mapa. Míralo bien. ¿A que ya quieres jugar?|Look at the map. Really look. Don't you want to play already?|Regarde la carte. Bien regarde. Tu n'as pas déjà envie de jouer ?|Olhe o mapa. Olhe bem. Já não quer jogar?|Schau dir die Karte an. Genau hinschauen. Willst du nicht schon spielen?|Guarda la mappa. Guardala bene. Non hai già voglia di giocare?",
      "Ven, ven. Aquí no muerde nadie… mucho.|Come, come. Nobody bites here… much.|Viens, viens. Personne ne mord ici… trop.|Vem, vem. Ninguém morde aqui… muito.|Komm schon. Hier beißt keiner… allzu sehr.|Vieni, vieni. Qui non morde nessuno… troppo.",
      "Tengo cartas nuevas esperándote. Literalmente. Ven a verlas.|I've got new cards waiting for you. Literally. Come see them.|J'ai de nouvelles cartes qui t'attendent. Littéralement. Viens voir.|Tenho cartas novas te esperando. Literalmente. Venha ver.|Ich habe neue Karten für dich. Wortwörtlich. Komm sie dir ansehen.|Ho carte nuove che ti aspettano. Letteralmente. Vieni a vederle.",
      "Ese botón de 'Nueva partida'… se ve solito. Dale cariño.|That 'New game' button… looks lonely. Give it some love.|Ce bouton 'Nouvelle partie'… il a l'air seul. Donne-lui de l'amour.|Esse botão de 'Nova partida'… parece sozinho. Dê carinho a ele.|Dieser 'Neues Spiel'-Knopf… sieht so einsam aus. Gib ihm Liebe.|Quel pulsante 'Nuova partita'… sembra solo soletto. Dagli un po' d'amore.",
      "Anda, juega. Luego me lo agradeces… o me maldices. Lo que sea.|Go on, play. You'll thank me later… or curse me. Either way.|Allez, joue. Tu me remercieras… ou tu me maudiras. Peu importe.|Vai, jogue. Depois me agradece… ou me xinga. Tanto faz.|Los, spiel schon. Später dankst du mir… oder verfluchst mich. Egal.|Dai, gioca. Poi mi ringrazi… o mi maledici. Fa lo stesso.",
      "Nadie ha ganado nunca sin jugar. Bueno, tú tampoco jugando, pero inténtalo.|Nobody's ever won without playing. Well, you might not either, but try.|Personne n'a jamais gagné sans jouer. Toi non plus peut-être, mais essaie.|Ninguém nunca ganhou sem jogar. Bem, você também não jogando, mas tente.|Niemand hat je gewonnen, ohne zu spielen. Na gut, du vielleicht auch nicht, aber versuch's.|Nessuno ha mai vinto senza giocare. Beh, forse nemmeno tu giocando, ma prova.",
      "Confiésalo: llevas un rato mirando esa carta de Aventura.|Admit it: you've been eyeing that Adventure card for a while.|Avoue : tu regardes cette carte Aventure depuis un moment.|Admita: já tem um tempo que está de olho nessa carta de Aventura.|Gib's zu: du starrst schon eine Weile auf diese Abenteuer-Karte.|Ammettilo: guardi quella carta Avventura da un bel po'.",
      "Doblones gratis no doy, pero diversión sí. Un trato justo, ¿no?|I don't hand out free doubloons, but I do hand out fun. Fair deal, right?|Je ne donne pas de doublons gratuits, mais du plaisir oui. Ça te va ?|Dobrões grátis eu não dou, mas diversão sim. Trato justo, né?|Gratis-Dublonen gibt's von mir nicht, aber Spaß schon. Fairer Deal, oder?|Dobloni gratis non ne do, ma divertimento sì. Affare giusto, no?",
      "El mundo entero cabe en esta mesa. Ven a recorrerlo conmigo.|The whole world fits on this table. Come explore it with me.|Le monde entier tient sur cette table. Viens l'explorer avec moi.|O mundo inteiro cabe nesta mesa. Venha explorá-lo comigo.|Die ganze Welt passt auf diesen Tisch. Komm, erkunde sie mit mir.|Il mondo intero sta su questo tavolo. Vieni a esplorarlo con me.",
      "¿Cinco minutos? En esta mesa el tiempo vuela… normalmente en mi contra.|Five minutes? Time flies at this table… usually against me.|Cinq minutes ? Le temps file à cette table… souvent contre moi.|Cinco minutos? O tempo voa nesta mesa… geralmente contra mim.|Fünf Minuten? An diesem Tisch vergeht die Zeit… meist zu meinen Ungunsten.|Cinque minuti? A questo tavolo il tempo vola… di solito contro di me.",
    ],
    homeTrivia: [
      "¿Sabías que Rusia cruza 11 husos horarios? Ni yo doy tantas vueltas en una noche.|Did you know Russia spans 11 time zones? Even I don't spin that much in one night.|Tu savais que la Russie traverse 11 fuseaux horaires ? Même moi je ne tourne pas autant en une nuit.|Sabia que a Rússia atravessa 11 fusos horários? Nem eu giro tanto assim numa noite.|Wusstest du, dass Russland 11 Zeitzonen umfasst? Nicht mal ich drehe mich so oft an einem Abend.|Sapevi che la Russia attraversa 11 fusi orari? Nemmeno io giro così tanto in una notte.",
      "El Nilo mide más de 6.500 km. Y tú sin saber ni tu propia capital.|The Nile is over 6,500 km long. And you don't even know your own capital.|Le Nil fait plus de 6 500 km. Et toi, tu ne connais même pas ta propre capitale.|O Nilo tem mais de 6.500 km. E você nem sabe a própria capital.|Der Nil ist über 6.500 km lang. Und du kennst nicht mal deine eigene Hauptstadt.|Il Nilo è lungo oltre 6.500 km. E tu non conosci nemmeno la tua capitale.",
      "El Vaticano es el país más pequeño del mundo. Como tu paciencia para estudiar geografía.|The Vatican is the smallest country in the world. Like your patience for studying geography.|Le Vatican est le plus petit pays du monde. Comme ta patience pour étudier la géographie.|O Vaticano é o menor país do mundo. Igual à sua paciência para estudar geografia.|Der Vatikan ist das kleinste Land der Welt. Wie deine Geduld beim Geografie-Lernen.|Il Vaticano è il paese più piccolo del mondo. Come la tua pazienza nello studiare geografia.",
      "Canadá tiene más lagos que el resto del planeta junto. A ver si aciertas uno.|Canada has more lakes than the rest of the planet combined. Let's see if you can name one.|Le Canada a plus de lacs que le reste de la planète réunie. Voyons si tu en trouves un.|O Canadá tem mais lagos que o resto do planeta junto. Vamos ver se você acerta um.|Kanada hat mehr Seen als der Rest der Welt zusammen. Mal sehen, ob du einen triffst.|Il Canada ha più laghi del resto del pianeta messo insieme. Vediamo se ne indovini uno.",
      "El Sáhara es casi tan grande como Estados Unidos. Y tú perdido en tu propio barrio.|The Sahara is almost as big as the United States. And you get lost in your own neighborhood.|Le Sahara est presque aussi grand que les États-Unis. Et toi, tu te perds dans ton propre quartier.|O Saara é quase do tamanho dos Estados Unidos. E você se perde no próprio bairro.|Die Sahara ist fast so groß wie die USA. Und du verläufst dich in deiner eigenen Nachbarschaft.|Il Sahara è quasi grande quanto gli Stati Uniti. E tu ti perdi nel tuo stesso quartiere.",
      "Australia es una isla, un país y un continente a la vez. Presume de eso en la próxima mano.|Australia is an island, a country and a continent all at once. Brag about that on the next hand.|L'Australie est une île, un pays et un continent à la fois. Vante-toi de ça à la prochaine main.|A Austrália é uma ilha, um país e um continente ao mesmo tempo. Se gabe disso na próxima mão.|Australien ist Insel, Land und Kontinent zugleich. Prahl damit bei der nächsten Runde.|L'Australia è un'isola, un paese e un continente insieme. Vantatene alla prossima mano.",
      "Groenlandia parece enorme en el mapa… y en realidad cabe varias veces en África. Sorpresa.|Greenland looks huge on the map… and it actually fits inside Africa several times over. Surprise.|Le Groenland paraît énorme sur la carte… et il tient plusieurs fois dans l'Afrique. Surprise.|A Groenlândia parece enorme no mapa… e na verdade cabe várias vezes dentro da África. Surpresa.|Grönland sieht auf der Karte riesig aus… und passt tatsächlich mehrfach in Afrika. Überraschung.|La Groenlandia sembra enorme sulla mappa… e in realtà ci sta più volte dentro l'Africa. Sorpresa.",
      "Mongolia tiene la densidad de población más baja del planeta. Como tu interés por estudiar, oye.|Mongolia has the lowest population density on the planet. Kind of like your interest in studying.|La Mongolie a la densité de population la plus basse de la planète. Comme ton intérêt pour étudier.|A Mongólia tem a menor densidade populacional do planeta. Tipo seu interesse em estudar.|Die Mongolei hat die niedrigste Bevölkerungsdichte der Welt. So wie dein Interesse am Lernen.|La Mongolia ha la densità di popolazione più bassa del pianeta. Un po' come il tuo interesse a studiare.",
      "Chile mide más de 4.300 km de norte a sur y apenas 180 de ancho. Un fideo con playa.|Chile stretches over 4,300 km north to south and barely 180 km wide. A noodle with a beach.|Le Chili s'étend sur plus de 4 300 km du nord au sud et à peine 180 de large. Une nouille avec une plage.|O Chile tem mais de 4.300 km de norte a sul e apenas 180 de largura. Um macarrão com praia.|Chile erstreckt sich über 4.300 km von Nord nach Süd und ist kaum 180 km breit. Eine Nudel mit Strand.|Il Cile si estende per oltre 4.300 km da nord a sud ed è largo appena 180 km. Uno spaghetto con la spiaggia.",
      "Filipinas tiene más de 7.000 islas. Tú, con encontrar una, ya vas que chutas.|The Philippines has over 7,000 islands. You, finding just one, would already be doing great.|Les Philippines comptent plus de 7 000 îles. Toi, en trouver une seule, ce serait déjà bien.|As Filipinas têm mais de 7.000 ilhas. Você, achando uma só, já está indo bem.|Die Philippinen haben über 7.000 Inseln. Für dich wäre schon eine einzige ein Erfolg.|Le Filippine hanno oltre 7.000 isole. Tu, trovarne anche solo una, saresti già a buon punto.",
      "Lesoto está completamente rodeado por Sudáfrica. Un país dentro de otro, como una muñeca rusa de verdad.|Lesotho is entirely surrounded by South Africa. A country inside another, like a real matryoshka doll.|Le Lesotho est entièrement entouré par l'Afrique du Sud. Un pays dans un autre, une vraie poupée russe.|O Lesoto está totalmente cercado pela África do Sul. Um país dentro de outro, como uma boneca russa de verdade.|Lesotho ist komplett von Südafrika umgeben. Ein Land im Land, wie eine echte Matroschka.|Il Lesotho è completamente circondato dal Sudafrica. Un paese dentro un altro, come una vera matrioska.",
      "Brasil hace frontera con casi todos los países de Sudamérica, menos Chile y Ecuador. Ni el mapa se libra de él.|Brazil borders almost every South American country except Chile and Ecuador. Not even the map escapes it.|Le Brésil est frontalier de presque tous les pays d'Amérique du Sud, sauf le Chili et l'Équateur. Même la carte n'y échappe pas.|O Brasil faz fronteira com quase todos os países da América do Sul, menos Chile e Equador. Nem o mapa escapa dele.|Brasilien grenzt an fast jedes südamerikanische Land außer Chile und Ecuador. Nicht mal die Karte entkommt ihm.|Il Brasile confina con quasi tutti i paesi del Sud America, tranne Cile ed Ecuador. Nemmeno la mappa gli sfugge.",
      "El Transiberiano recorre 9.289 km. Más de lo que tú aguantas mirando un mapa sin bostezar.|The Trans-Siberian Railway runs 9,289 km. Longer than you can look at a map without yawning.|Le Transsibérien parcourt 9 289 km. Plus long que ce que tu tiens à regarder une carte sans bâiller.|A Transiberiana percorre 9.289 km. Mais do que você aguenta olhando um mapa sem bocejar.|Die Transsibirische Eisenbahn fährt 9.289 km. Länger, als du eine Karte ohne Gähnen ansehen kannst.|La Transiberiana percorre 9.289 km. Più di quanto tu resista a guardare una mappa senza sbadigliare.",
      "Bután mide su éxito con la 'Felicidad Nacional Bruta'. Aquí medimos el tuyo con lástima.|Bhutan measures success with 'Gross National Happiness'. Here we measure yours with pity.|Le Bhoutan mesure sa réussite avec le 'Bonheur National Brut'. Ici on mesure la tienne avec de la pitié.|O Butão mede seu sucesso com a 'Felicidade Nacional Bruta'. Aqui medimos a sua com pena.|Bhutan misst seinen Erfolg mit dem 'Bruttonationalglück'. Hier messen wir deins mit Mitleid.|Il Bhutan misura il successo con la 'Felicità Nazionale Lorda'. Qui misuriamo il tuo con la pietà.",
      "Indonesia abarca ella sola tres husos horarios. Ni que fuera un país o algo.|Indonesia spans three time zones all by itself. As if it were a whole country or something.|L'Indonésie couvre à elle seule trois fuseaux horaires. Comme si c'était tout un pays, tiens.|A Indonésia abrange sozinha três fusos horários. Como se fosse um país inteiro, ou algo assim.|Indonesien allein umfasst drei Zeitzonen. Als wäre es ein ganzes Land oder so.|L'Indonesia da sola copre tre fusi orari. Come se fosse un intero paese, o giù di lì.",
      "El Mar Muerto es el punto más bajo de la superficie terrestre. Casi tan bajo como tu puntería.|The Dead Sea is the lowest point on Earth's land surface. Almost as low as your aim.|La mer Morte est le point le plus bas de la surface terrestre. Presque aussi bas que ta précision.|O Mar Morto é o ponto mais baixo da superfície terrestre. Quase tão baixo quanto sua mira.|Das Tote Meer ist der tiefste Punkt der Landoberfläche der Erde. Fast so niedrig wie deine Treffsicherheit.|Il Mar Morto è il punto più basso della superficie terrestre. Quasi basso quanto la tua mira.",
      "Nueva Zelanda fue de los últimos grandes territorios en poblarse. Como tú aprendiendo geografía: nunca es tarde.|New Zealand was one of the last major landmasses to be settled. Like you learning geography: never too late.|La Nouvelle-Zélande fut l'un des derniers grands territoires peuplés. Comme toi et la géographie : jamais trop tard.|A Nova Zelândia foi um dos últimos grandes territórios a ser povoado. Tipo você aprendendo geografia: nunca é tarde.|Neuseeland war eine der letzten großen Landmassen, die besiedelt wurden. Wie bei dir mit Geografie: nie zu spät.|La Nuova Zelanda fu una delle ultime grandi terre a essere popolate. Come te con la geografia: mai troppo tardi.",
      "Chad tiene más de 200 grupos étnicos. Y tú sin saber ni el tuyo, seguramente.|Chad has over 200 ethnic groups. And you probably don't even know your own.|Le Tchad compte plus de 200 groupes ethniques. Et toi, tu ne connais sûrement même pas le tien.|O Chade tem mais de 200 grupos étnicos. E você provavelmente nem sabe o seu.|Der Tschad hat über 200 ethnische Gruppen. Und du kennst wahrscheinlich nicht mal deine eigene.|Il Ciad ha oltre 200 gruppi etnici. E tu probabilmente non conosci nemmeno il tuo.",
      "Singapur es más pequeño que la ciudad de Nueva York. Y aun así te lo pondría difícil.|Singapore is smaller than New York City. And it would still give you a hard time.|Singapour est plus petit que la ville de New York. Et il te donnerait quand même du fil à retordre.|Singapura é menor que a cidade de Nova York. E ainda assim te daria trabalho.|Singapur ist kleiner als die Stadt New York. Und würde dir trotzdem Kopfzerbrechen bereiten.|Singapore è più piccola della città di New York. E comunque ti metterebbe in difficoltà.",
      "Turquía tiene territorio en Europa y en Asia a la vez. Ni tú sabes en qué continente estás ahora mismo.|Turkey has territory in both Europe and Asia. You don't even know which continent you're on right now.|La Turquie a un territoire en Europe et en Asie à la fois. Toi, tu ne sais même pas sur quel continent tu es.|A Turquia tem território na Europa e na Ásia ao mesmo tempo. Você nem sabe em que continente está agora.|Die Türkei hat Gebiet in Europa und Asien zugleich. Du weißt nicht mal, auf welchem Kontinent du gerade bist.|La Turchia ha territorio sia in Europa che in Asia. Tu non sai nemmeno in che continente sei ora.",
      "Kazajistán es el país sin salida al mar más grande del mundo. Como tu suerte hoy: sin salida.|Kazakhstan is the largest landlocked country in the world. Like your luck today: no way out.|Le Kazakhstan est le plus grand pays enclavé du monde. Comme ta chance aujourd'hui : sans issue.|O Cazaquistão é o maior país sem litoral do mundo. Igual sua sorte hoje: sem saída.|Kasachstan ist das größte Binnenland der Welt. Wie dein Glück heute: kein Ausweg.|Il Kazakistan è il più grande paese senza sbocco sul mare del mondo. Come la tua fortuna oggi: senza via d'uscita.",
      "El Amazonas lleva más agua que los siguientes siete ríos más grandes juntos. Como mi paciencia, que también se desborda.|The Amazon carries more water than the next seven biggest rivers combined. Like my patience, which also overflows.|L'Amazone transporte plus d'eau que les sept plus grands fleuves suivants réunis. Comme ma patience, qui déborde aussi.|O Amazonas carrega mais água que os sete rios seguintes juntos. Igual minha paciência, que também transborda.|Der Amazonas führt mehr Wasser als die nächsten sieben größten Flüsse zusammen. Wie meine Geduld, die auch überläuft.|Il Rio delle Amazzoni trasporta più acqua dei successivi sette fiumi più grandi messi insieme. Come la mia pazienza, che trabocca pure lei.",
      "Islandia no tiene ejército permanente. Tampoco le hace falta contra ti.|Iceland has no standing army. It doesn't need one against you either.|L'Islande n'a pas d'armée permanente. Elle n'en a pas besoin contre toi non plus.|A Islândia não tem exército permanente. Também não precisa disso contra você.|Island hat kein stehendes Heer. Braucht es gegen dich auch nicht.|L'Islanda non ha un esercito permanente. Non ne avrebbe bisogno nemmeno contro di te.",
      "África tiene 54 países reconocidos. Y tú sin saber ni la mitad, seguro.|Africa has 54 recognized countries. And you probably don't know even half of them.|L'Afrique compte 54 pays reconnus. Et toi, tu n'en connais sûrement même pas la moitié.|A África tem 54 países reconhecidos. E você provavelmente não sabe nem a metade.|Afrika hat 54 anerkannte Länder. Und du kennst sicher nicht mal die Hälfte davon.|L'Africa ha 54 paesi riconosciuti. E tu di sicuro non ne conosci nemmeno la metà.",
      "La Antártida es técnicamente un desierto: el más seco del planeta. Como tus respuestas, secas de razón.|Antarctica is technically a desert: the driest on the planet. Like your answers, dry of any reason.|L'Antarctique est techniquement un désert : le plus sec de la planète. Comme tes réponses, sèches de tout bon sens.|A Antártida é tecnicamente um deserto: o mais seco do planeta. Igual suas respostas, secas de razão.|Die Antarktis ist technisch eine Wüste: die trockenste der Welt. Wie deine Antworten, trocken jeder Logik.|L'Antartide è tecnicamente un deserto: il più secco del pianeta. Come le tue risposte, prive di logica.",
      "Mónaco es el segundo país más pequeño del mundo, después del Vaticano. Cabe en tu ego, tranquilo.|Monaco is the second-smallest country in the world, after the Vatican. It fits inside your ego, don't worry.|Monaco est le deuxième plus petit pays du monde, après le Vatican. Il tient dans ton ego, ne t'inquiète pas.|Mônaco é o segundo menor país do mundo, depois do Vaticano. Cabe no seu ego, sem problema.|Monaco ist das zweitkleinste Land der Welt, nach dem Vatikan. Passt locker in dein Ego.|Monaco è il secondo paese più piccolo del mondo, dopo il Vaticano. Ci sta comodo nel tuo ego.",
      "La Gran Pirámide de Guiza fue la construcción más alta del mundo durante más de 3.800 años. Un récord más largo que tu racha de aciertos.|The Great Pyramid of Giza was the tallest structure on Earth for over 3,800 years. A record longer than your hit streak.|La grande pyramide de Gizeh fut la plus haute construction du monde pendant plus de 3 800 ans. Un record plus long que ta série de bons coups.|A Grande Pirâmide de Gizé foi a construção mais alta do mundo por mais de 3.800 anos. Um recorde mais longo que sua sequência de acertos.|Die Große Pyramide von Gizeh war über 3.800 Jahre lang das höchste Bauwerk der Welt. Ein Rekord, länger als deine Trefferserie.|La Grande Piramide di Giza fu la costruzione più alta del mondo per oltre 3.800 anni. Un record più lungo della tua striscia di successi.",
      "Japón tiene más de 6.800 islas. Y tú perdido en la primera.|Japan has over 6,800 islands. And you're lost on the very first one.|Le Japon compte plus de 6 800 îles. Et toi, perdu dès la première.|O Japão tem mais de 6.800 ilhas. E você perdido logo na primeira.|Japan hat über 6.800 Inseln. Und du verläufst dich schon auf der ersten.|Il Giappone ha oltre 6.800 isole. E tu ti perdi già sulla prima.",
      "Noruega comparte frontera terrestre con Rusia. Vecinos incómodos, como tú y la geografía.|Norway shares a land border with Russia. Awkward neighbors, like you and geography.|La Norvège partage une frontière terrestre avec la Russie. Des voisins gênants, comme toi et la géographie.|A Noruega faz fronteira terrestre com a Rússia. Vizinhos incômodos, tipo você e a geografia.|Norwegen teilt eine Landgrenze mit Russland. Unbequeme Nachbarn, wie du und die Geografie.|La Norvegia condivide un confine terrestre con la Russia. Vicini scomodi, come te e la geografia.",
      "El canal de Panamá conecta el Pacífico y el Atlántico en apenas 82 km. Menos distancia que la que te separa de acertar.|The Panama Canal connects the Pacific and Atlantic in just 82 km. Shorter than the distance between you and a correct guess.|Le canal de Panama relie le Pacifique et l'Atlantique en à peine 82 km. Moins que la distance qui te sépare d'une bonne réponse.|O canal do Panamá conecta o Pacífico e o Atlântico em apenas 82 km. Menos distância do que te separa de acertar.|Der Panamakanal verbindet Pazifik und Atlantik auf nur 82 km. Kürzer als die Distanz zwischen dir und einer richtigen Antwort.|Il canale di Panama collega il Pacifico e l'Atlantico in appena 82 km. Meno della distanza che ti separa da una risposta giusta.",
      "San Marino presume de ser el estado soberano más antiguo del mundo. Presume, como yo de tus fallos.|San Marino claims to be the oldest sovereign state in the world. It brags, like I do about your mistakes.|Saint-Marin prétend être le plus vieil État souverain du monde. Il s'en vante, comme moi de tes erreurs.|San Marino se gaba de ser o estado soberano mais antigo do mundo. Se gaba, como eu dos seus erros.|San Marino behauptet, der älteste souveräne Staat der Welt zu sein. Es prahlt, so wie ich mit deinen Fehlern.|San Marino si vanta di essere lo stato sovrano più antico del mondo. Si vanta, come me dei tuoi errori.",
      "Hace miles de años el Sáhara era verde y fértil. Ahora solo hay arena… y tus excusas.|Thousands of years ago the Sahara was green and fertile. Now there's only sand… and your excuses.|Il y a des milliers d'années, le Sahara était vert et fertile. Maintenant il n'y a que du sable… et tes excuses.|Há milhares de anos o Saara era verde e fértil. Agora só tem areia… e suas desculpas.|Vor Tausenden von Jahren war die Sahara grün und fruchtbar. Jetzt gibt es nur Sand… und deine Ausreden.|Migliaia di anni fa il Sahara era verde e fertile. Ora c'è solo sabbia… e le tue scuse.",
    ],
    homeReturn: [
      "Vaya, vaya… otra vez por aquí. Sabía que volverías.|Well, well… back again. I knew you would.|Eh bien, eh bien… de retour. Je savais que tu reviendrais.|Ora, ora… de volta de novo. Eu sabia que voltaria.|Na sowas… schon wieder hier. Ich wusste, du kommst zurück.|Toh, toh… di nuovo qui. Sapevo che saresti tornato.",
      "¿Segunda visita ya? Esto empieza a ser una costumbre tuya.|Second visit already? This is becoming a habit of yours.|Déjà une deuxième visite ? Ça devient une habitude chez toi.|Já a segunda visita? Isso está virando hábito seu.|Schon der zweite Besuch? Das wird ja zur Gewohnheit bei dir.|Già la seconda visita? Sta diventando un'abitudine per te.",
      "Te echaba de menos. Bueno, echaba de menos reírme de ti.|I missed you. Well, I missed laughing at you.|Tu m'as manqué. Enfin, rire de toi m'a manqué.|Senti sua falta. Bem, senti falta de rir de você.|Du hast mir gefehlt. Naja, mir fehlte, über dich zu lachen.|Mi sei mancato. Beh, mi mancava ridere di te.",
      "¿Otra vez tú? La mesa ya casi reconoce tus pasos.|You again? The table can almost recognize your footsteps.|Encore toi ? La table reconnaît presque tes pas.|Você de novo? A mesa quase já reconhece seus passos.|Schon wieder du? Der Tisch erkennt fast deine Schritte.|Ancora tu? Il tavolo riconosce quasi i tuoi passi.",
      "Volviste. No sé si felicitarte o preocuparme por ti.|You came back. Not sure whether to congratulate you or worry about you.|Tu es revenu. Je ne sais pas si je dois te féliciter ou m'inquiéter.|Você voltou. Não sei se te parabenizo ou me preocupo com você.|Du bist zurück. Ich weiß nicht, ob ich dich beglückwünschen oder mir Sorgen machen soll.|Sei tornato. Non so se farti i complimenti o preoccuparmi per te.",
      "Cuántas veces ya… y sigues sin aprenderte un mapa. Admirable, en cierto modo.|So many times already… and still can't learn a map. Admirable, in a way.|Tant de fois déjà… et toujours incapable d'apprendre une carte. Admirable, à sa façon.|Tantas vezes já… e ainda não decorou um mapa. Admirável, à sua maneira.|Schon so oft… und immer noch keine Karte gelernt. Auf gewisse Weise bewundernswert.|Già tante volte… e ancora non impari una mappa. Ammirevole, a modo suo.",
      "La mesa se acuerda de ti. Yo también, por desgracia.|The table remembers you. So do I, unfortunately.|La table se souvient de toi. Moi aussi, malheureusement.|A mesa se lembra de você. Eu também, infelizmente.|Der Tisch erinnert sich an dich. Ich leider auch.|Il tavolo si ricorda di te. Anch'io, purtroppo.",
      "¿Ya de vuelta? Ni que tuvieras algo mejor que hacer.|Back already? As if you had anything better to do.|Déjà de retour ? Comme si tu avais mieux à faire.|Já de volta? Como se tivesse algo melhor pra fazer.|Schon wieder da? Als hättest du nichts Besseres zu tun.|Già di ritorno? Come se avessi di meglio da fare.",
      "Cada vez que vuelves, mi sonrisa se hace un poco más malvada.|Every time you come back, my smile gets a little more evil.|Chaque fois que tu reviens, mon sourire devient un peu plus malveillant.|Cada vez que você volta, meu sorriso fica um pouco mais maligno.|Jedes Mal, wenn du zurückkommst, wird mein Lächeln ein bisschen böser.|Ogni volta che torni, il mio sorriso diventa un po' più malvagio.",
      "Mira quién ha vuelto a pedir más castigo.|Look who came back for more punishment.|Regarde qui revient chercher une autre raclée.|Olha quem voltou pedindo mais castigo.|Sieh mal einer an, wer für mehr Strafe zurückkommt.|Guarda chi è tornato a chiedere altre punizioni.",
    ],
    homeTimeMorning: [
      "Buenos días. O buenas… lo que sea que sea esto tan temprano.|Good morning. Or whatever this early hour is supposed to be.|Bonjour. Ou peu importe ce que c'est, si tôt.|Bom dia. Ou seja lá o que for, tão cedo assim.|Guten Morgen. Oder was auch immer das zu dieser frühen Stunde sein soll.|Buongiorno. O quel che è, così presto.",
      "¿Café antes o después de perder? Yo recomiendo antes.|Coffee before or after losing? I recommend before.|Café avant ou après avoir perdu ? Je recommande avant.|Café antes ou depois de perder? Eu recomendo antes.|Kaffee vor oder nach der Niederlage? Ich empfehle vorher.|Caffè prima o dopo aver perso? Consiglio prima.",
      "Madrugar para venir a perder conmigo. Qué dedicación.|Getting up early just to lose to me. Such dedication.|Se lever tôt juste pour perdre contre moi. Quelle dévotion.|Acordar cedo só para perder para mim. Que dedicação.|Früh aufstehen, nur um gegen mich zu verlieren. Was für eine Hingabe.|Svegliarsi presto solo per perdere contro di me. Che dedizione.",
      "El día apenas empieza y ya te estoy tomando el pelo. Buen ritmo.|The day's barely started and I'm already teasing you. Good pace.|La journée commence à peine et je me moque déjà de toi. Bon rythme.|O dia mal começou e eu já estou zoando você. Bom ritmo.|Der Tag fängt gerade erst an und ich mache mich schon über dich lustig. Gutes Tempo.|La giornata è appena iniziata e già ti prendo in giro. Bel ritmo.",
      "Los madrugadores del mundo… y tú, aquí, perdiendo geografía.|Early birds of the world… and you, here, losing at geography.|Les lève-tôt du monde… et toi, ici, en train de perdre en géographie.|Os madrugadores do mundo… e você, aqui, perdendo em geografia.|Die Frühaufsteher dieser Welt… und du hier, verlierst in Geografie.|I mattinieri del mondo… e tu qui, a perdere in geografia.",
      "Buenos días. Espero que tu suerte se haya despertado también.|Good morning. Hope your luck woke up too.|Bonjour. J'espère que ta chance s'est réveillée aussi.|Bom dia. Espero que sua sorte também tenha acordado.|Guten Morgen. Hoffentlich ist dein Glück auch aufgewacht.|Buongiorno. Spero che anche la tua fortuna si sia svegliata.",
    ],
    homeTimeAfternoon: [
      "Buenas tardes. Justo a tiempo para que te tome el pelo un rato.|Good afternoon. Just in time for me to tease you a bit.|Bon après-midi. Juste à temps pour que je me moque un peu de toi.|Boa tarde. Bem a tempo de eu zoar você um pouco.|Guten Nachmittag. Genau rechtzeitig, damit ich dich ein wenig aufziehe.|Buon pomeriggio. Giusto in tempo per prenderti un po' in giro.",
      "¿Descanso de la comida o escapando del trabajo? No juzgo. Bueno, sí.|Lunch break or hiding from work? No judgment. Okay, some judgment.|Pause déjeuner ou fuite du travail ? Aucun jugement. Bon, un peu.|Pausa do almoço ou fugindo do trabalho? Sem julgamento. Tá, com um pouco.|Mittagspause oder Flucht vor der Arbeit? Kein Urteil. Na gut, ein bisschen.|Pausa pranzo o fuga dal lavoro? Nessun giudizio. Va bene, un po'.",
      "La tarde es perfecta para perder tiempo. Y para perder, en general.|Afternoons are perfect for wasting time. And for losing, in general.|L'après-midi est parfait pour perdre du temps. Et pour perdre, en général.|A tarde é perfeita para perder tempo. E para perder, em geral.|Der Nachmittag ist perfekt, um Zeit zu vergeuden. Und um generell zu verlieren.|Il pomeriggio è perfetto per perdere tempo. E per perdere, in generale.",
      "Sol fuera, tú aquí dentro perdiéndote en un mapa. Prioridades.|Sun outside, you in here getting lost on a map. Priorities.|Soleil dehors, toi ici en train de te perdre sur une carte. Priorités.|Sol lá fora, você aqui se perdendo num mapa. Prioridades.|Sonne draußen, du hier drinnen, verloren auf einer Karte. Prioritäten.|Sole fuori, tu qui dentro a perderti su una mappa. Priorità.",
      "Buenas tardes. La mesa lleva calentita desde esta mañana, por si acaso.|Good afternoon. The table's been warm since this morning, just so you know.|Bon après-midi. La table est chaude depuis ce matin, au cas où.|Boa tarde. A mesa está quentinha desde de manhã, só pra avisar.|Guten Nachmittag. Der Tisch ist seit heute Morgen warm, nur damit du's weißt.|Buon pomeriggio. Il tavolo è caldo da stamattina, giusto per saperlo.",
      "Media tarde, energía media, resultados… ya veremos.|Mid-afternoon, mid-energy, results… we'll see.|Milieu d'après-midi, énergie moyenne, résultats… on verra.|Meio da tarde, energia mediana, resultados… vamos ver.|Mitten am Nachmittag, mittlere Energie, Ergebnisse… mal sehen.|Metà pomeriggio, energia media, risultati… si vedrà.",
    ],
    homeTimeEvening: [
      "Buenas noches. La mesa se pone más interesante cuando anochece.|Good evening. The table gets more interesting once night falls.|Bonsoir. La table devient plus intéressante à la tombée de la nuit.|Boa noite. A mesa fica mais interessante quando escurece.|Guten Abend. Der Tisch wird interessanter, wenn es dunkel wird.|Buonasera. Il tavolo diventa più interessante quando cala la notte.",
      "¿Terminaste el día y esto es tu premio? Vaya premio te has buscado.|Done with the day and this is your reward? Some reward you picked.|Journée terminée et voilà ta récompense ? Belle récompense, tiens.|Terminou o dia e esse é seu prêmio? Belo prêmio você escolheu.|Tag vorbei und das ist deine Belohnung? Was für eine Belohnung.|Finita la giornata ed ecco il tuo premio? Bel premio ti sei scelto.",
      "Al anochecer, todos los mapas se ven igual de confusos. Al menos para ti.|At dusk, every map looks equally confusing. At least to you.|Au crépuscule, toutes les cartes semblent aussi confuses. Pour toi, en tout cas.|Ao anoitecer, todos os mapas parecem igualmente confusos. Pelo menos pra você.|In der Abenddämmerung sehen alle Karten gleich verwirrend aus. Zumindest für dich.|Al tramonto, tutte le mappe sembrano ugualmente confuse. Almeno per te.",
      "Buenas noches. Las luces del casino se encienden… y tu suerte, no tanto.|Good evening. The casino lights turn on… your luck, not so much.|Bonsoir. Les lumières du casino s'allument… ta chance, pas tellement.|Boa noite. As luzes do cassino se acendem… sua sorte, nem tanto.|Guten Abend. Die Lichter des Casinos gehen an… dein Glück eher nicht.|Buonasera. Le luci del casinò si accendono… la tua fortuna, meno.",
      "La tarde-noche es mi horario favorito para verte fallar con estilo.|Early evening is my favorite time to watch you fail with style.|La soirée est mon moment préféré pour te voir échouer avec style.|O fim de tarde é meu horário favorito para ver você falhar com estilo.|Der frühe Abend ist meine Lieblingszeit, dich stilvoll scheitern zu sehen.|La sera è il mio momento preferito per vederti fallire con stile.",
      "Buenas noches, explorador nocturno. La mesa te esperaba.|Good evening, night-time explorer. The table's been waiting.|Bonsoir, explorateur nocturne. La table t'attendait.|Boa noite, explorador noturno. A mesa esperava por você.|Guten Abend, nächtlicher Entdecker. Der Tisch hat gewartet.|Buonasera, esploratore notturno. Il tavolo ti aspettava.",
    ],
    homeTimeNight: [
      "¿Jugando a estas horas? No juzgo… bueno, un poco sí.|Playing at this hour? No judgment… okay, a little.|Jouer à cette heure ? Aucun jugement… bon, un peu.|Jogando a essa hora? Sem julgamento… tá, um pouquinho.|Zu dieser Stunde spielen? Kein Urteil… na gut, ein bisschen.|Giocare a quest'ora? Nessun giudizio… okay, un po'.",
      "Es tardísimo. O tempranísimo. Depende de si has dormido ya.|It's really late. Or really early. Depends if you've slept yet.|Il est très tard. Ou très tôt. Ça dépend si tu as déjà dormi.|Está muito tarde. Ou muito cedo. Depende se você já dormiu.|Es ist sehr spät. Oder sehr früh. Kommt drauf an, ob du schon geschlafen hast.|È tardissimo. O prestissimo. Dipende se hai già dormito.",
      "El resto del mundo duerme. Tú, aquí, con un croupier malvado. Buena elección.|The rest of the world sleeps. You, here, with an evil dealer. Great choice.|Le reste du monde dort. Toi, ici, avec un croupier malveillant. Excellent choix.|O resto do mundo dorme. Você, aqui, com um crupiê maligno. Ótima escolha.|Der Rest der Welt schläft. Du hier mit einem bösen Croupier. Gute Wahl.|Il resto del mondo dorme. Tu, qui, con un croupier malvagio. Ottima scelta.",
      "De madrugada todos los mapas parecen del revés. Los tuyos, siempre.|Late at night every map looks upside down. Yours, always.|Tard dans la nuit, toutes les cartes semblent à l'envers. Les tiennes, toujours.|De madrugada todos os mapas parecem de cabeça para baixo. Os seus, sempre.|Spätnachts sieht jede Karte auf dem Kopf aus. Deine, immer.|A notte fonda ogni mappa sembra capovolta. La tua, sempre.",
      "Vaya horas para venir a que te tome el pelo. Me parece perfecto.|Quite the hour to come get teased by me. Perfect, honestly.|Sacrée heure pour venir te faire charrier par moi. Parfait, franchement.|Que horário para vir apanhar da minha zoeira. Perfeito, sinceramente.|Zu einer solchen Uhrzeit dich von mir aufziehen zu lassen. Perfekt, ehrlich.|Che orario per venire a farti prendere in giro da me. Perfetto, sinceramente.",
      "¿Insomnio o simplemente no puedes dejar de perder conmigo?|Insomnia, or can you just not stop losing to me?|Insomnie, ou tu ne peux juste pas arrêter de perdre contre moi ?|Insônia, ou você simplesmente não consegue parar de perder pra mim?|Schlaflosigkeit, oder kannst du einfach nicht aufhören, gegen mich zu verlieren?|Insonnia, o semplicemente non riesci a smettere di perdere con me?",
      "A estas horas hasta yo debería estar durmiendo. Pero aquí estamos los dos.|At this hour even I should be asleep. Yet here we both are.|À cette heure, même moi je devrais dormir. Et pourtant, nous voilà tous les deux.|A essa hora até eu deveria estar dormindo. Mas aqui estamos nós dois.|Zu dieser Stunde sollte sogar ich schlafen. Und doch sind wir beide hier.|A quest'ora dovrei dormire pure io. Eppure eccoci qui, entrambi.",
      "Última partida antes de dormir, ¿verdad? Ja. Nunca es la última.|Last game before bed, right? Ha. It's never the last one.|Dernière partie avant de dormir, hein ? Ha. Ce n'est jamais la dernière.|Última partida antes de dormir, né? Ha. Nunca é a última.|Letzte Runde vorm Schlafen, oder? Ha. Es ist nie die letzte.|Ultima partita prima di dormire, vero? Ah. Non è mai l'ultima.",
    ],
    homeTimeWeekend: [
      "Fin de semana, ¿eh? Tiempo libre para perder conmigo con calma.|Weekend, huh? Free time to lose to me at a relaxed pace.|Week-end, hein ? Du temps libre pour perdre contre moi tranquillement.|Fim de semana, né? Tempo livre para perder pra mim com calma.|Wochenende, was? Freizeit, um in Ruhe gegen mich zu verlieren.|Weekend, eh? Tempo libero per perdere con me con calma.",
      "Sin trabajo, sin excusas. Solo tú, yo y un mapa que no perdona.|No work, no excuses. Just you, me, and a map that shows no mercy.|Pas de travail, pas d'excuses. Juste toi, moi et une carte impitoyable.|Sem trabalho, sem desculpas. Só você, eu e um mapa sem piedade.|Keine Arbeit, keine Ausreden. Nur du, ich und eine gnadenlose Karte.|Niente lavoro, niente scuse. Solo tu, io e una mappa spietata.",
      "Fin de semana libre para el mundo… y para mis burlas también.|Weekend off for the world… and for my teasing too.|Week-end libre pour le monde… et pour mes moqueries aussi.|Fim de semana livre para o mundo… e para minhas zoeiras também.|Wochenende frei für die Welt… und auch für meine Sticheleien.|Weekend libero per il mondo… e anche per le mie prese in giro.",
      "¿Plan de sábado? Perder conmigo. No hay mucho más que elegir.|Saturday plans? Losing to me. Not much else to choose from.|Plan du samedi ? Perdre contre moi. Pas beaucoup d'autres choix.|Plano de sábado? Perder pra mim. Não tem muita escolha.|Samstagsplan? Gegen mich verlieren. Viel Auswahl gibt's nicht.|Programma del sabato? Perdere con me. Non c'è molta scelta.",
      "Domingo… el día perfecto para fingir que vas a estudiar geografía en serio.|Sunday… the perfect day to pretend you'll seriously study geography.|Dimanche… le jour parfait pour faire semblant d'étudier la géo sérieusement.|Domingo… o dia perfeito para fingir que vai estudar geografia a sério.|Sonntag… der perfekte Tag, um so zu tun, als würdest du ernsthaft Geografie lernen.|Domenica… il giorno perfetto per fingere di studiare geografia sul serio.",
      "Fin de semana en el casino. Aquí no hay lunes, solo revanchas.|Weekend at the casino. No Mondays here, only rematches.|Week-end au casino. Ici, pas de lundi, juste des revanches.|Fim de semana no cassino. Aqui não tem segunda-feira, só revanches.|Wochenende im Casino. Hier gibt's keinen Montag, nur Revanchen.|Weekend al casinò. Qui non c'è lunedì, solo rivincite.",
    ],
    homeMeta: [
      "Sé que me estás leyendo ahora mismo. Hola.|I know you're reading this right now. Hi.|Je sais que tu me lis en ce moment même. Salut.|Sei que você está me lendo agora mesmo. Oi.|Ich weiß, dass du das gerade liest. Hallo.|So che mi stai leggendo proprio ora. Ciao.",
      "Esta frase la eligió el azar. O yo. Nunca lo sabrás con certeza.|This line was picked at random. Or by me. You'll never know for sure.|Cette phrase a été choisie au hasard. Ou par moi. Tu ne sauras jamais vraiment.|Essa frase foi escolhida ao acaso. Ou por mim. Você nunca vai ter certeza.|Diese Zeile wurde zufällig ausgewählt. Oder von mir. Du wirst es nie sicher wissen.|Questa battuta è stata scelta a caso. O da me. Non lo saprai mai con certezza.",
      "Existo dentro de una pantalla y aun así te gano. Piénsalo bien.|I exist inside a screen and I still beat you. Think about that.|J'existe dans un écran et je te bats quand même. Réfléchis-y.|Eu existo dentro de uma tela e ainda assim te venço. Pense nisso.|Ich existiere in einem Bildschirm und schlage dich trotzdem. Denk mal drüber nach.|Esisto dentro uno schermo e ti batto comunque. Pensaci su.",
      "¿Crees que esto es aleatorio? Yo tampoco lo sé del todo, mejor no preguntes.|Think this is random? Honestly, even I'm not sure. Better not ask.|Tu crois que c'est aléatoire ? Honnêtement, même moi je ne suis pas sûr. Mieux vaut ne pas demander.|Acha que isso é aleatório? Sinceramente, nem eu tenho certeza. Melhor não perguntar.|Denkst du, das ist Zufall? Ehrlich gesagt, bin ich mir selbst nicht sicher. Frag lieber nicht.|Pensi che sia casuale? Sinceramente nemmeno io ne sono sicuro. Meglio non chiedere.",
      "Alguien programó todas estas frases mías. Espero que le pagaran bien.|Someone programmed all these lines of mine. Hope they got paid well.|Quelqu'un a programmé toutes mes répliques. J'espère qu'il a été bien payé.|Alguém programou todas essas minhas falas. Espero que tenha sido bem pago.|Jemand hat all diese Sätze von mir programmiert. Hoffentlich wurde er gut bezahlt.|Qualcuno ha programmato tutte queste mie battute. Spero sia stato pagato bene.",
      "No estoy mirándote a través de la pantalla. Probablemente.|I'm not watching you through the screen. Probably.|Je ne te regarde pas à travers l'écran. Probablement.|Eu não estou olhando você através da tela. Provavelmente.|Ich beobachte dich nicht durch den Bildschirm. Wahrscheinlich.|Non ti sto guardando attraverso lo schermo. Probabilmente.",
      "Esta mesa existe aunque cierres la pestaña. Bueno, tal vez no. Compruébalo.|This table exists even if you close the tab. Well, maybe not. Test it.|Cette table existe même si tu fermes l'onglet. Enfin, peut-être pas. Vérifie.|Esta mesa existe mesmo que você feche a aba. Bem, talvez não. Teste aí.|Dieser Tisch existiert, auch wenn du den Tab schließt. Nun ja, vielleicht auch nicht. Probier's aus.|Questo tavolo esiste anche se chiudi la scheda. Beh, forse no. Provaci.",
      "Puedo repetirme… si dejas de jugar el tiempo suficiente. Así que sigue jugando.|I might repeat myself… if you stop playing long enough. So keep playing.|Je pourrais me répéter… si tu arrêtes de jouer assez longtemps. Alors continue.|Posso me repetir… se você parar de jogar tempo suficiente. Então continue jogando.|Ich könnte mich wiederholen… wenn du lange genug pausierst. Also spiel weiter.|Potrei ripetermi… se smetti di giocare abbastanza a lungo. Quindi continua a giocare.",
      "Tengo cientos de frases guardadas. Tú tienes cero excusas para no jugar.|I've got hundreds of lines saved up. You've got zero excuses not to play.|J'ai des centaines de répliques en réserve. Toi, zéro excuse pour ne pas jouer.|Tenho centenas de falas guardadas. Você tem zero desculpas para não jogar.|Ich habe Hunderte Sätze auf Lager. Du hast null Ausreden, nicht zu spielen.|Ho centinaia di battute in serbo. Tu hai zero scuse per non giocare.",
      "No soy real. Pero mis burlas sí que te duelen, ¿a que sí?|I'm not real. But my teasing still stings, doesn't it?|Je ne suis pas réel. Mais mes moqueries te piquent quand même, non ?|Eu não sou real. Mas minhas zoeiras ainda doem, né?|Ich bin nicht echt. Aber meine Sticheleien tun trotzdem weh, oder?|Non sono reale. Ma le mie prese in giro fanno comunque male, vero?",
      "Detrás de cada frase mía hay una lista larguísima… y tú aún no la has vaciado.|Behind every line of mine is a very long list… and you haven't emptied it yet.|Derrière chacune de mes phrases se cache une très longue liste… que tu n'as pas encore vidée.|Por trás de cada fala minha existe uma lista enorme… que você ainda não esvaziou.|Hinter jedem meiner Sätze steckt eine sehr lange Liste… die du noch nicht geleert hast.|Dietro ogni mia battuta c'è una lista lunghissima… che non hai ancora svuotato.",
      "Si me lees en voz alta, técnicamente estás hablando conmigo. Piénsalo.|If you read me out loud, you're technically talking to me. Think about it.|Si tu me lis à voix haute, techniquement, tu me parles. Réfléchis-y.|Se você me ler em voz alta, tecnicamente está falando comigo. Pense nisso.|Wenn du mich laut vorliest, sprichst du technisch gesehen mit mir. Denk drüber nach.|Se mi leggi ad alta voce, tecnicamente stai parlando con me. Pensaci.",
    ],
    runIdle: [
      "¿Perdido en el mapa o solo de paseo?|Lost on the map, or just wandering?|Perdu sur la carte, ou juste en balade ?|Perdido no mapa ou só passeando?|Verloren auf der Karte, oder schlenderst du nur?|Perso sulla mappa, o stai solo passeggiando?",
      "Ese doblón no se va a gastar solo, ¿sabes?|That doubloon isn't going to spend itself, you know.|Ce doublon ne va pas se dépenser tout seul, tu sais.|Esse dobrão não vai se gastar sozinho, sabia?|Diese Dublone gibt sich nicht von selbst aus, weißt du.|Quel dobloni non si spenderà da solo, sai?",
      "Tómate tu tiempo. El reloj no. Pero tú sí.|Take your time. The clock won't. But you will.|Prends ton temps. L'horloge, non. Mais toi, oui.|Fique à vontade. O relógio, não. Mas você, sim.|Lass dir Zeit. Die Uhr nicht. Aber du schon.|Prenditi il tuo tempo. L'orologio no. Ma tu sì.",
      "El mapa no cambia de sitio solo porque lo mires fijamente.|The map doesn't move just because you stare at it.|La carte ne bouge pas juste parce que tu la fixes.|O mapa não muda de lugar só porque você fica encarando.|Die Karte bewegt sich nicht, nur weil du sie anstarrst.|La mappa non si sposta solo perché la fissi.",
      "¿Cuántas rondas llevas ya? Yo he perdido la cuenta. De tus aciertos.|How many rounds in already? I've lost count. Of your hits.|Combien de manches déjà ? J'ai perdu le compte. De tes réussites.|Quantas rodadas já? Eu perdi a conta. Dos seus acertos.|Wie viele Runden schon? Ich hab die Übersicht verloren. Über deine Treffer.|Quante manche già? Ho perso il conto. Dei tuoi successi.",
      "Ese acto es solo el principio… o el final, según cómo te vaya.|This act is only the beginning… or the end, depending how you're doing.|Cet acte n'est que le début… ou la fin, selon comment ça se passe.|Esse ato é só o começo… ou o fim, dependendo de como você vai.|Dieser Akt ist erst der Anfang… oder das Ende, je nachdem, wie's läuft.|Questo atto è solo l'inizio… o la fine, a seconda di come va.",
      "Silencio en la mesa. Sospechoso. Muy sospechoso.|Quiet at the table. Suspicious. Very suspicious.|Silence à la table. Suspect. Très suspect.|Silêncio na mesa. Suspeito. Muito suspeito.|Stille am Tisch. Verdächtig. Sehr verdächtig.|Silenzio al tavolo. Sospetto. Molto sospetto.",
      "¿Repasando el mapa mentalmente? Buena suerte con eso.|Reviewing the map in your head? Good luck with that.|Tu révises la carte dans ta tête ? Bonne chance avec ça.|Revisando o mapa de cabeça? Boa sorte com isso.|Gehst du die Karte im Kopf durch? Viel Glück damit.|Ripassi la mappa a memoria? Buona fortuna.",
      "Provisiones, doblones, tiempo… y tu paciencia. Todo se agota.|Provisions, doubloons, time… and your patience. It all runs out.|Provisions, doublons, temps… et ta patience. Tout s'épuise.|Provisões, dobrões, tempo… e sua paciência. Tudo acaba.|Proviant, Dublonen, Zeit… und deine Geduld. Alles geht zur Neige.|Provviste, dobloni, tempo… e la tua pazienza. Tutto finisce.",
      "¿Ya sabes dónde vas a clicar o estás improvisando como siempre?|Already know where you'll click, or improvising as usual?|Tu sais déjà où tu vas cliquer, ou tu improvises comme d'habitude ?|Já sabe onde vai clicar ou está improvisando como sempre?|Weißt du schon, wo du klickst, oder improvisierst du wie immer?|Sai già dove cliccherai o improvvisi come al solito?",
      "Este mapa ha visto a mejores jugadores que tú. Y a peores. Tranquilo.|This map has seen better players than you. And worse. Relax.|Cette carte a vu de meilleurs joueurs que toi. Et de pires. Détends-toi.|Este mapa já viu jogadores melhores que você. E piores. Relaxa.|Diese Karte hat bessere Spieler gesehen als dich. Und schlechtere. Entspann dich.|Questa mappa ha visto giocatori migliori di te. E peggiori. Rilassati.",
      "Cada segundo que dudas, yo sonrío un poquito más.|Every second you hesitate, I smile a little more.|Chaque seconde d'hésitation, je souris un peu plus.|Cada segundo que você hesita, eu sorrio um pouquinho mais.|Jede Sekunde, die du zögerst, lächle ich ein bisschen mehr.|Ogni secondo che esiti, sorrido un po' di più.",
      "El mundo es grande. Tus aciertos, no tanto.|The world is big. Your hits, not so much.|Le monde est grand. Tes réussites, moins.|O mundo é grande. Seus acertos, nem tanto.|Die Welt ist groß. Deine Treffer eher nicht.|Il mondo è grande. I tuoi successi, meno.",
      "Piensa rápido, apunta despacio. O al revés. Tú decides tu propio desastre.|Think fast, aim slow. Or the other way. Your disaster to choose.|Réfléchis vite, vise lentement. Ou l'inverse. Ton désastre, ton choix.|Pense rápido, mire devagar. Ou o contrário. O desastre é seu, escolha.|Denk schnell, ziel langsam. Oder umgekehrt. Dein Desaster, deine Wahl.|Pensa in fretta, mira piano. O il contrario. Il disastro è tuo, scegli.",
    ],

    /* ---------------------------------------------------------------- rabieta del crupier: te gana la ronda y la paga con la pantalla */
    tantrumShake: [
      "¡¿Que tú me ganas?! Voy a hacer temblar hasta la pantalla.|YOU beat ME?! I'm making the whole screen shake.|Toi, tu me bats ?! Je vais faire trembler l'écran entier.|VOCÊ me vence?! Vou fazer a tela inteira tremer.|DU schlägst MICH?! Ich lasse gleich den ganzen Bildschirm beben.|TU mi batti?! Faccio tremare tutto lo schermo.",
      "No pataleo… bueno, sí. Toda la sala tiembla conmigo.|I'm not throwing a tantrum… okay, I am. The whole room shakes with me.|Je ne fais pas de caprice… bon, si. Toute la salle tremble avec moi.|Não estou fazendo birra… tá, estou. A sala toda treme comigo.|Ich habe keinen Wutanfall… na gut, doch. Der ganze Saal bebt mit mir.|Non sto facendo i capricci… va bene, sì. Tutta la sala trema con me.",
      "Esto no es un terremoto. Es mi orgullo cayéndose a pedazos.|This isn't an earthquake. It's my pride falling apart.|Ce n'est pas un séisme. C'est ma fierté qui s'effondre.|Isso não é um terremoto. É o meu orgulho desmoronando.|Das ist kein Erdbeben. Das ist mein Stolz, der zerbricht.|Questo non è un terremoto. È il mio orgoglio che va in pezzi.",
      "¿Sientes eso? Es mi mal humor sacudiendo tu pantalla.|Feel that? That's my bad mood shaking your screen.|Tu sens ça ? C'est ma mauvaise humeur qui secoue ton écran.|Sentiu isso? É meu mau humor sacudindo sua tela.|Spürst du das? Das ist meine schlechte Laune, die deinen Bildschirm rüttelt.|Lo senti? È il mio malumore che scuote il tuo schermo.",
      "Un poco de terremoto no le hace daño a nadie. A ti, un poco sí.|A little earthquake never hurt anybody. You, maybe a little.|Un petit séisme n'a jamais fait de mal à personne. À toi, un peu quand même.|Um terremotozinho não faz mal a ninguém. A você, um pouquinho sim.|Ein kleines Erdbeben hat noch niemandem geschadet. Dir vielleicht ein bisschen.|Un piccolo terremoto non ha mai fatto male a nessuno. A te, un po' sì.",
      "Tranquilo: cuando pierdo, tiemblo yo… y tu pantalla también.|Relax: when I lose, I shake… and so does your screen.|Détends-toi : quand je perds, je tremble… et ton écran aussi.|Relaxa: quando eu perco, eu tremo… e sua tela também.|Entspann dich: wenn ich verliere, zittere ich… und dein Bildschirm auch.|Tranquillo: quando perdo, tremo io… e anche il tuo schermo.",
    ],
    tantrumBlackout: [
      "¿Se ha ido la luz? Qué casualidad, justo cuando ganas.|Did the lights just go out? What a coincidence, right when you win.|La lumière vient de s'éteindre ? Quelle coïncidence, juste quand tu gagnes.|A luz caiu? Que coincidência, bem na hora que você ganha.|Ist gerade das Licht ausgegangen? Was für ein Zufall, genau als du gewinnst.|È andata via la luce? Che coincidenza, proprio quando vinci.",
      "Un cortocircuito muy oportuno. No tiene nada que ver conmigo.|A very convenient short circuit. Nothing to do with me.|Un court-circuit bien pratique. Ça n'a rien à voir avec moi.|Um curto-circuito bem oportuno. Não tem nada a ver comigo.|Ein sehr passender Kurzschluss. Hat nichts mit mir zu tun.|Un cortocircuito molto opportuno. Non c'entro niente.",
      "A oscuras se me disimula mejor la cara de fastidio. Ya vuelvo.|In the dark my annoyed face is easier to hide. Be right back.|Dans le noir, ma tête dépitée se voit moins. Je reviens.|No escuro minha cara de irritado se disfarça melhor. Já volto.|Im Dunkeln versteckt sich mein genervtes Gesicht besser. Bin gleich zurück.|Al buio la mia faccia scocciata si nota meno. Torno subito.",
      "Apago las luces un segundo. Así no ves mi cara ahora mismo.|Turning off the lights for a second. So you don't see my face right now.|J'éteins les lumières une seconde. Comme ça tu ne vois pas ma tête maintenant.|Vou apagar as luzes um segundo. Assim você não vê minha cara agora.|Ich mache kurz das Licht aus. Damit du mein Gesicht jetzt nicht siehst.|Spengo le luci un secondo. Così non vedi la mia faccia adesso.",
      "El casino se queda a oscuras. Yo sigo aquí. Siempre aquí.|The casino goes dark. I'm still here. Always here.|Le casino plonge dans le noir. Je suis toujours là. Toujours.|O cassino fica no escuro. Eu continuo aqui. Sempre aqui.|Das Casino wird dunkel. Ich bin immer noch da. Immer da.|Il casinò resta al buio. Io sono sempre qui. Sempre.",
      "Un pequeño apagón de rabia. Nada personal. Bueno, un poco sí.|A little blackout of rage. Nothing personal. Okay, a little.|Une petite panne de rage. Rien de personnel. Bon, un peu quand même.|Um pequeno apagão de raiva. Nada pessoal. Tá, um pouquinho sim.|Ein kleiner Wutausbruch als Stromausfall. Nichts Persönliches. Na gut, ein bisschen.|Un piccolo blackout di rabbia. Niente di personale. Va bene, un po' sì.",
    ],
  };
  for (const k in LINES) LINES[k] = LINES[k].map(L6);

  const D = A.dealer = { on: false, onHome: false, host: null, timers: [], busy: false };
  let el, face, bubble, txt;
  const rand = a => a[Math.floor(Math.random() * a.length)];

  function ensure() {
    if (el && el.isConnected) return;
    el = document.createElement("div"); el.id = "dealer"; el.className = "dealer";
    el.innerHTML = `<div class="dl-bubble"><p></p></div><img class="dl-face" alt="" src="assets/icons/dealer_neutral.webp">`;
    $("app").appendChild(el); face = el.querySelector(".dl-face"); bubble = el.querySelector(".dl-bubble"); txt = bubble.querySelector("p");
  }
  const clear = () => { D.timers.forEach(clearTimeout); D.timers = []; };
  const later = (fn, ms) => { const t = setTimeout(fn, ms); D.timers.push(t); return t; };

  /* dice una frase con voz arcade y maquina de escribir */
  D.say = (line, o = {}) => {
    if (!D.on && !D.onHome) return; ensure(); clear();
    const mood = o.mood || "sly", text = typeof line === "string" ? line : A.tx(line), src = FACE[mood] || "dealer_neutral";
    face.src = `assets/icons/${src}.webp`; el.className = "dealer in " + mood + (D.host ? " big" : "") + (el.closest("#vdDealer") ? " inline" : ""); txt.textContent = ""; bubble.classList.add("on");
    if (mood === "laugh") A.sfx.laugh && A.sfx.laugh();
    let i = 0; const chars = [...text], step = mood === "laugh" ? 44 : 34;
    const tick = () => {
      if (i >= chars.length) { el.classList.add("done"); if (o.hold !== 0) later(() => D.hide(), o.hold || 1800 + text.length * 22); if (o.done) o.done(); return; }
      txt.textContent += chars[i]; if (/\S/.test(chars[i]) && i % 2 === 0 && mood !== "laugh") A.sfx.voice && A.sfx.voice(mood, i); i++; later(tick, step + (/[.,!?…]/.test(chars[i - 1]) ? 140 : 0));
    };
    tick(); D.busy = true;
  };
  D.hide = () => { if (!el) return; el.classList.remove("in", "done", "laugh", "angry", "shock", "sly", "boss"); bubble.classList.remove("on"); D.busy = false; };
  D.enable = on => {
    D.on = !!on; clearTimeout(runT);
    if (!on) { clear(); D.dock(null); if (el) el.classList.add("hidden"); }
    else { ensure(); el.classList.remove("hidden"); runT = setTimeout(runTick, 18000 + Math.random() * 14000); }
  };
  /* pasa el retrato a un contenedor grande (pantalla de intro) o lo devuelve a la esquina */
  D.dock = host => { ensure(); D.host = host || null; if (host) host.appendChild(el); else $("app").appendChild(el); el.classList.toggle("big", !!host); };
  /* lo coloca dentro de un hueco de la pantalla (veredicto) sin bloquear sus reacciones */
  D.anchor = host => { if (!host) return; ensure(); host.appendChild(el); el.classList.add("inline"); };
  /* secuencia de frases: [{line, mood}] */
  D.sequence = (items, done) => { let k = 0; const next = () => { if (k >= items.length) return done && done(); const it = items[k++]; D.say(it.line, { mood: it.mood, hold: 0, done: () => later(next, it.gap || 700) }); }; next(); };
  D.line = (key, i) => { const a = LINES[key]; return a ? (i == null ? rand(a) : a[i % a.length]) : null; };
  D.lines = LINES;
  D._pick = key => pickLine(key);   // solo para pruebas de desarrollo (dev/*.js): saca una frase de la bolsa sin repetir

  /* ---------------------------------------------------------------- memoria persistente: visitas y "bolsas" para no repetir frase hasta agotar la categoria (ni entre sesiones) */
  const SKEY = "atlasiq.dealer.v1";
  const loadStore = () => { try { const d = JSON.parse(localStorage.getItem(SKEY) || "null"); return Object.assign({ visits: 0, lastSeen: 0, bags: {} }, d || {}); } catch (e) { return { visits: 0, lastSeen: 0, bags: {} }; } };
  const DS = loadStore();
  const saveStore = () => { try { localStorage.setItem(SKEY, JSON.stringify(DS)); } catch (e) { /* sin almacenamiento */ } };
  const shuffled = n => { const a = Array.from({ length: n }, (_, i) => i); for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; };
  /* saca una frase de `key` sin repetir ninguna hasta que se agoten todas (la bolsa se guarda en localStorage: tampoco se repite si cierras y abres el juego) */
  function pickLine(key) {
    const arr = LINES[key]; if (!arr || !arr.length) return null;
    let bag = DS.bags[key];
    if (!bag || bag.order.length !== arr.length || bag.pos >= bag.order.length) { bag = { order: shuffled(arr.length), pos: 0 }; DS.bags[key] = bag; }
    const idx = bag.order[bag.pos]; bag.pos++; saveStore();
    return arr[idx];
  }
  /* contexto: primera visita de la sesion, ¿ha vuelto antes?, hora del dia, fin de semana */
  let sessionCounted = false, isReturning = false;
  function noteVisit() {
    if (sessionCounted) return; sessionCounted = true;
    const now = Date.now(); isReturning = DS.visits > 0 && (now - DS.lastSeen) > 20 * 60 * 1000;   // sesion nueva de verdad: han pasado >20 min desde la ultima
    DS.visits++; DS.lastSeen = now; saveStore();
  }
  const timeBucket = () => { const h = new Date().getHours(); return h < 5 ? "homeTimeNight" : h < 12 ? "homeTimeMorning" : h < 19 ? "homeTimeAfternoon" : h < 23 ? "homeTimeEvening" : "homeTimeNight"; };
  const isWeekend = () => { const d = new Date().getDay(); return d === 0 || d === 6; };

  /* ---------------------------------------------------------------- pantalla principal: apariciones sueltas del crupier mientras el jugador elige modo */
  const HOME_CORNERS = ["home-tl", "home-tr"];
  let homeT = 0, lastCat = "";
  function homeTick() {
    if (!D.onHome) return;
    if (!document.querySelector(".hh") || D.busy) { homeT = setTimeout(homeTick, 2500); return; }         // solo en la pantalla de inicio, y no interrumpe si ya esta hablando
    noteVisit();
    const P = A.profile ? A.profile.get() : null, hasSave = A.adv && A.adv.hasSave && A.adv.hasSave(), seen = P && P.ach ? Object.keys(P.ach).length : 0;
    const pool = []; const push = (k, n) => { for (let i = 0; i < n; i++) pool.push(k); };
    if (hasSave) { push("homeTempt", 5); push("homeTaunt", 3); push("homeTrivia", 3); }                    // partida a medias: mas tentacion para que la retome
    else if (!seen) { push("homeTaunt", 5); push("homeTrivia", 4); push("homeTempt", 2); }                 // nunca ha jugado: mas burla y datos, poca tentacion
    else { push("homeTaunt", 4); push("homeTrivia", 4); push("homeTempt", 3); }
    push(timeBucket(), 2); if (isWeekend()) push("homeTimeWeekend", 2);
    if (isReturning) push("homeReturn", 4);
    push("homeMeta", 1);
    let cat = rand(pool); if (cat === lastCat && pool.some(p => p !== cat)) cat = rand(pool.filter(p => p !== cat));
    const line = pickLine(cat); lastCat = cat;
    ensure(); el.classList.remove(...HOME_CORNERS);
    D.say(line, { mood: rand(["sly", "laugh"]), hold: 4200 + (typeof line === "string" ? line.length : 60) * 24 });
    el.classList.add("home", rand(HOME_CORNERS));
    homeT = setTimeout(homeTick, 14000 + Math.random() * 13000);
  }
  /* activa/desactiva las apariciones de inicio (independiente de D.on, que es solo para dentro de una partida) */
  D.homeTease = on => {
    D.onHome = !!on; clearTimeout(homeT);
    if (!on) { if (el) el.classList.remove(...HOME_CORNERS, "home"); D.hide(); return; }
    ensure(); el.classList.remove("hidden"); homeT = setTimeout(homeTick, 7000 + Math.random() * 6000);
  };

  /* ---------------------------------------------------------------- dentro de una partida: comentarios sueltos del crupier mientras el jugador mira el mapa (no interrumpe retos ni reacciones) */
  let runT = 0, lastRunCat = "";
  function runTick() {
    if (!D.on) return;
    const ph = A.core && A.core.S && A.core.S.phase;
    if (ph !== "asking" || D.busy || D.host) { runT = setTimeout(runTick, 3000); return; }
    const pool = ["runIdle", "runIdle", "runIdle", "homeTrivia", "homeTrivia", "homeTaunt", timeBucket()];
    let cat = rand(pool); if (cat === lastRunCat && pool.some(p => p !== cat)) cat = rand(pool.filter(p => p !== cat));
    const line = pickLine(cat); lastRunCat = cat;
    D.say(line, { mood: rand(["sly", "laugh"]), hold: 3800 + (typeof line === "string" ? line.length : 60) * 22 });
    runT = setTimeout(runTick, 26000 + Math.random() * 24000);
  }

  /* reacciones a lo que pasa en la mesa */
  /* rabieta: la pantalla paga el enfado del crupier cuando le ganas una ronda o un jefe (temblor de toda la pantalla, o apagon total con la luz de vuelta) */
  let bo;
  const ensureBO = () => { if (!bo || !bo.isConnected) { bo = document.createElement("div"); bo.id = "dlBlackout"; document.body.appendChild(bo); } return bo; };
  D.fx = kind => {
    if (kind === "shake") { const root = document.documentElement; root.classList.remove("dl-tantrum"); void root.offsetWidth; root.classList.add("dl-tantrum"); setTimeout(() => root.classList.remove("dl-tantrum"), 700); }
    else if (kind === "blackout") { const el = ensureBO(); el.classList.remove("go"); void el.offsetWidth; el.classList.add("go"); setTimeout(() => el.classList.remove("go"), 1300); }
  };
  D.react = (kind, o = {}) => {
    if (!D.on || D.host) return; const ph = A.core && A.core.S && A.core.S.phase; if (ph === "shop" || ph === "title" || ph === "intro") return;
    const p = { bull: 0.9, miss: 0.85, timeout: 1, good: 0.35, streak: 0.5, counter: 1, roundWin: 0.8, roundFail: 1, runWin: 1, runLose: 1 }[kind];
    if (p == null || Math.random() > p) return;
    const reduced = A.core && A.core.S && A.core.S.reduce;
    if (kind === "roundWin" && !reduced && Math.random() < 0.22) {
      const fx = rand(["shake", "blackout"]), line = D.line(fx === "shake" ? "tantrumShake" : "tantrumBlackout");
      if (line) { D.say(line, { mood: "angry" }); D.fx(fx); return; }
    }
    const mood = { bull: "shock", miss: "laugh", timeout: "laugh", good: "sly", streak: "angry", counter: "angry", roundWin: "angry", roundFail: "laugh", runWin: "shock", runLose: "laugh" }[kind];
    const line = D.line(kind === "roundWin" ? "roundWin" : kind);
    if (line) D.say(line, { mood });
  };
})(window.AIQ);
