/* Geolite - traducciones (v0.9): textos nuevos de la Aventura por temas, tienda y menu. Se suman a A.TR (js/i18n2.js). [fr, pt, de, it, es-419, zh, ko, ja, ru] */
window.AIQ = window.AIQ || {};
(function (A) {
  Object.assign(A.TR = A.TR || {}, {
    "Field journal + Chronicler. You shine on battles and events.": ["Carnet de terrain + Chroniqueur. Tu brilles sur les batailles et les événements.", "Caderno de campo + Cronista. Você brilha em batalhas e acontecimentos.", "Feldbuch + Chronist. Du glänzt bei Schlachten und Ereignissen.", "Taccuino di campo + Cronista. Brilli con battaglie ed eventi.", "Diario de campo + Cronista. Brillas en batallas y sucesos.", "野外笔记 + 编年史家。在战役与事件中大放异彩。", "야외 일지 + 연대기 작가. 전투와 사건에서 빛을 발합니다.", "フィールドノート+年代記作者。戦いと出来事で輝く。", "Полевой дневник + Летописец. Ты блистаешь на битвах и событиях."],
    "Poker hand: ": ["Main de poker : ", "Mão de pôquer: ", "Pokerhand: ", "Mano di poker: ", "Mano de póker: ", "扑克牌型：", "포커 핸드: ", "ポーカーハンド: ", "Покерная комбинация: "],
    "Doubloons ×2": ["Doublons ×2", "Dobrões ×2", "Dublonen ×2", "Dobloni ×2", "Doblones ×2", "金币 ×2", "도블론 ×2", "ダブロン×2", "Дублоны ×2"],
    "The Shield saves you: no provision lost! ": ["Le Bouclier te sauve : aucune provision perdue ! ", "O Escudo salva você: nenhuma provisão perdida! ", "Der Schild rettet dich: kein Proviant verloren! ", "Lo Scudo ti salva: nessuna provvista persa! ", "El Escudo te salva: ¡ninguna provisión perdida! ", "护盾救了你：没有损失任何补给！ ", "방패가 당신을 구했습니다: 식량 손실 없음! ", "シールドがあなたを救った：プロビジョンは失われなかった！ ", "Щит спас тебя: ни один запас не потерян! "],
    "No cards left: move on!": ["Plus de cartes : en avant !", "Não restam cartas: siga em frente!", "Keine Karten mehr: weiter geht's!", "Niente più carte: avanti!", "No quedan cartas: ¡a seguir!", "没有更多卡牌了：继续前进吧！", "남은 카드가 없습니다: 계속 진행하세요!", "カードがもうない：先へ進もう！", "Карт больше нет: продолжаем!"],
    "Pick ONE relic for free. Legendaries can show up here.": ["Choisis UNE relique gratuite. Des légendaires peuvent apparaître ici.", "Escolha UMA relíquia de graça. Aqui podem aparecer lendárias.", "Wähle EIN Relikt kostenlos. Hier können Legendäre auftauchen.", "Scegli UNA reliquia gratis. Qui possono uscire le leggendarie.", "Elige UNA reliquia gratis. Aquí pueden aparecer legendarias.", "免费选择一件遗物。这里可能出现传说级遗物。", "유물 하나를 무료로 선택하세요. 여기서는 레전더리도 나올 수 있습니다.", "レリックを1つ無料で選ぼう。ここではレジェンダリーも出現する。", "Выбери ОДНУ реликвию бесплатно. Здесь могут появиться легендарные."],
    "Three cards on the table. Buy, or roll?": ["Trois cartes sur la table. Tu achètes ou tu relances ?", "Três cartas na mesa. Comprar ou rolar?", "Drei Karten auf dem Tisch. Kaufen oder würfeln?", "Tre carte sul tavolo. Compri o tiri?", "Tres cartas sobre la mesa. ¿Compras o tiras de nuevo?", "桌上有三张卡牌。购买还是重新抽取？", "테이블 위에 카드 세 장. 구매할까요, 다시 뽑을까요?", "テーブルに3枚のカード。買う？それともリロール？", "На столе три карты. Купить или перебросить?"],
    "Roll": ["Relancer", "Rolar", "Würfeln", "Tira", "Tirar", "抽取", "뽑기", "リロール", "Бросить"],
    "free": ["gratuit", "grátis", "gratis", "gratis", "gratis", "免费", "무료", "無料", "бесплатно"],
    "Poker hand": ["Main de poker", "Mão de pôquer", "Pokerhand", "Mano di poker", "Mano de póker", "扑克牌型", "포커 핸드", "ポーカーハンド", "Покерная комбинация"],
    "per round": ["par manche", "por rodada", "pro Runde", "per round", "por ronda", "每回合", "라운드당", "ラウンドごと", "за раунд"],
    "Match ranks or suits for a poker-hand bonus": ["Assemble des valeurs ou des couleurs identiques pour un bonus de main de poker", "Junte valores ou naipes iguais para ganhar bônus de mão de pôquer", "Kombiniere gleiche Werte oder Farben für einen Pokerhand-Bonus", "Abbina valori o semi uguali per il bonus mano di poker", "Combina valores o palos iguales para un bono de mano de póker", "凑出相同点数或花色以获得扑克牌型加成", "숫자나 무늬를 맞춰 포커 핸드 보너스를 받으세요", "ランクやスートを揃えてポーカーハンドボーナスを得よう", "Собери одинаковые значения или масти для бонуса покерной комбинации"],
    "Roguelike: every run is different. Topics, relics, doubloons and bosses.": ["Roguelike : chaque partie est différente. Thèmes, reliques, doublons et boss.", "Roguelike: cada partida é diferente. Temas, relíquias, dobrões e chefes.", "Roguelike: jede Partie ist anders. Themen, Relikte, Dublonen und Bosse.", "Roguelike: ogni partita è diversa. Temi, reliquie, dobloni e boss.", "Roguelike: cada partida es distinta. Temas, reliquias, doblones y jefes.", "Roguelike：每局都不同。主题、遗物、金币与首领。", "로그라이크: 매 판마다 다릅니다. 주제, 유물, 도블론, 보스.", "ローグライク：毎回違う展開。テーマ、レリック、ダブロン、ボス。", "Роглайк: каждый забег уникален. Темы, реликвии, дублоны и боссы."],
    "New content": ["Contenu nouveau", "Conteúdo novo", "Neue Inhalte", "Contenuti nuovi", "Contenido nuevo", "全新内容", "새로운 콘텐츠", "新コンテンツ", "Новый контент"],
    "You scored {s} of {a}. You have {n} provisions left.": ["Tu as fait {s} sur {a}. Il te reste {n} provisions.", "Você fez {s} de {a}. Restam {n} provisões.", "Du hast {s} von {a}. Es bleiben {n} Proviant.", "Hai fatto {s} su {a}. Ti restano {n} provviste.", "Conseguiste {s} de {a}. Te quedan {n} provisiones.", "你得了 {s} / {a} 分。还剩 {n} 份补给。", "{a} 중 {s}점을 얻었습니다. 식량이 {n}개 남았습니다.", "{a}のうち{s}を獲得。プロビジョン残り{n}。", "Ты набрал {s} из {a}. Осталось запасов: {n}."],
    "Starts with “{l}”": ["Commence par « {l} »", "Começa com “{l}”", "Beginnt mit „{l}“", "Inizia con «{l}»", "Empieza con “{l}”", "以“{l}”开头", "“{l}”로 시작", "「{l}」で始まる", "Начинается на «{l}»"],
    "Northern hemisphere": ["Hémisphère nord", "Hemisfério norte", "Nordhalbkugel", "Emisfero nord", "Hemisferio norte", "北半球", "북반구", "北半球", "Северное полушарие"], "Southern hemisphere": ["Hémisphère sud", "Hemisfério sul", "Südhalbkugel", "Emisfero sud", "Hemisferio sur", "南半球", "남반구", "南半球", "Южное полушарие"],
    "east": ["est", "leste", "Ost", "est", "este", "东", "동", "東", "восток"], "west": ["ouest", "oeste", "West", "ovest", "oeste", "西", "서", "西", "запад"],
    "Reset Encyclopedia": ["Réinitialiser l'Encyclopédie", "Redefinir a Enciclopédia", "Enzyklopädie zurücksetzen", "Ripristina l'Enciclopedia", "Restablecer la Enciclopedia", "重置百科全书", "도감 초기화", "図鑑をリセット", "Сбросить энциклопедию"],
    "Data": ["Données", "Dados", "Daten", "Dati", "Datos", "数据", "데이터", "データ", "Данные"],
    "Deletes every unlocked card. Your profile, achievements and records stay.": ["Supprime toutes les cartes débloquées. Ton profil, tes succès et tes records restent.", "Apaga todas as cartas desbloqueadas. Seu perfil, conquistas e recordes continuam.", "Löscht alle freigeschalteten Karten. Profil, Erfolge und Rekorde bleiben.", "Elimina tutte le carte sbloccate. Profilo, obiettivi e record restano.", "Borra todas las cartas desbloqueadas. Tu perfil, logros y récords se mantienen.", "删除所有已解锁的卡片。你的个人资料、成就与记录会保留。", "잠금 해제된 모든 카드를 삭제합니다. 프로필, 업적, 기록은 유지됩니다.", "アンロック済みのカードをすべて削除します。プロフィール、実績、記録は残ります。", "Удаляет все разблокированные карточки. Профиль, достижения и рекорды сохранятся."],
    "Sure? Press again to delete": ["Sûr ? Appuie encore pour supprimer", "Tem certeza? Toque de novo para apagar", "Sicher? Nochmal drücken zum Löschen", "Sicuro? Premi ancora per eliminare", "¿Seguro? Pulsa otra vez para borrar", "确定吗？再点一次以删除", "확실한가요? 삭제하려면 다시 누르세요", "本当に？削除するにはもう一度押してください", "Уверен? Нажми ещё раз, чтобы удалить"],
    "Encyclopedia reset": ["Encyclopédie réinitialisée", "Enciclopédia redefinida", "Enzyklopädie zurückgesetzt", "Enciclopedia ripristinata", "Enciclopedia restablecida", "百科全书已重置", "도감이 초기화되었습니다", "図鑑をリセットしました", "Энциклопедия сброшена"],
    "Boss": ["Boss", "Chefe", "Boss", "Boss", "Jefe", "首领", "보스", "ボス", "Босс"], "Legend": ["Légende", "Lenda", "Legende", "Leggenda", "Leyenda", "传说", "레전드", "レジェンド", "Легенда"],
  });
})(window.AIQ);
