/* Geolite - traducciones (v0.10): retos, crupier, herramientas nuevas y tienda. Se suman a A.TR (js/i18n2.js). [fr, pt, de, it, es-419, zh, ko, ja, ru, pl] */
window.AIQ = window.AIQ || {};
(function (A) {
  Object.assign(A.TR = A.TR || {}, {
    "Astrolabe": ["Astrolabe", "Astrolábio", "Astrolabium", "Astrolabio", "Astrolabio", "星盘", "아스트롤라베", "アストロラーベ", "Астролябия", "Astrolabium"],
    "Master switch": ["Interrupteur général", "Interruptor geral", "Hauptschalter", "Interruttore generale", "Interruptor general", "总开关", "메인 스위치", "マスタースイッチ", "Главный выключатель", "Wyłącznik główny"],
    "Swap card": ["Carte d'échange", "Carta de troca", "Tauschkarte", "Carta di scambio", "Carta de intercambio", "交换卡", "교환 카드", "交換カード", "Карта обмена", "Karta zamiany"],
    "Turns the map upright: beats the Upside-down world for this question.": ["Redresse la carte : vainc le Monde à l'envers pour cette question.", "Endireita o mapa: vence o Mundo de cabeça para baixo nesta pergunta.", "Dreht die Karte aufrecht: schlägt die Welt auf dem Kopf in dieser Frage.", "Raddrizza la mappa: batte il Mondo capovolto per questa domanda.", "Endereza el mapa: anula el Mundo al revés en esta pregunta.", "将地图摆正：在本题中克服“颠倒的世界”。", "지도를 똑바로 세웁니다: 이 문제에서 뒤집힌 세계를 무효화합니다.", "地図を正しい向きに戻す：この問題で「逆さまの世界」を無効化する。", "Переворачивает карту правильно: снимает эффект «Мир вверх ногами» для этого вопроса.", "Odwraca mapę na właściwą stronę: pokonuje Świat do góry nogami w tym pytaniu."],
    "Switches every challenge off for this question.": ["Désactive tous les défis pour cette question.", "Desliga todos os desafios nesta pergunta.", "Schaltet alle Herausforderungen für diese Frage aus.", "Spegne tutte le sfide per questa domanda.", "Desactiva todos los retos en esta pregunta.", "关闭本题的所有挑战效果。", "이 문제의 모든 도전 효과를 끕니다.", "この問題のすべてのチャレンジをオフにする。", "Отключает все испытания для этого вопроса.", "Wyłącza wszystkie wyzwania w tym pytaniu."],
    "Swaps this question for another place from the round.": ["Remplace cette question par un autre lieu de la manche.", "Troca esta pergunta por outro lugar da rodada.", "Tauscht diese Frage gegen einen anderen Ort der Runde.", "Sostituisce questa domanda con un altro luogo del round.", "Cambia esta pregunta por otro lugar de la ronda.", "将本题替换为本轮中的另一个地点。", "이 문제를 라운드의 다른 장소로 교체합니다.", "この問題をラウンド内の別の場所に交換する。", "Заменяет этот вопрос на другое место из раунда.", "Zamienia to pytanie na inne miejsce z rundy."],
    "Field journal + Dictionary. Faded letters won't stop you.": ["Carnet de terrain + Dictionnaire. Les lettres effacées ne t'arrêtent pas.", "Caderno de campo + Dicionário. Letras apagadas não te param.", "Feldbuch + Wörterbuch. Verblasste Buchstaben halten dich nicht auf.", "Taccuino di campo + Dizionario. Le lettere sbiadite non ti fermano.", "Diario de campo + Diccionario. Las letras borrosas no te detendrán.", "野外笔记 + 词典。褪色的字母也难不倒你。", "야외 일지 + 사전. 흐릿한 글자도 당신을 막지 못합니다.", "フィールドノート+辞書。薄れた文字にも動じない。", "Полевой дневник + Словарь. Стёртые буквы тебя не остановят.", "Dziennik terenowy + Słownik. Wyblakłe litery cię nie zatrzymają."],
    "Two compasses and the 16-point compass. You never get lost.": ["Deux boussoles et la boussole à 16 rumbs. Tu ne te perds jamais.", "Duas bússolas e a bússola de 16 pontos. Você nunca se perde.", "Zwei Kompasse und der 16-Strich-Kompass. Du verirrst dich nie.", "Due bussole e la bussola a 16 punte. Non ti perdi mai.", "Dos brújulas y la brújula de 16 puntos. Nunca te pierdes.", "两个指南针加十六方位罗盘。你永远不会迷路。", "나침반 두 개와 16방위 나침반. 절대 길을 잃지 않습니다.", "2つのコンパスと16方位コンパス。決して迷わない。", "Два компаса и 16-румбовый компас. Ты никогда не заблудишься.", "Dwa kompasy i róża wiatrów na 16 kierunków. Nigdy się nie zgubisz."],
    "No tools, with the Miner's lamp and 4 provisions.": ["Sans outils, avec la lampe de mineur et 4 provisions.", "Sem ferramentas, com a lanterna de mineiro e 4 provisões.", "Ohne Werkzeuge, mit der Grubenlampe und 4 Proviant.", "Senza strumenti, con la lampada da minatore e 4 provviste.", "Sin herramientas, con la lámpara de minero y 4 provisiones.", "没有工具，携带矿工灯与 4 份补给。", "도구 없이 광부의 등불과 식량 4개.", "道具なし、鉱夫のランプと4つのプロビジョン。", "Без инструментов, с шахтёрской лампой и 4 запасами.", "Bez narzędzi, z lampą górniczą i 4 zapasami."],
    "The dealer touches the table": ["Le croupier touche à la table", "O crupiê mexe na mesa", "Der Croupier dreht am Tisch", "Il croupier tocca il tavolo", "El crupier toca la mesa", "荷官触碰了桌面", "딜러가 테이블을 건드립니다", "ディーラーがテーブルに手を加える", "Крупье касается стола", "Krupier majstruje przy stole"],
    "Next round": ["Manche suivante", "Próxima rodada", "Nächste Runde", "Prossimo round", "Siguiente ronda", "下一回合", "다음 라운드", "次のラウンド", "Следующий раунд", "Następna runda"],
    "Then": ["Ensuite", "Depois", "Danach", "Poi", "Luego", "然后", "그다음", "次に", "Затем", "Potem"],
    "No tricks": ["Sans tours", "Sem truques", "Keine Tricks", "Nessun trucco", "Sin trucos", "没有花招", "속임수 없음", "トリックなし", "Без трюков", "Bez sztuczek"],
    "Helps against": ["Aide contre", "Ajuda contra", "Hilft gegen", "Aiuta contro", "Ayuda contra", "克制", "대응 도구", "対策になる", "Помогает против", "Pomaga na"],
    "Map upright": ["Carte redressée", "Mapa endireitado", "Karte aufgerichtet", "Mappa raddrizzata", "Mapa enderezado", "地图已摆正", "지도 정방향", "地図が正しい向きに", "Карта выпрямлена", "Mapa prosto"],
    "Challenges off for this question": ["Défis désactivés pour cette question", "Desafios desligados nesta pergunta", "Herausforderungen für diese Frage aus", "Sfide spente per questa domanda", "Retos desactivados en esta pregunta", "本题的挑战已关闭", "이 문제의 도전 비활성화", "この問題のチャレンジはオフ", "Испытания отключены для этого вопроса", "Wyzwania wyłączone w tym pytaniu"],
    "No places left to swap.": ["Plus de lieux à échanger.", "Não restam lugares para trocar.", "Keine Orte mehr zum Tauschen.", "Nessun luogo da scambiare.", "No quedan lugares para intercambiar.", "没有可供交换的地点了。", "교환할 장소가 더 이상 없습니다.", "交換できる場所がもうない。", "Больше нет мест для замены.", "Nie ma już miejsc do zamiany."],
    "Pack full: sell a relic.": ["Sac plein : vends une relique.", "Mochila cheia: venda uma relíquia.", "Rucksack voll: verkaufe ein Relikt.", "Zaino pieno: vendi una reliquia.", "Mochila llena: vende una reliquia.", "背包已满：请出售一件遗物。", "가방이 가득 찼습니다: 유물을 판매하세요.", "バッグが満杯：レリックを売ろう。", "Рюкзак полон: продай реликвию.", "Plecak pełny: sprzedaj relikwię."],
    "Roguelike: the dealer changes the rules. Dark maps, upside-down worlds, shaky letters… and perks to beat him.": ["Roguelike : le croupier change les règles. Cartes dans le noir, à l'envers, lettres tremblantes… et des atouts pour le battre.", "Roguelike: o crupiê muda as regras. Mapas às escuras, de cabeça para baixo, letras trêmulas… e perks para vencê-lo.", "Roguelike: Der Croupier ändert die Regeln. Dunkle Karten, Welt auf dem Kopf, zitternde Buchstaben… und Perks, um ihn zu schlagen.", "Roguelike: il croupier cambia le regole. Mappe al buio, mondo capovolto, lettere tremanti… e perk per batterlo.", "Roguelike: el crupier cambia las reglas. Mapas a oscuras, mundos al revés, letras temblorosas… y reliquias para vencerlo.", "Roguelike：荷官会改变规则。黑暗的地图、颠倒的世界、颤抖的字母……还有克制他的技能。", "로그라이크: 딜러가 규칙을 바꿉니다. 어두운 지도, 뒤집힌 세계, 떨리는 글자… 그리고 그를 이길 특전들.", "ローグライク：ディーラーがルールを変える。暗い地図、逆さまの世界、震える文字……そして彼を倒すためのパーク。", "Роглайк: крупье меняет правила. Тёмные карты, перевёрнутые миры, дрожащие буквы… и способности, чтобы победить его.", "Roguelike: krupier zmienia zasady. Ciemne mapy, światy do góry nogami, drżące litery… i atuty, by go pokonać."],
  });
})(window.AIQ);
