/*
 * Geolite - catalogo de PERKS de la Aventura (v0.10). Ninguno multiplica ni suma puntos: la puntuacion es solo tu precision.
 * Los perks ayudan a resolver los RETOS del crupier (letras temblorosas, mapa borroso, apagon, fronteras falsas, continentes movidos...),
 * mejoran tu puntero, dan pistas, tiempo, supervivencia o doblones. Cada perk es una carta de poker con palo geografico.
 *
 *   fx {..}         mitigaciones de retos y mejoras del puntero (ver A.chal.fx en js/challenges.js)
 *   round(x,run)    al empezar la ronda (x.seconds)                open(api,o,run)  pistas gratis al empezar cada pregunta (api.laterHalf: a mitad de tiempo)
 *   clear(x,run)    al superar una ronda (x.coins)                 shop(x,run)      tienda (x.price -, x.freeReroll)   buy(run) / sell(run)  al comprarla / venderla
 *   post(c,run)     tras puntuar: SOLO doblones (c.coins)          flags: immune[], softenBoss, coinX, toolBonus, interest, shieldAct, sonarErr, compass16, spy, skipFirst
 * Texto: n = nombre y d = descripcion en es|en|fr|pt|de|it|es-419|zh|ko|ja|ru|pl (es-419 vacio = espanol).
 */
window.AIQ = window.AIQ || {};
(function (A) {
  const L6 = A.L6;
  const P = {};
  const def = (id, suit, cost, r, n, d, hooks = {}) => { P[id] = { id, ico: id, suit, cost, r, n: L6(n), d: L6(d), ...hooks }; };
  const seeded = (run, tag) => A.rng(`${run.seed}:${tag}:${run.act}:${run.round}:${run.qi}:${run.qTotal || 0}`)();

  /* ---------------------------------------------------------------- contra retos de TEXTO */
  def("steadyhand", "s_compass", 5, 0, "Mano de crupier|Dealer's hand|Main de croupier|Mão de crupiê|Krupierhand|Mano da croupier||荷官之手|딜러의 손|ディーラーの手|Рука крупье|Ręka krupiera", "Las letras que tiemblan o bailan, el pulso tembloroso y el mareo del puntero bajan un 75 %, y la marquesina se queda quieta.|Shaking or dancing letters, a shaky hand and a dizzy pointer drop by 75%, and the ticker sign stands still.|Les lettres qui tremblent ou dansent, la main tremblante et le vertige du pointeur baissent de 75 %, et l'enseigne défilante s'arrête.|As letras que tremem ou dançam, a mão trêmula e a tontura do ponteiro caem 75 %, e o letreiro fica parado.|Zitternde oder tanzende Buchstaben, zittrige Hand und Zeiger-Schwindel sinken um 75 %, und die Laufschrift bleibt stehen.|Le lettere che tremano o ballano, la mano tremante e il capogiro del puntatore calano del 75 %, e l'insegna scorrevole si ferma.||颤抖或跳舞的字母、手抖和指针眩晕减少 75%，滚动字幕也会停下来。|떨리거나 춤추는 글자, 떨리는 손, 포인터 어지러움이 75% 줄고, 전광판이 멈춰 섭니다.|震える文字や踊る文字、手の震え、ポインターのめまいが75%減り、電光掲示板が止まる。|Дрожь и пляска букв, дрожащая рука и головокружение курсора снижаются на 75%, а бегущая строка замирает.|Drżące i tańczące litery, drżąca ręka i zawrót głowy kursora słabną o 75%, a świetlna reklama staje w miejscu.", { fx: { shakeMul: 0.25, noMarquee: true } });
  def("dictionary", "s_peak", 6, 0, "Chuleta de crupier|Dealer's cheat sheet|Antisèche du croupier|Cola do crupiê|Spickzettel des Croupiers|Bigliettino del croupier|Acordeón del crupier|荷官的小抄|딜러의 커닝 페이퍼|ディーラーのカンニングペーパー|Шпаргалка крупье|Ściąga krupiera", "Las letras borradas vuelven una a una, las cambiadas o mezcladas vuelven a su sitio a los 2 segundos y el nombre ya no sale en otro idioma.|Faded letters come back one by one, swapped or shuffled letters return to their place after 2 seconds, and the name no longer shows up in another language.|Les lettres effacées reviennent une à une, les lettres échangées ou mélangées reprennent leur place au bout de 2 secondes et le nom n'apparaît plus dans une autre langue.|As letras apagadas voltam uma a uma, as trocadas ou embaralhadas voltam ao lugar após 2 segundos e o nome já não aparece em outro idioma.|Verblasste Buchstaben kehren einzeln zurück, vertauschte oder gemischte springen nach 2 Sekunden an ihren Platz, und der Name erscheint nicht mehr in einer anderen Sprache.|Le lettere sbiadite tornano una a una, quelle scambiate o mescolate tornano al loro posto dopo 2 secondi e il nome non appare più in un'altra lingua.||褪色的字母会一个个恢复，错位或打乱的字母 2 秒后回到原位，名字也不会再用别的语言出现。|바랜 글자가 하나씩 돌아오고, 뒤바뀌거나 섞인 글자는 2초 뒤 제자리로 돌아오며, 이름이 더 이상 다른 언어로 나오지 않습니다.|かすれた文字が一つずつ戻り、入れ替わった文字や混ざった文字は2秒後に元の位置へ戻り、名前が別の言語で出なくなる。|Выцветшие буквы возвращаются одна за другой, переставленные или перемешанные через 2 секунды встают на место, а название больше не появляется на другом языке.|Wyblakłe litery wracają jedna po drugiej, zamienione lub wymieszane po 2 sekundach wracają na miejsce, a nazwa nie pojawia się już w innym języku.", { fx: { missingRate: 0.9, unswapMs: 2000, noBabel: true } });
  def("handmirror", "s_compass", 5, 0, "Espejo del ilusionista|Conjurer's mirror|Miroir de l'illusionniste|Espelho do ilusionista|Spiegel des Illusionisten|Specchio dell'illusionista||魔术师之镜|마술사의 거울|奇術師の鏡|Зеркало фокусника|Lustro iluzjonisty", "Nombres en espejo o del revés se leen normal, y el mapa en espejo o con el Sur arriba y el puntero invertido vuelven a su sitio.|Mirrored or upside-down names read normally, and a mirrored or south-up map and a reversed pointer are set right.|Les noms en miroir ou à l'envers se lisent normalement, et la carte miroir ou avec le Sud en haut comme le pointeur inversé reviennent à la normale.|Nomes espelhados ou de cabeça para baixo ficam normais, e o mapa espelhado ou com o Sul em cima e o ponteiro invertido voltam ao lugar.|Gespiegelte oder kopfstehende Namen sind normal lesbar; Spiegelkarte, Karte mit Süden oben und umgekehrter Zeiger werden korrigiert.|I nomi a specchio o capovolti si leggono normali, e la mappa a specchio o con il Sud in alto e il puntatore invertito tornano a posto.||镜像或倒置的名字恢复正常，镜像或南方朝上的地图和反向指针也会复原。|거울상이나 뒤집힌 이름이 정상으로 보이고, 거울 지도나 남쪽이 위인 지도와 반전된 포인터도 제자리로 돌아옵니다.|鏡文字や逆さまの名前が普通に読め、鏡の地図や南が上の地図、逆操作のポインターも元に戻る。|Зеркальные и перевёрнутые названия читаются нормально, а зеркальная карта, карта с югом наверху и обратный курсор возвращаются на место.|Lustrzane i odwrócone nazwy czytasz normalnie, a lustrzana mapa, mapa z południem u góry i odwrócony kursor wracają do normy.", { fx: { unmirror: true } });
  def("spectacles", "s_palm", 6, 1, "Visera de crupier|Dealer's eyeshade|Visière de croupier|Viseira de crupiê|Krupier-Augenschirm|Visiera da croupier||荷官的遮光帽|딜러의 챙모자|ディーラーのサンバイザー|Козырёк крупье|Daszek krupiera", "Las letras que tiemblan o bailan, las borradas, las cambiadas, las runas y la memoria de pez tienen la mitad de efecto.|Shaking or dancing letters, faded and swapped letters, runes and goldfish memory have half the effect.|Les lettres qui tremblent ou dansent, effacées ou échangées, les runes et la mémoire de poisson ont moitié moins d'effet.|As letras que tremem ou dançam, apagadas ou trocadas, as runas e a memória de peixe têm metade do efeito.|Zitternde oder tanzende, verblasste und vertauschte Buchstaben, Runen und Fischgedächtnis wirken nur halb so stark.|Le lettere che tremano o ballano, sbiadite o scambiate, le rune e la memoria di pesce hanno metà dell'effetto.||颤抖或跳舞的字母、褪色和错位的字母、符文以及金鱼记忆，效果减半。|떨리거나 춤추는 글자, 바랜 글자와 뒤바뀐 글자, 룬 문자, 금붕어 기억력의 효과가 절반이 됩니다.|震える文字や踊る文字、かすれた文字、入れ替わった文字、ルーン文字、金魚の記憶力の効果が半減する。|Дрожащие и танцующие, выцветшие и переставленные буквы, руны и память как у рыбки действуют вдвое слабее.|Drżące i tańczące, wyblakłe i zamienione litery, runy oraz pamięć złotej rybki działają o połowę słabiej.", { fx: { textMul: 0.5 } });

  /* ---------------------------------------------------------------- contra retos del MAPA */
  def("miner", "s_peak", 5, 0, "Foco del vigilante|Pit boss's spotlight|Projecteur du chef de table|Holofote do supervisor|Scheinwerfer des Pitbosses|Faro del capotavolo||场务经理的聚光灯|플로어 매니저의 스포트라이트|ピットボスのスポットライト|Прожектор пит-босса|Reflektor szefa sali", "Tu haz de luz es casi el doble de ancho en un apagón. Si las luces parpadean, te avisa antes de cada corte y la sala solo se oscurece a medias. Y alumbra las banderas a oscuras.|Your light beam is almost twice as wide in a blackout. If the lights flicker, it warns you before each cut and the room only half darkens. It also lights up flags in the dark.|Ton faisceau est presque deux fois plus large en cas de panne. Si les lumières clignotent, il te prévient avant chaque coupure et la salle ne s'assombrit qu'à moitié. Il éclaire aussi les drapeaux dans le noir.|Seu feixe de luz é quase o dobro num apagão. Se as luzes piscarem, ele avisa antes de cada corte e a sala só escurece pela metade. E ilumina as bandeiras no escuro.|Dein Lichtkegel ist bei Stromausfall fast doppelt so breit. Flackert das Licht, warnt er dich vor jedem Ausfall und der Saal wird nur halb dunkel. Und er beleuchtet Flaggen im Dunkeln.|Il tuo fascio di luce è quasi il doppio in un blackout. Se le luci sfarfallano, ti avvisa prima di ogni taglio e la sala si oscura solo a metà. E illumina le bandiere al buio.||停电时你的光束宽度几乎翻倍。灯光闪烁时，每次断电前都会提醒你，房间也只会暗一半。黑暗中的国旗也会被照亮。|정전 중 빛줄기가 거의 두 배로 넓어집니다. 조명이 깜빡이면 끊기기 전에 미리 알려 주고 방은 절반만 어두워집니다. 어둠 속의 국기도 비춰 줍니다.|停電中、光の範囲がほぼ2倍に広がる。照明が点滅するときは切れる前に知らせてくれ、部屋は半分しか暗くならない。暗闇の国旗も照らす。|При отключении света твой луч почти вдвое шире. Если свет мигает, он предупреждает перед каждым отключением, и зал темнеет лишь наполовину. А ещё освещает флаги в темноте.|Podczas awarii prądu twój snop światła jest prawie dwa razy szerszy. Gdy światła migają, ostrzega przed każdym zgaśnięciem, a sala ciemnieje tylko do połowy. Oświetla też flagi w ciemności.", { fx: { darkR: 1.9, halo: true, flickerWarn: true, blackoutMul: 0.5 } });
  def("lens", "s_compass", 6, 1, "Lupa del tasador|Appraiser's loupe|Loupe de l'expert|Lupa do avaliador|Lupe des Schätzers|Lente del perito||鉴定师的放大镜|감정사의 확대경|鑑定士のルーペ|Лупа оценщика|Lupa rzeczoznawcy", "Un círculo nítido sigue a tu puntero en un mapa borroso, los píxeles gordos se afinan y las banderas de neón o sin color recuperan casi todo su color.|A sharp circle follows your pointer on a blurry map, chunky pixels get finer, and neon or colorless flags get most of their color back.|Un cercle net suit ton pointeur sur une carte floue, les gros pixels s'affinent et les drapeaux néon ou sans couleurs retrouvent presque toute leur couleur.|Um círculo nítido acompanha o ponteiro num mapa desfocado, os pixels gordos ficam mais finos e as bandeiras em neon ou sem cor recuperam quase toda a cor.|Ein scharfer Kreis folgt deinem Zeiger auf unscharfer Karte, grobe Pixel werden feiner, und Neon- oder farblose Flaggen bekommen fast ihre ganze Farbe zurück.|Un cerchio nitido segue il puntatore su una mappa sfocata, i pixel giganti si affinano e le bandiere al neon o senza colori ritrovano quasi tutto il colore.||在模糊的地图上，一个清晰的圆圈跟随你的指针；粗大像素会变细，霓虹或无色的国旗也会恢复大部分颜色。|흐릿한 지도에서 선명한 원이 포인터를 따라다니고, 큼직한 픽셀은 촘촘해지며, 네온이나 색 없는 국기는 색을 거의 되찾습니다.|ぼやけた地図で、くっきりした円がポインターについてくる。粗いピクセルは細かくなり、ネオンや色のない国旗もほとんど色が戻る。|На размытой карте за курсором следует чёткий круг, крупные пиксели мельчают, а неоновые или бесцветные флаги почти полностью возвращают цвет.|Na rozmytej mapie za kursorem podąża ostre koło, grube piksele robią się drobniejsze, a neonowe lub bezbarwne flagi odzyskują prawie cały kolor.", { fx: { lensR: 120, mosaicMul: 0.4, colorMul: 0.25 } });
  def("divingmask", "s_palm", 5, 0, "Gafas de sol de crupier|Dealer's sunglasses|Lunettes de soleil du croupier|Óculos de sol do crupiê|Krupier-Sonnenbrille|Occhiali da sole del croupier|Lentes de sol de crupier|荷官的墨镜|딜러의 선글라스|ディーラーのサングラス|Очки крупье|Okulary krupiera", "El desenfoque del mapa, del puntero y de la bandera baja un 80 %, y la miopía y el punto ciego se encogen a la mitad.|Map, pointer and flag blur drop by 80%, and nearsightedness and the blind spot shrink by half.|Le flou de la carte, du pointeur et du drapeau baisse de 80 %, et la myopie comme l'angle mort rétrécissent de moitié.|O desfoque do mapa, do ponteiro e da bandeira cai 80%, e a miopia e o ponto cego encolhem pela metade.|Die Unschärfe von Karte, Zeiger und Flagge sinkt um 80 %, und Kurzsichtigkeit und blinder Fleck schrumpfen auf die Hälfte.|La sfocatura di mappa, puntatore e bandiera scende dell'80%, e la miopia e il punto cieco si rimpiccioliscono della metà.||地图、指针和国旗的模糊减少 80%，近视和盲点也缩小一半。|지도, 포인터, 국기의 흐림이 80% 줄고, 근시와 사각지대가 절반으로 줄어듭니다.|地図・ポインター・国旗のぼやけが80%減り、近視と死角も半分に縮む。|Размытие карты, курсора и флага снижается на 80%, а близорукость и слепое пятно уменьшаются вдвое.|Rozmycie mapy, kursora i flagi spada o 80%, a krótkowzroczność i martwe pole kurczą się o połowę.", { fx: { blurMul: 0.2, focusMul: 0.5 } });
  def("customs", "s_pin", 7, 1, "Sello de la casa|House stamp|Cachet de la maison|Carimbo da casa|Stempel des Hauses|Timbro della casa||赌场印章|하우스 도장|ハウスの印章|Печать заведения|Pieczątka kasyna", "Ves las fronteras verdaderas en un círculo junto a tu puntero, las chinchetas trampa se delatan y el mapa o la bandera en negativo recuperan sus colores.|You see the true borders in a circle around your pointer, decoy pins give themselves away, and a negative map or flag gets its colors back.|Tu vois les vraies frontières dans un cercle autour de ton pointeur, les épingles leurres se trahissent et la carte ou le drapeau en négatif retrouvent leurs couleurs.|Você vê as fronteiras verdadeiras num círculo ao redor do ponteiro, os pinos falsos se denunciam e o mapa ou a bandeira em negativo recuperam as cores.|Du siehst die echten Grenzen in einem Kreis um deinen Zeiger, Lockvogel-Pins verraten sich, und Karte oder Flagge im Negativ bekommen ihre Farben zurück.|Vedi i veri confini in un cerchio attorno al puntatore, i pin esca si tradiscono e la mappa o la bandiera in negativo ritrovano i loro colori.|Ves las fronteras verdaderas en un círculo junto a tu puntero, las chinches trampa se delatan y el mapa o la bandera en negativo recuperan sus colores.|你能在指针周围的圆圈中看到真实边界，诱饵图钉会露馅，负片的地图或国旗也会恢复颜色。|포인터 주변 원 안에서 진짜 국경이 보이고, 가짜 핀은 정체가 드러나며, 네거티브 지도나 국기는 색을 되찾습니다.|ポインターの周りの円の中に本当の国境が見え、おとりピンは正体がばれ、ネガの地図や国旗は色が戻る。|В круге вокруг курсора видны настоящие границы, ложные булавки выдают себя, а негативная карта или флаг возвращают цвета.|W kole wokół kursora widzisz prawdziwe granice, fałszywe pinezki się zdradzają, a mapa lub flaga w negatywie odzyskują kolory.", { fx: { trueR: 110, peekR: 110, trapGhost: true, noNegative: true } });
  def("plates", "s_palm", 8, 2, "Nivel de crupier|Dealer's level|Niveau du croupier|Nível do crupiê|Wasserwaage des Croupiers|Livella del croupier||荷官的水平仪|딜러의 수평계|ディーラーの水準器|Уровень крупье|Poziomica krupiera", "Pangea y los continentes movidos quedan más cerca de su sitio real (60 % menos de desplazamiento).|Pangaea and moved continents end up closer to their real place (60% less displacement).|La Pangée et les continents déplacés restent plus près de leur vraie place (60 % de décalage en moins).|A Pangeia e os continentes movidos ficam mais perto do lugar real (60 % menos de deslocamento).|Pangaea und verschobene Kontinente liegen näher an ihrem echten Platz (60 % weniger Verschiebung).|La Pangea e i continenti spostati restano più vicini al loro posto reale (60 % di spostamento in meno).||盘古大陆和移位的大洲会更接近真实位置（位移减少 60%）。|판게아와 이동한 대륙이 실제 위치에 더 가까워집니다(이동량 60% 감소).|パンゲアや移動した大陸が本来の位置に近づく（ずれが60%減少）。|Пангея и сдвинутые континенты оказываются ближе к реальному месту (смещение на 60% меньше).|Pangea i przesunięte kontynenty lądują bliżej swojego miejsca (o 60% mniejsze przesunięcie).", { fx: { plateMul: 0.4 } });
  def("weathervane", "s_compass", 6, 1, "Ancla de mesa|Table anchor|Ancre de table|Âncora de mesa|Tischanker|Ancora da tavolo||牌桌之锚|테이블 닻|テーブルの錨|Якорь стола|Kotwica stołu", "El viento te empuja la mitad.|The wind pushes you only half as hard.|Le vent te pousse deux fois moins fort.|O vento te empurra só a metade.|Der Wind schiebt dich nur halb so stark.|Il vento ti spinge la metà.||风对你的推力减半。|바람이 절반의 힘으로만 밀어냅니다.|風に押される力が半分になる。|Ветер толкает тебя вдвое слабее.|Wiatr spycha cię o połowę słabiej.", { fx: { windMul: 0.5 } });

  /* ---------------------------------------------------------------- puntero */

  /* ---------------------------------------------------------------- pistas gratis y herramientas */
  def("sextant", "s_palm", 5, 0, "Soplo del crupier|Dealer's tip-off|Tuyau du croupier|Dica do crupiê|Tipp vom Croupier|Soffiata del croupier||荷官的暗示|딜러의 귀띔|ディーラーの耳打ち|Подсказка крупье|Cynk od krupiera", "Al empezar cada pregunta se te dice en qué continente está.|At the start of every question you're told which continent it is on.|Au début de chaque question, on te dit sur quel continent elle se trouve.|No início de cada pergunta dizem-te em que continente fica.|Zu Beginn jeder Frage erfährst du, auf welchem Kontinent es liegt.|All'inizio di ogni domanda ti dicono in quale continente si trova.||每题开始时都会告诉你它在哪个大洲。|매 문제 시작 시 어느 대륙인지 알려줍니다.|毎問の最初に、どの大陸にあるか教えてもらえる。|В начале каждого вопроса тебе говорят, на каком он континенте.|Na początku każdego pytania dowiadujesz się, na jakim to kontynencie.", { open: (api, o) => api.note(api.continent(o), "sextant") });
  def("atlasbook", "s_peak", 9, 2, "Chuleta de bolsillo|Pocket cheat sheet|Antisèche de poche|Cola de bolso|Taschenspickzettel|Bigliettino tascabile|Acordeón de bolsillo|口袋小抄|주머니 커닝 페이퍼|ポケットのカンペ|Карманная шпаргалка|Ściąga w kieszeni", "En cada pregunta, con 5 s restantes se ilumina en el mapa el país del lugar.|On every question, with 5 s left the place's country lights up on the map.|À chaque question, avec 5 s restantes, le pays du lieu s'illumine sur la carte.|Em cada pergunta, com 5 s restantes o país do lugar se ilumina no mapa.|Bei jeder Frage leuchtet bei 5 s Restzeit das Land des Ortes auf der Karte auf.|A ogni domanda, con 5 s rimasti il paese del luogo si illumina sulla mappa.||每题剩余 5 秒时，地点所在国家会在地图上亮起。|매 문제에서 5초가 남으면 장소의 국가가 지도에 표시됩니다.|毎問、残り5秒でその場所の国が地図上で光る。|На каждом вопросе за 5 с до конца страна места подсвечивается на карте.|W każdym pytaniu na 5 s przed końcem kraj miejsca podświetla się na mapie.", { open: (api, o) => api.later(5, () => api.country(o)) });
  def("almanac", "s_peak", 6, 1, "Libro de la casa|House ledger|Registre de la maison|Livro da casa|Hausregister|Registro della casa||赌场账簿|하우스 장부|ハウスの帳簿|Книга заведения|Księga kasyna", "En cada pregunta, lees gratis la nota de campo del lugar; y si el nombre llega en forma de adivinanza, se desvela a los 3 segundos.|On every question, read the place's field note for free; and if the name comes as a riddle, it's revealed after 3 seconds.|À chaque question, tu lis gratuitement la note de terrain du lieu ; et si le nom arrive sous forme de devinette, il se dévoile au bout de 3 secondes.|Em cada pergunta, você lê grátis a nota de campo do lugar; e se o nome vier como adivinha, é revelado após 3 segundos.|Bei jeder Frage liest du die Feldnotiz des Ortes gratis; und kommt der Name als Rätsel, wird er nach 3 Sekunden aufgedeckt.|A ogni domanda, leggi gratis la nota di campo del luogo; e se il nome arriva come indovinello, si svela dopo 3 secondi.||每题都可以免费阅读该地点的野外笔记；如果名字以谜语形式出现，3 秒后会揭晓。|매 문제에서 장소의 야외 일지를 무료로 읽을 수 있고, 이름이 수수께끼로 나오면 3초 뒤에 밝혀집니다.|毎問、その場所のフィールドノートを無料で読める。名前がなぞなぞで出たら、3秒後に明かされる。|На каждом вопросе полевая заметка о месте доступна бесплатно, а если название дано загадкой, через 3 секунды оно раскрывается.|W każdym pytaniu czytasz notatkę terenową za darmo, a jeśli nazwa przychodzi jako zagadka, po 3 sekundach zostaje odsłonięta.", { open: (api, o) => api.fact(o), fx: { riddleMs: 3000 } });
  def("sonarplus", "s_compass", 6, 1, "Sonar trucado|Loaded sonar|Sonar truqué|Sonar viciado|Frisiertes Sonar|Sonar truccato||加料声呐|조작된 소나|イカサマソナー|Заряженный сонар|Podrasowany sonar", "El Sonar solo se equivoca un ±2 % (en vez de ±6 %).|Sonar is off by only ±2% (instead of ±6%).|Le sonar ne se trompe que de ±2 % (au lieu de ±6 %).|O Sonar erra só ±2% (em vez de ±6%).|Das Sonar irrt nur um ±2 % (statt ±6 %).|Il Sonar sbaglia solo del ±2% (invece del ±6%).||声呐误差仅 ±2%（而非 ±6%）。|소나 오차가 ±6% 대신 ±2%로 줄어듭니다.|ソナーの誤差が±6%ではなく±2%になる。|Погрешность сонара всего ±2% (вместо ±6%).|Sonar myli się tylko o ±2% (zamiast ±6%).", { sonarErr: 0.02 });
  def("compass16", "s_peak", 6, 1, "Ruleta de 16 rumbos|16-point roulette|Roulette à 16 directions|Roleta de 16 rumos|16-Feld-Roulette|Roulette a 16 direzioni||十六方位轮盘|16방위 룰렛|16方位ルーレット|16-румбовая рулетка|Ruletka na 16 pól", "La Brújula señala 16 direcciones en vez de 8.|The Compass points in 16 directions instead of 8.|La boussole indique 16 directions au lieu de 8.|A Bússola aponta 16 direções em vez de 8.|Der Kompass zeigt 16 statt 8 Richtungen.|La Bussola indica 16 direzioni invece di 8.||指南针指向 16 个方位，而非 8 个。|나침반이 8방향 대신 16방향을 가리킵니다.|コンパスが8方位ではなく16方位を示す。|Компас показывает 16 направлений вместо 8.|Kompas wskazuje 16 kierunków zamiast 8.", { compass16: true });
  def("glass", "s_palm", 8, 2, "Catalejo del apostador|Gambler's spyglass|Longue-vue du parieur|Luneta do apostador|Fernrohr des Spielers|Cannocchiale dello scommettitore||赌徒的望远镜|도박사의 망원경|ギャンブラーの望遠鏡|Подзорная труба игрока|Luneta hazardzisty", "+1 carga en todas tus herramientas.|+1 charge on all your tools.|+1 charge sur tous tes outils.|+1 carga em todas as suas ferramentas.|+1 Ladung für alle Werkzeuge.|+1 carica su tutti i tuoi strumenti.||所有工具 +1 使用次数。|모든 도구에 충전 +1.|すべての道具にチャージ+1。|+1 заряд ко всем твоим инструментам.|+1 ładunek do wszystkich narzędzi.", { toolBonus: 1 });
  def("spyhole", "s_pin", 5, 1, "Ojo en el cielo|Eye in the sky|Œil dans le ciel|Olho no céu|Auge im Himmel|Occhio nel cielo||天空之眼|하늘의 눈|天の目|Всевидящее око|Oko w niebie", "El Campamento te muestra los retos de las 2 próximas rondas.|Camp shows you the challenges of the next 2 rounds.|Le camp te montre les défis des 2 prochaines manches.|O Acampamento mostra os desafios das 2 próximas rodadas.|Das Lager zeigt die Herausforderungen der nächsten 2 Runden.|Il Campo mostra le sfide dei prossimi 2 round.||营地会显示接下来 2 个回合的挑战。|캠프에서 다음 2라운드의 도전을 보여줍니다.|キャンプで次の2ラウンドのチャレンジが分かる。|Лагерь показывает испытания следующих 2 раундов.|Obóz pokazuje wyzwania z 2 następnych rund.", { spy: 1 });

  /* ---------------------------------------------------------------- tiempo */
  def("boots", "s_palm", 4, 0, "Cortesía de la casa|House comp|Cadeau de la maison|Cortesia da casa|Kulanz des Hauses|Omaggio della casa||赌场赠品|하우스 서비스|ハウスのサービス|Подарок заведения|Prezent od kasyna", "+3 s por pregunta.|+3 s per question.|+3 s par question.|+3 s por pergunta.|+3 s pro Frage.|+3 s per domanda.||每题 +3 秒。|문제당 +3초.|1問につき+3秒。|+3 с на вопрос.|+3 s na pytanie.", { round: x => { x.seconds += 3; } });

  /* ---------------------------------------------------------------- economia (doblones y tienda) */
  def("purse", "s_pin", 4, 0, "Ficha de propina|Tip chip|Jeton de pourboire|Ficha de gorjeta|Trinkgeld-Chip|Fiche di mancia||小费筹码|팁 칩|チップのチップ|Фишка на чай|Żeton na napiwek", "+1 doblón por cada respuesta con 750 puntos de precisión o más (máximo 1000).|+1 doubloon for every answer with 750 accuracy points or more (max 1000).|+1 doublon pour chaque réponse avec 750 points de précision ou plus (maximum 1000).|+1 dobrão por cada resposta com 750 pontos de precisão ou mais (máximo 1000).|+1 Dublone für jede Antwort mit 750 Genauigkeitspunkten oder mehr (maximal 1000).|+1 doblone per ogni risposta con 750 punti di precisione o più (massimo 1000).||每个精准度达到 750 分以上的回答 +1 金币（满分 1000）。|정확도 750점 이상인 답마다 도블론 +1 (최대 1000).|精度750ポイント以上の回答ごとに+1ダブロン（最大1000）。|+1 дублон за каждый ответ с точностью 750 очков и выше (макс. 1000).|+1 dublon za każdą odpowiedź z 750 lub więcej punktami celności (maks. 1000).", { post: c => (c.dist >= 750 ? (c.coins += 1, "+1") : null) });
  def("hoard", "s_pin", 6, 1, "Cajero|Cashier|Caissier|Caixa|Kassierer|Cassiere||出纳员|캐셔|キャッシャー|Кассир|Kasjer", "+2 doblones al superar una ronda.|+2 doubloons when you clear a round.|+2 doublons en réussissant une manche.|+2 dobrões ao superar uma rodada.|+2 Dublonen beim Bestehen einer Runde.|+2 dobloni al superare un round.||通过一回合 +2 金币。|라운드를 클리어하면 도블론 +2.|ラウンドをクリアすると+2ダブロン。|+2 дублона за прохождение раунда.|+2 dublony za zaliczenie rundy.", { clear: x => { x.coins += 2; return "+2"; } });
  def("coupon", "s_pin", 5, 0, "Vale de la casa|House voucher|Bon de la maison|Vale da casa|Hausgutschein|Buono della casa|Cupón de la casa|赌场优惠券|하우스 쿠폰|ハウスの割引券|Ваучер заведения|Bon kasyna", "Las cartas, las provisiones y los suministros del Campamento cuestan 1 doblón menos. Sobornar, Barajar y Cambiar cartas cuestan lo mismo.|Camp cards, provisions and supplies cost 1 doubloon less. Bribe, Reshuffle and New cards cost the same.|Les cartes, provisions et fournitures du Camp coûtent 1 doublon de moins. Soudoyer, Mélanger et Nouvelles cartes coûtent pareil.|Cartas, provisões e suprimentos do Acampamento custam 1 dobrão a menos. Subornar, Embaralhar e Novas cartas custam o mesmo.|Karten, Proviant und Rundenvorräte im Lager kosten 1 Dublone weniger. Bestechen, Mischen und Neue Karten kosten gleich viel.|Carte, provviste e rifornimenti del Campo costano 1 doblone in meno. Corrompi, Rimescola e Nuove carte costano uguale.||营地的卡牌、补给和物资便宜 1 金币。贿赂、重新洗牌和新卡牌价格不变。|캠프의 카드, 식량, 보급품이 도블론 1개 저렴해집니다. 매수, 다시 섞기, 새 카드는 그대로입니다.|キャンプのカード、プロビジョン、補給品が1ダブロン安くなる。買収、シャッフル、新しいカードは値段そのまま。|Карты, запасы и снаряжение на раунд в лагере на 1 дублон дешевле. «Подкупить», «Перетасовать» и «Новые карты» стоят как прежде.|Karty, zapasy i zaopatrzenie w obozie kosztują 1 dublon mniej. Przekup, Przetasuj i Nowe karty kosztują tyle samo.", { shop: x => { x.price -= 1; } });
  def("banker", "s_pin", 8, 2, "Banquero|Banker|Banquier|Banqueiro|Bankier|Banchiere||银行家|은행가|銀行家|Банкир|Bankier", "El interés de fin de ronda (1 doblón por cada 10 que tengas) sube su tope de +2 a +4.|The end-of-round interest (1 doubloon per 10 you hold) rises from a cap of +2 to +4.|L'intérêt de fin de manche (1 doublon pour 10 en poche) passe d'un plafond de +2 à +4.|Os juros no fim da ronda (1 dobrão por cada 10 que tens) sobem o limite de +2 para +4.|Die Zinsen am Rundenende (1 Dublone pro 10 im Besitz) steigen von maximal +2 auf +4.|Gli interessi a fine round (1 doblone ogni 10 che hai) salgono dal tetto di +2 a +4.||回合结束时的利息（每持有 10 枚得 1 枚）上限从 +2 提高到 +4。|라운드 종료 이자(보유 10개당 1개)의 상한이 +2에서 +4로 오릅니다.|ラウンド終了時の利息（10枚ごとに1枚）の上限が+2から+4に上がる。|Проценты в конце раунда (1 дублон за каждые 10) растут с лимита +2 до +4.|Odsetki na koniec rundy (1 dublon za każde 10) rosną z limitu +2 do +4.", { interest: 4 });

  /* ---------------------------------------------------------------- supervivencia */
  def("shield", "s_palm", 9, 2, "Seguro|Insurance|Assurance|Seguro (blackjack)|Versicherung|Assicurazione||保险|보험|保険|Страховка|Ubezpieczenie", "Una vez por acto, un fallo de ronda no te cuesta provisión.|Once per act, a failed round costs no provision.|Une fois par acte, une manche ratée ne coûte pas de provision.|Uma vez por ato, uma rodada falhada não custa provisão.|Einmal pro Akt kostet eine verpatzte Runde keinen Proviant.|Una volta per atto, un round fallito non costa una provvista.||每幕一次，失败的回合不会消耗补给。|막마다 한 번, 실패한 라운드에서 식량을 잃지 않습니다.|1幕に1回、失敗したラウンドでプロビジョンを失わない。|Раз за акт проваленный раунд не отнимает запас.|Raz na akt oblana runda nie kosztuje zapasu.", { shieldAct: true });
  def("medkit", "s_pin", 5, 0, "Por cuenta de la casa|On the house|Offert par la maison|Por conta da casa|Auf Kosten des Hauses|Offerto dalla casa||赌场请客|하우스 서비스|店のおごり|За счёт заведения|Na koszt firmy", "Al empezar cada acto recuperas 1 provisión.|At the start of each act you recover 1 provision.|Au début de chaque acte, tu récupères 1 provision.|No início de cada ato você recupera 1 provisão.|Zu Beginn jedes Akts erhältst du 1 Proviant zurück.|All'inizio di ogni atto recuperi 1 provvista.||每一幕开始时恢复 1 份补给。|각 막이 시작될 때 식량 1개를 회복합니다.|各幕の開始時にプロビジョンを1つ回復する。|В начале каждого акта восстанавливается 1 запас.|Na początku każdego aktu odzyskujesz 1 zapas.", { actStart: run => { run.lives = Math.min(run.maxLives, run.lives + 1); } });
  def("heartperk", "s_pin", 8, 2, "Corazón de explorador|Explorer's heart|Cœur d'explorateur|Coração de explorador|Entdeckerherz|Cuore d'esploratore||探险家之心|탐험가의 심장|探検家の心|Сердце исследователя|Serce odkrywcy", "+1 provisión máxima mientras lo lleves (y llega llena al comprarlo).|+1 max provision while you hold it, restored on purchase.|+1 provision max tant que tu le gardes, récupérée à l'achat.|+1 provisão máxima enquanto o tiver, restaurada na compra.|+1 max. Proviant, solange du es hast, beim Kauf sofort aufgefüllt.|+1 provvista massima finché lo tieni, ripristinata all'acquisto.||持有期间最大补给 +1，购买时立即恢复。|보유하는 동안 최대 식량 +1, 구매 시 회복됩니다.|持っている間は最大プロビジョン+1、購入時に回復。|+1 к макс. запасу, пока он у тебя; восстанавливается при покупке.|+1 do maks. zapasów, dopóki go masz; uzupełniane przy zakupie.", { buy: run => { run.maxLives++; run.lives++; }, sell: run => { run.maxLives = Math.max(1, run.maxLives - 1); run.lives = Math.min(run.lives, run.maxLives); } });   // al venderlo se va la provision maxima (antes comprar, vender y recomprar la sumaba sin fin)
  def("talisman", "s_compass", 9, 2, "Amuleto del apostador|Gambler's charm|Porte-bonheur du parieur|Amuleto do apostador|Glücksbringer des Spielers|Portafortuna dello scommettitore||赌徒护身符|도박사의 부적|ギャンブラーのお守り|Талисман игрока|Amulet hazardzisty", "El primer reto de cada jefe pierde fuerza (nivel 1).|The first challenge of every boss drops to level 1.|Le premier défi de chaque boss retombe au niveau 1.|O primeiro desafio de cada chefe cai para o nível 1.|Die erste Herausforderung jedes Bosses fällt auf Stufe 1.|La prima sfida di ogni boss scende al livello 1.||每个首领的第一个挑战降至 1 级。|모든 보스의 첫 번째 도전이 1단계로 낮아집니다.|すべてのボスの最初のチャレンジがレベル1に下がる。|Первое испытание каждого босса снижается до 1-го уровня.|Pierwsze wyzwanie każdego bossa spada do poziomu 1.", { softenBoss: 1 });
  def("earplugs", "s_palm", 6, 1, "Tapones VIP|VIP earplugs|Bouchons VIP|Tampões VIP|VIP-Ohrstöpsel|Tappi VIP||VIP 耳塞|VIP 귀마개|VIP耳栓|VIP-беруши|Zatyczki VIP", "Inmune a los retos Silencio y Tormenta.|Immune to the Silence and Storm challenges.|Immunisé contre les défis Silence et Tempête.|Imune aos desafios Silêncio e Tempestade.|Immun gegen die Herausforderungen Stille und Gewitter.|Immune alle sfide Silenzio e Tempesta.||免疫“沉默”和“风暴”挑战。|침묵과 폭풍 도전에 면역이 됩니다.|静寂と嵐のチャレンジを無効化する。|Иммунитет к испытаниям «Тишина» и «Буря».|Odporność na wyzwania Cisza i Burza.", { immune: ["silence", "storm"] });


  /* ---------------------------------------------------------------- v0.11: mas ayudas contra retos de texto, mapa y puntero */
  def("shockabsorber", "s_palm", 6, 1, "Amortiguador de la casa|House shock absorber|Amortisseur de la maison|Amortecedor da casa|Stoßdämpfer des Hauses|Ammortizzatore della casa||赌场减震器|하우스 충격 흡수기|ハウスの衝撃吸収材|Амортизатор заведения|Amortyzator kasyna", "Terremoto, deriva y ruleta del mapa se reducen un 70 %.|Earthquake, drift and map spin are cut by 70%.|Séisme, dérive et rotation réduits de 70 %.|Terremoto, deriva e roleta reduzidos em 70%.|Beben, Abdrift und Kartendrehung um 70 % kleiner.|Terremoto, deriva e rotazione ridotti del 70%.||地震、漂移和地图旋转减弱 70%。|지진, 표류, 지도 회전이 70% 줄어듭니다.|地震・漂流・地図の回転が70%軽減される。|Землетрясение, дрейф и вращение карты ослаблены на 70%.|Trzęsienie, dryf i obrót mapy słabną o 70%.", { fx: { quakeMul: 0.3 } });
  def("umbrella", "s_palm", 4, 0, "Paraguas de cóctel|Cocktail umbrella|Parasol à cocktail|Guarda-chuva de coquetel|Cocktailschirmchen|Ombrellino da cocktail||鸡尾酒小伞|칵테일 우산|カクテルの傘|Коктейльный зонтик|Parasolka do drinka", "La lluvia y el humo tapan menos el mapa, y los rayos ya no te deslumbran.|Rain and smoke cover less of the map, and lightning no longer dazzles you.|La pluie et la fumée cachent moins la carte, et les éclairs ne t'éblouissent plus.|A chuva e o fumo tapam menos o mapa, e os raios já não te ofuscam.|Regen und Rauch verdecken weniger von der Karte, und Blitze blenden dich nicht mehr.|La pioggia e il fumo coprono meno la mappa, e i fulmini non ti abbagliano più.||雨和烟雾遮挡的地图区域变少，闪电也不会再晃到你的眼。|비와 연기가 지도를 덜 가리고, 번개가 더 이상 눈부시지 않습니다.|雨と煙が地図を覆う範囲が減り、稲妻にも目がくらまなくなる。|Дождь и дым закрывают меньше карты, а молнии больше не слепят.|Deszcz i dym zasłaniają mniej mapy, a błyskawice już cię nie oślepiają.", { fx: { rainMul: 0.35, cloudMul: 0.6, noFlash: true } });
  def("gamer", "s_pin", 6, 1, "Guante blanco|White glove|Gant blanc|Luva branca|Weißer Handschuh|Guanto bianco||白手套|흰 장갑|白手袋|Белая перчатка|Biała rękawiczka", "Sin retraso en el puntero y sin parpadeos.|No pointer lag and no blinking.|Pas de retard du pointeur ni de clignotement.|Sem atraso no ponteiro e sem piscar.|Keine Zeigerverzögerung und kein Blinken.|Nessun ritardo del puntatore e niente lampeggi.||指针不再延迟，也不再闪烁。|포인터 지연과 깜빡임이 없어집니다.|ポインターの遅れも点滅もなくなる。|Курсор не отстаёт и не мигает.|Kursor się nie spóźnia i nie miga.", { fx: { lagMul: 0.001, noBlink: true } });
  def("spareeye", "s_pin", 5, 1, "Monóculo de repuesto|Spare monocle|Monocle de secours|Monóculo reserva|Ersatzmonokel|Monocolo di riserva||备用单片眼镜|예비 외알 안경|予備のモノクル|Запасной монокль|Zapasowy monokl", "El cursor fantasma queda invisible un 60 % menos de tiempo.|The ghost cursor stays invisible 60% less time.|Le curseur fantôme reste invisible 60 % moins longtemps.|O cursor fantasma fica invisível 60% menos tempo.|Der Geisterzeiger bleibt 60 % kürzer unsichtbar.|Il cursore fantasma resta invisibile il 60% in meno.||幽灵光标隐形的时间减少 60%。|유령 커서가 보이지 않는 시간이 60% 줄어듭니다.|幽霊カーソルが見えない時間が60%短くなる。|Курсор-призрак невидим на 60% меньше времени.|Kursor widmo jest niewidoczny o 60% krócej.", { fx: { ghostMul: 0.4 } });

  /* ---------------------------------------------------------------- v0.33: contra los retos de CUARTA PARED */
  def("protector", "s_palm", 5, 0, "Protector de pantalla|Screen protector|Protection d'écran|Película protetora|Displayschutz|Pellicola protettiva||屏幕保护膜|화면 보호 필름|画面保護フィルム|Защитное стекло|Szkło ochronne", "Cristal roto y Pantalla sucia tapan un 60 % menos.|Cracked screen and Greasy screen cover 60% less.|Écran fissuré et Écran gras cachent 60 % de moins.|Tela rachada e Tela engordurada cobrem 60% menos.|Gesprungener und Fettiger Bildschirm verdecken 60 % weniger.|Schermo incrinato e Schermo unto coprono il 60% in meno.||屏幕碎裂和油腻的屏幕遮挡减少 60%。|깨진 화면과 기름 묻은 화면이 60% 덜 가립니다.|割れた画面と脂っぽい画面が覆う範囲が60%減る。|Треснувший и жирный экран закрывают на 60% меньше.|Pęknięty i tłusty ekran zasłaniają o 60% mniej.", { fx: { glassMul: 0.4 } });
  def("powerbank", "s_pin", 5, 0, "Batería externa|Power bank|Batterie externe|Power bank|Powerbank|Power bank||充电宝|보조 배터리|モバイルバッテリー|Пауэрбанк|Powerbank", "Inmune a Batería baja y +2 s por pregunta.|Immune to Low battery and +2 s per question.|Immunisé contre Batterie faible et +2 s par question.|Imune a Bateria fraca e +2 s por pergunta.|Immun gegen Akku schwach und +2 s pro Frage.|Immune a Batteria scarica e +2 s per domanda.||免疫“电量不足”，每题 +2 秒。|배터리 부족에 면역이 되고 문제당 +2초.|バッテリー残量低下を無効化し、1問につき+2秒。|Иммунитет к «Низкому заряду» и +2 с на вопрос.|Odporność na Słabą baterię i +2 s na pytanie.", { immune: ["battery"], round: x => { x.seconds += 2; } });
  def("taskmgr", "s_compass", 4, 0, "Administrador de tareas|Task manager|Gestionnaire des tâches|Gerenciador de tarefas|Task-Manager|Gestione attività||任务管理器|작업 관리자|タスクマネージャー|Диспетчер задач|Menedżer zadań", "Las ventanas de error se cierran solas en 1,5 s.|Error windows close by themselves after 1.5 s.|Les fenêtres d'erreur se ferment seules au bout de 1,5 s.|As janelas de erro fecham sozinhas após 1,5 s.|Fehlerfenster schließen sich nach 1,5 s von selbst.|Le finestre di errore si chiudono da sole dopo 1,5 s.||错误窗口会在 1.5 秒后自动关闭。|오류 창이 1.5초 후 저절로 닫힙니다.|エラーウィンドウが1.5秒で自動的に閉じる。|Окна ошибок закрываются сами через 1,5 с.|Okna błędów zamykają się same po 1,5 s.", { fx: { hangAuto: 1500 } });

  /* ---------------------------------------------------------------- LEGENDARIOS (solo en cofres de jefe) */
  def("philosopher", "s_pin", 14, 3, "Toque de Midas|Midas touch|Toucher de Midas|Toque de Midas|Midas-Berührung|Tocco di Mida||点金手|미다스의 손|ミダスの手|Прикосновение Мидаса|Dotyk Midasa", "Todos los doblones que ganes se duplican.|All doubloons you earn are doubled.|Tous les doublons que tu gagnes sont doublés.|Todos os dobrões que ganhar são dobrados.|Alle verdienten Dublonen werden verdoppelt.|Tutti i dobloni che guadagni sono raddoppiati.||你获得的所有金币翻倍。|획득하는 모든 도블론이 두 배가 됩니다.|獲得するダブロンがすべて2倍になる。|Все заработанные дублоны удваиваются.|Wszystkie zdobyte dublony są podwajane.", { coinX: 2 });
  def("oracle", "s_palm", 14, 3, "Oráculo|Oracle|Oracle|Oráculo|Orakel|Oracolo||神谕|신탁|神託|Оракул|Wyrocznia", "En cada pregunta, el país del lugar se ilumina en el mapa desde el primer segundo.|On every question, the place's country is lit up on the map from the first second.|À chaque question, le pays du lieu est illuminé sur la carte dès la première seconde.|Em cada pergunta, o país do lugar já vem iluminado no mapa desde o primeiro segundo.|Bei jeder Frage ist das Land des Ortes von der ersten Sekunde an auf der Karte beleuchtet.|A ogni domanda, il paese del luogo è illuminato sulla mappa fin dal primo secondo.||每题从第一秒起，地点所在国家就在地图上亮起。|매 문제의 첫 순간부터 장소의 국가가 지도에 표시됩니다.|毎問、最初からその場所の国が地図上で光っている。|На каждом вопросе страна места подсвечена на карте с первой секунды.|W każdym pytaniu kraj miejsca świeci na mapie od pierwszej sekundy.", { open: (api, o) => api.country(o) });
  def("masterkey", "s_peak", 14, 3, "Carta comodín|Wildcard|Carte joker|Carta coringa|Jokerkarte|Carta jolly||万能牌|와일드카드|ワイルドカード|Джокер|Dżoker", "El primer reto de cada ronda queda desactivado.|The first challenge of every round is disabled.|Le premier défi de chaque manche est désactivé.|O primeiro desafio de cada rodada fica desativado.|Die erste Herausforderung jeder Runde entfällt.|La prima sfida di ogni round è disattivata.||每回合的第一个挑战会被禁用。|모든 라운드의 첫 번째 도전이 비활성화됩니다.|毎ラウンド、最初のチャレンジが無効になる。|Первое испытание каждого раунда отключено.|Pierwsze wyzwanie każdej rundy jest wyłączone.", { skipFirst: 1 });

  A.RELICS = P;
  A.RELIC_IDS = Object.keys(P);
})(window.AIQ);
