/*
 * Geolite - catalogo de PERKS de la Aventura (v0.10). Ninguno multiplica ni suma puntos: la puntuacion es solo tu precision.
 * Los perks ayudan a resolver los RETOS del crupier (letras temblorosas, mapa borroso, apagon, fronteras falsas, continentes movidos...),
 * mejoran tu puntero, dan pistas, tiempo, supervivencia o doblones. Cada perk es una carta de poker con palo geografico.
 *
 *   fx {..}         mitigaciones de retos y mejoras del puntero (ver A.chal.fx en js/challenges.js)
 *   round(x,run)    al empezar la ronda (x.seconds)                open(api,o,run)  pistas gratis al empezar cada pregunta (api.laterHalf: a mitad de tiempo)
 *   clear(x,run)    al superar una ronda (x.coins)                 shop(x,run)      tienda (x.price -, x.freeReroll)
 *   post(c,run)     tras puntuar: SOLO doblones (c.coins)          flags: immune[], softenBoss, coinX, toolBonus, interest, shieldAct, sonarErr, compass16, spy, skipFirst
 * Texto: n = nombre y d = descripcion en es|en|fr|pt|de|it|es-419|zh|ko|ja|ru|pl (es-419 vacio = espanol).
 */
window.AIQ = window.AIQ || {};
(function (A) {
  const L6 = A.L6;
  const P = {};
  const def = (id, suit, cost, r, n, d, hooks = {}) => { P[id] = { id, ico: id, suit, cost, r, n: L6(n), d: L6(d), ...hooks }; };
  const seeded = (run, tag) => A.rng(`${run.seed}:${tag}:${run.act}:${run.round}:${run.qi}:${run.qTotal || 0}`)();

  /* ---------------------------------------------------------------- contra retos de TEXTO */
  def("steadyhand", "s_compass", 4, 0, "Mano de crupier|Dealer's hand|Main de croupier|Mão de crupiê|Krupierhand|Mano da croupier||荷官之手|딜러의 손|ディーラーの手|Рука крупье|Ręka krupiera", "Las letras que tiemblan, el pulso tembloroso y el mareo del puntero bajan un 75 %.|Shaking letters, a shaky hand and a dizzy pointer drop by 75%.|Les lettres qui tremblent, la main tremblante et le vertige du pointeur baissent de 75 %.|As letras que tremem, a mão trêmula e a tontura do ponteiro caem 75 %.|Zitternde Buchstaben, zittrige Hand und Zeiger-Schwindel sinken um 75 %.|Le lettere che tremano, la mano tremante e il capogiro del puntatore calano del 75 %.||颤抖的字母、手抖和指针眩晕减少 75%。|떨리는 글자, 떨리는 손, 포인터 어지러움이 75% 줄어듭니다.|震える文字、手の震え、ポインターのめまいが75%減る。|Дрожь букв, дрожащая рука и головокружение курсора снижаются на 75%.|Drżące litery, drżąca ręka i zawrót głowy kursora słabną o 75%.", { fx: { shakeMul: 0.25 } });
  def("dictionary", "s_peak", 5, 0, "Chuleta de crupier|Dealer's cheat sheet|Antisèche du croupier|Cola do crupiê|Spickzettel des Croupiers|Bigliettino del croupier||荷官的小抄|딜러의 커닝 페이퍼|ディーラーのカンニングペーパー|Шпаргалка крупье|Ściąga krupiera", "Las letras borradas vuelven una a una.|Faded letters come back one by one.|Les lettres effacées reviennent une à une.|As letras apagadas voltam uma a uma.|Verblasste Buchstaben kehren einzeln zurück.|Le lettere sbiadite tornano una a una.||褪色的字母会一个个恢复。|바랜 글자가 하나씩 돌아옵니다.|かすれた文字が一つずつ戻ってくる。|Выцветшие буквы возвращаются одна за другой.|Wyblakłe litery wracają jedna po drugiej.", { fx: { missingRate: 0.9 } });
  def("handmirror", "s_compass", 4, 0, "Espejo del ilusionista|Conjurer's mirror|Miroir de l'illusionniste|Espelho do ilusionista|Spiegel des Illusionisten|Specchio dell'illusionista||魔术师之镜|마술사의 거울|奇術師の鏡|Зеркало фокусника|Lustro iluzjonisty", "Nombres en espejo o del revés se leen normal, y el mapa en espejo y el puntero invertido vuelven a su sitio.|Mirrored or upside-down names read normally, and a mirrored map or reversed pointer is set right.|Les noms en miroir ou à l'envers se lisent normalement, et la carte miroir comme le pointeur inversé reviennent à la normale.|Nomes espelhados ou de cabeça para baixo ficam normais, e o mapa espelhado e o ponteiro invertido voltam ao lugar.|Gespiegelte oder kopfstehende Namen sind normal lesbar, Spiegelkarte und umgekehrter Zeiger werden korrigiert.|I nomi a specchio o capovolti si leggono normali, e la mappa a specchio e il puntatore invertito tornano a posto.||镜像或倒置的名字恢复正常，镜像地图和反向指针也会复原。|거울상이나 뒤집힌 이름이 정상으로 보이고, 거울 지도와 반전된 포인터도 제자리로 돌아옵니다.|鏡文字や逆さまの名前が普通に読め、鏡の地図と逆操作のポインターも元に戻る。|Зеркальные и перевёрнутые названия читаются нормально, а зеркальная карта и обратный курсор возвращаются на место.|Lustrzane i odwrócone nazwy czytasz normalnie, a lustrzana mapa i odwrócony kursor wracają do normy.", { fx: { unmirror: true } });
  def("spectacles", "s_palm", 6, 1, "Visera de crupier|Dealer's eyeshade|Visière de croupier|Viseira de crupiê|Krupier-Augenschirm|Visiera da croupier||荷官的遮光帽|딜러의 챙모자|ディーラーのサンバイザー|Козырёк крупье|Daszek krupiera", "Los retos de texto (letras que tiemblan, borradas, cambiadas, runas…) tienen la mitad de efecto.|Text challenges (shaking, faded or swapped letters, runes…) have half the effect.|Les défis de texte (lettres qui tremblent, effacées, échangées, runes…) ont moitié moins d'effet.|Os desafios de texto (letras que tremem, apagadas, trocadas, runas…) têm metade do efeito.|Text-Herausforderungen (zitternde, verblasste, vertauschte Buchstaben, Runen …) wirken nur halb so stark.|Le sfide di testo (lettere che tremano, sbiadite, scambiate, rune…) hanno metà dell'effetto.||文字类挑战（颤抖、褪色、错位的字母、符文……）效果减半。|글자 도전(떨림, 바램, 뒤바뀐 글자, 룬…)의 효과가 절반이 됩니다.|文字系チャレンジ（震え、かすれ、入れ替わり、ルーン…）の効果が半減する。|Текстовые испытания (дрожащие, выцветшие, переставленные буквы, руны…) действуют вдвое слабее.|Wyzwania tekstowe (drżące, wyblakłe, zamienione litery, runy…) działają o połowę słabiej.", { fx: { textMul: 0.5 } });

  /* ---------------------------------------------------------------- contra retos del MAPA */
  def("miner", "s_peak", 5, 0, "Foco del vigilante|Pit boss's spotlight|Projecteur du chef de table|Holofote do supervisor|Scheinwerfer des Pitbosses|Faro del capotavolo||场务经理的聚光灯|플로어 매니저의 스포트라이트|ピットボスのスポットライト|Прожектор пит-босса|Reflektor szefa sali", "Tu haz de luz es casi el doble de ancho en un apagón.|Your light beam is almost twice as wide in a blackout.|Ton faisceau est presque deux fois plus large en cas de panne.|Seu feixe de luz é quase o dobro num apagão.|Dein Lichtkegel ist bei Stromausfall fast doppelt so breit.|Il tuo fascio di luce è quasi il doppio in un blackout.||停电时你的光束宽度几乎翻倍。|정전 중 빛줄기가 거의 두 배로 넓어집니다.|停電中、光の範囲がほぼ2倍に広がる。|При отключении света твой луч почти вдвое шире.|Podczas awarii prądu twój snop światła jest prawie dwa razy szerszy.", { fx: { darkR: 1.9, halo: true } });
  def("lens", "s_compass", 6, 1, "Lupa del tasador|Appraiser's loupe|Loupe de l'expert|Lupa do avaliador|Lupe des Schätzers|Lente del perito||鉴定师的放大镜|감정사의 확대경|鑑定士のルーペ|Лупа оценщика|Lupa rzeczoznawcy", "Un círculo nítido sigue a tu puntero en un mapa borroso.|A sharp circle follows your pointer on a blurry map.|Un cercle net suit ton pointeur sur une carte floue.|Um círculo nítido acompanha o ponteiro num mapa desfocado.|Ein scharfer Kreis folgt deinem Zeiger auf unscharfer Karte.|Un cerchio nitido segue il puntatore su una mappa sfocata.||在模糊的地图上，一个清晰的圆圈跟随你的指针。|흐릿한 지도에서 선명한 원이 포인터를 따라다닙니다.|ぼやけた地図で、くっきりした円がポインターについてくる。|На размытой карте за курсором следует чёткий круг.|Na rozmytej mapie za kursorem podąża ostre koło.", { fx: { lensR: 120 } });
  def("divingmask", "s_palm", 4, 0, "Gafas de sol de crupier|Dealer's sunglasses|Lunettes de soleil du croupier|Óculos de sol do crupiê|Krupier-Sonnenbrille|Occhiali da sole del croupier|Lentes de sol de crupier|荷官的墨镜|딜러의 선글라스|ディーラーのサングラス|Очки крупье|Okulary krupiera", "El desenfoque del mapa y del puntero baja un 80 %.|Map and pointer blur drop by 80%.|Le flou de la carte et du pointeur baisse de 80 %.|O desfoque do mapa e do ponteiro cai 80%.|Die Unschärfe von Karte und Zeiger sinkt um 80 %.|La sfocatura di mappa e puntatore scende dell'80%.||地图和指针的模糊减少 80%。|지도와 포인터의 흐림이 80% 줄어듭니다.|地図とポインターのぼやけが80%減る。|Размытие карты и курсора снижается на 80%.|Rozmycie mapy i kursora spada o 80%.", { fx: { blurMul: 0.2 } });
  def("customs", "s_pin", 7, 1, "Sello de la casa|House stamp|Cachet de la maison|Carimbo da casa|Stempel des Hauses|Timbro della casa||赌场印章|하우스 도장|ハウスの印章|Печать заведения|Pieczątka kasyna", "Ves las fronteras verdaderas en un círculo junto a tu puntero.|You see the true borders in a circle around your pointer.|Tu vois les vraies frontières dans un cercle autour de ton pointeur.|Você vê as fronteiras verdadeiras num círculo ao redor do ponteiro.|Du siehst die echten Grenzen in einem Kreis um deinen Zeiger.|Vedi i veri confini in un cerchio attorno al puntatore.||你能在指针周围的圆圈中看到真实边界。|포인터 주변 원 안에서 진짜 국경이 보입니다.|ポインターの周りの円の中に本当の国境が見える。|В круге вокруг курсора видны настоящие границы.|W kole wokół kursora widzisz prawdziwe granice.", { fx: { trueR: 110, peekR: 110 } });
  def("plates", "s_palm", 8, 2, "Nivel de crupier|Dealer's level|Niveau du croupier|Nível do crupiê|Wasserwaage des Croupiers|Livella del croupier||荷官的水平仪|딜러의 수평계|ディーラーの水準器|Уровень крупье|Poziomica krupiera", "Pangea y los continentes movidos quedan más cerca de su sitio real (60 % menos de desplazamiento).|Pangaea and moved continents end up closer to their real place (60% less displacement).|La Pangée et les continents déplacés restent plus près de leur vraie place (60 % de décalage en moins).|A Pangeia e os continentes movidos ficam mais perto do lugar real (60 % menos de deslocamento).|Pangaea und verschobene Kontinente liegen näher an ihrem echten Platz (60 % weniger Verschiebung).|La Pangea e i continenti spostati restano più vicini al loro posto reale (60 % di spostamento in meno).||盘古大陆和移位的大洲会更接近真实位置（位移减少 60%）。|판게아와 이동한 대륙이 실제 위치에 더 가까워집니다(이동량 60% 감소).|パンゲアや移動した大陸が本来の位置に近づく（ずれが60%減少）。|Пангея и сдвинутые континенты оказываются ближе к реальному месту (смещение на 60% меньше).|Pangea i przesunięte kontynenty lądują bliżej swojego miejsca (o 60% mniejsze przesunięcie).", { fx: { plateMul: 0.4 } });
  def("weathervane", "s_compass", 6, 1, "Ancla de mesa|Table anchor|Ancre de table|Âncora de mesa|Tischanker|Ancora da tavolo||牌桌之锚|테이블 닻|テーブルの錨|Якорь стола|Kotwica stołu", "El viento te empuja la mitad.|The wind pushes you only half as hard.|Le vent te pousse deux fois moins fort.|O vento te empurra só a metade.|Der Wind schiebt dich nur halb so stark.|Il vento ti spinge la metà.||风对你的推力减半。|바람이 절반의 힘으로만 밀어냅니다.|風に押される力が半分になる。|Ветер толкает тебя вдвое слабее.|Wiatr spycha cię o połowę słabiej.", { fx: { windMul: 0.5 } });

  /* ---------------------------------------------------------------- puntero */

  /* ---------------------------------------------------------------- pistas gratis y herramientas */
  def("sextant", "s_palm", 5, 0, "Soplo del crupier|Dealer's tip-off|Tuyau du croupier|Dica do crupiê|Tipp vom Croupier|Soffiata del croupier||荷官的暗示|딜러의 귀띔|ディーラーの耳打ち|Подсказка крупье|Cynk od krupiera", "Al empezar cada pregunta se te dice en qué continente está.|At the start of every question you're told which continent it is on.|Au début de chaque question, on te dit sur quel continent elle se trouve.|No início de cada pergunta dizem-te em que continente fica.|Zu Beginn jeder Frage erfährst du, auf welchem Kontinent es liegt.|All'inizio di ogni domanda ti dicono in quale continente si trova.||每题开始时都会告诉你它在哪个大洲。|매 문제 시작 시 어느 대륙인지 알려줍니다.|毎問の最初に、どの大陸にあるか教えてもらえる。|В начале каждого вопроса тебе говорят, на каком он континенте.|Na początku każdego pytania dowiadujesz się, na jakim to kontynencie.", { open: (api, o) => api.note(api.continent(o), "sextant") });
  def("atlasbook", "s_peak", 9, 2, "Chuleta de bolsillo|Pocket cheat sheet|Antisèche de poche|Cola de bolso|Taschenspickzettel|Bigliettino tascabile||口袋小抄|주머니 커닝 페이퍼|ポケットのカンペ|Карманная шпаргалка|Ściąga w kieszeni", "En cada pregunta, con 5 s restantes se ilumina en el mapa el país del lugar.|On every question, with 5 s left the place's country lights up on the map.|À chaque question, avec 5 s restantes, le pays du lieu s'illumine sur la carte.|Em cada pergunta, com 5 s restantes o país do lugar se ilumina no mapa.|Bei jeder Frage leuchtet bei 5 s Restzeit das Land des Ortes auf der Karte auf.|A ogni domanda, con 5 s rimasti il paese del luogo si illumina sulla mappa.||每题剩余 5 秒时，地点所在国家会在地图上亮起。|매 문제에서 5초가 남으면 장소의 국가가 지도에 표시됩니다.|毎問、残り5秒でその場所の国が地図上で光る。|На каждом вопросе за 5 с до конца страна места подсвечивается на карте.|W każdym pytaniu na 5 s przed końcem kraj miejsca podświetla się na mapie.", { open: (api, o) => api.later(5, () => api.country(o)) });
  def("almanac", "s_peak", 6, 1, "Libro de la casa|House ledger|Registre de la maison|Livro da casa|Hausregister|Registro della casa||赌场账簿|하우스 장부|ハウスの帳簿|Книга заведения|Księga kasyna", "En cada pregunta, lees gratis la nota de campo del lugar.|On every question, read the place's field note for free.|À chaque question, tu lis gratuitement la note de terrain du lieu.|Em cada pergunta, você lê grátis a nota de campo do lugar.|Bei jeder Frage liest du die Feldnotiz des Ortes gratis.|A ogni domanda, leggi gratis la nota di campo del luogo.||每题都可以免费阅读该地点的野外笔记。|매 문제에서 장소의 야외 일지를 무료로 읽을 수 있습니다.|毎問、その場所のフィールドノートを無料で読める。|На каждом вопросе полевая заметка о месте доступна бесплатно.|W każdym pytaniu czytasz notatkę terenową za darmo.", { open: (api, o) => api.fact(o) });
  def("sonarplus", "s_compass", 6, 1, "Sonar trucado|Loaded sonar|Sonar truqué|Sonar viciado|Frisiertes Sonar|Sonar truccato||加料声呐|조작된 소나|イカサマソナー|Заряженный сонар|Podrasowany sonar", "El Sonar solo se equivoca un ±2 % (en vez de ±6 %).|Sonar is off by only ±2% (instead of ±6%).|Le sonar ne se trompe que de ±2 % (au lieu de ±6 %).|O Sonar erra só ±2% (em vez de ±6%).|Das Sonar irrt nur um ±2 % (statt ±6 %).|Il Sonar sbaglia solo del ±2% (invece del ±6%).||声呐误差仅 ±2%（而非 ±6%）。|소나 오차가 ±6% 대신 ±2%로 줄어듭니다.|ソナーの誤差が±6%ではなく±2%になる。|Погрешность сонара всего ±2% (вместо ±6%).|Sonar myli się tylko o ±2% (zamiast ±6%).", { sonarErr: 0.02 });
  def("compass16", "s_peak", 6, 1, "Ruleta de 16 rumbos|16-point roulette|Roulette à 16 directions|Roleta de 16 rumos|16-Feld-Roulette|Roulette a 16 direzioni||十六方位轮盘|16방위 룰렛|16方位ルーレット|16-румбовая рулетка|Ruletka na 16 pól", "La Brújula señala 16 direcciones en vez de 8.|The Compass points in 16 directions instead of 8.|La boussole indique 16 directions au lieu de 8.|A Bússola aponta 16 direções em vez de 8.|Der Kompass zeigt 16 statt 8 Richtungen.|La Bussola indica 16 direzioni invece di 8.||指南针指向 16 个方位，而非 8 个。|나침반이 8방향 대신 16방향을 가리킵니다.|コンパスが8方位ではなく16方位を示す。|Компас показывает 16 направлений вместо 8.|Kompas wskazuje 16 kierunków zamiast 8.", { compass16: true });
  def("glass", "s_palm", 8, 2, "Catalejo del apostador|Gambler's spyglass|Longue-vue du parieur|Luneta do apostador|Fernrohr des Spielers|Cannocchiale dello scommettitore||赌徒的望远镜|도박사의 망원경|ギャンブラーの望遠鏡|Подзорная труба игрока|Luneta hazardzisty", "+1 carga en todas tus herramientas.|+1 charge on all your tools.|+1 charge sur tous tes outils.|+1 carga em todas as suas ferramentas.|+1 Ladung für alle Werkzeuge.|+1 carica su tutti i tuoi strumenti.||所有工具 +1 使用次数。|모든 도구에 충전 +1.|すべての道具にチャージ+1。|+1 заряд ко всем твоим инструментам.|+1 ładunek do wszystkich narzędzi.", { toolBonus: 1 });
  def("spyhole", "s_pin", 5, 1, "Ojo en el cielo|Eye in the sky|Œil dans le ciel|Olho no céu|Auge im Himmel|Occhio nel cielo||天空之眼|하늘의 눈|天の目|Всевидящее око|Oko w niebie", "El Campamento te muestra los retos de las 2 próximas rondas.|Camp shows you the challenges of the next 2 rounds.|Le camp te montre les défis des 2 prochaines manches.|O Acampamento mostra os desafios das 2 próximas rodadas.|Das Lager zeigt die Herausforderungen der nächsten 2 Runden.|Il Campo mostra le sfide dei prossimi 2 round.||营地会显示接下来 2 个回合的挑战。|캠프에서 다음 2라운드의 도전을 보여줍니다.|キャンプで次の2ラウンドのチャレンジが分かる。|Лагерь показывает испытания следующих 2 раундов.|Obóz pokazuje wyzwania z 2 następnych rund.", { spy: 1 });

  /* ---------------------------------------------------------------- tiempo */
  def("boots", "s_palm", 4, 0, "Cortesía de la casa|House comp|Cadeau de la maison|Cortesia da casa|Kulanz des Hauses|Omaggio della casa||赌场赠品|하우스 서비스|ハウスのサービス|Подарок заведения|Prezent od kasyna", "+3 s por pregunta.|+3 s per question.|+3 s par question.|+3 s por pergunta.|+3 s pro Frage.|+3 s per domanda.||每题 +3 秒。|문제당 +3초.|1問につき+3秒。|+3 с на вопрос.|+3 s na pytanie.", { round: x => { x.seconds += 3; } });

  /* ---------------------------------------------------------------- economia (doblones y tienda) */
  def("purse", "s_pin", 4, 0, "Ficha de propina|Tip chip|Jeton de pourboire|Ficha de gorjeta|Trinkgeld-Chip|Fiche di mancia||小费筹码|팁 칩|チップのチップ|Фишка на чай|Żeton na napiwek", "+1 doblón por cada respuesta con 750 puntos de precisión o más (máximo 1000).|+1 doubloon for every answer with 750 accuracy points or more (max 1000).|+1 doublon pour chaque réponse avec 750 points de précision ou plus (maximum 1000).|+1 dobrão por cada resposta com 750 pontos de precisão ou mais (máximo 1000).|+1 Dublone für jede Antwort mit 750 Genauigkeitspunkten oder mehr (maximal 1000).|+1 dobbline per ogni risposta con 750 punti di precisione o più (massimo 1000).||每个精准度达到 750 分以上的回答 +1 金币（满分 1000）。|정확도 750점 이상인 답마다 도블론 +1 (최대 1000).|精度750ポイント以上の回答ごとに+1ダブロン（最大1000）。|+1 дублон за каждый ответ с точностью 750 очков и выше (макс. 1000).|+1 dublon za każdą odpowiedź z 750 lub więcej punktami celności (maks. 1000).", { post: c => (c.dist >= 750 ? (c.coins += 1, "+1") : null) });
  def("hoard", "s_pin", 6, 1, "Cajero|Cashier|Caissier|Caixa|Kassierer|Cassiere||出纳员|캐셔|キャッシャー|Кассир|Kasjer", "+2 doblones al superar una ronda.|+2 doubloons when you clear a round.|+2 doublons en réussissant une manche.|+2 dobrões ao superar uma rodada.|+2 Dublonen beim Bestehen einer Runde.|+2 dobloni al superare un round.||通过一回合 +2 金币。|라운드를 클리어하면 도블론 +2.|ラウンドをクリアすると+2ダブロン。|+2 дублона за прохождение раунда.|+2 dublony za zaliczenie rundy.", { clear: x => { x.coins += 2; return "+2"; } });
  def("coupon", "s_pin", 5, 0, "Vale de la casa|House voucher|Bon de la maison|Vale da casa|Hausgutschein|Buono della casa|Cupón de la casa|赌场优惠券|하우스 쿠폰|ハウスの割引券|Ваучер заведения|Bon kasyna", "Todo cuesta 1 doblón menos en la tienda.|Everything costs 1 doubloon less in the shop.|Tout coûte 1 doublon de moins à la boutique.|Tudo custa 1 dobrão a menos na loja.|Alles kostet 1 Dublone weniger im Laden.|Tutto costa 1 doblone in meno al negozio.||商店里所有东西便宜 1 金币。|상점의 모든 물건이 도블론 1개 저렴해집니다.|ショップの品がすべて1ダブロン安くなる。|В лавке всё на 1 дублон дешевле.|W sklepie wszystko kosztuje 1 dublon mniej.", { shop: x => { x.price -= 1; } });
  def("banker", "s_pin", 8, 2, "Banquero|Banker|Banquier|Banqueiro|Bankier|Banchiere||银行家|은행가|銀行家|Банкир|Bankier", "El interés de fin de ronda (1 doblón por cada 10 que tengas) sube su tope de +2 a +4.|The end-of-round interest (1 doubloon per 10 you hold) rises from a cap of +2 to +4.|L'intérêt de fin de manche (1 doublon pour 10 en poche) passe d'un plafond de +2 à +4.|Os juros no fim da ronda (1 dobrão por cada 10 que tens) sobem o limite de +2 para +4.|Die Zinsen am Rundenende (1 Dublone pro 10 im Besitz) steigen von maximal +2 auf +4.|Gli interessi a fine round (1 dobbline ogni 10 che hai) salgono dal tetto di +2 a +4.||回合结束时的利息（每持有 10 枚得 1 枚）上限从 +2 提高到 +4。|라운드 종료 이자(보유 10개당 1개)의 상한이 +2에서 +4로 오릅니다.|ラウンド終了時の利息（10枚ごとに1枚）の上限が+2から+4に上がる。|Проценты в конце раунда (1 дублон за каждые 10) растут с лимита +2 до +4.|Odsetki na koniec rundy (1 dublon za każde 10) rosną z limitu +2 do +4.", { interest: 4 });

  /* ---------------------------------------------------------------- supervivencia */
  def("shield", "s_palm", 9, 2, "Seguro|Insurance|Assurance|Seguro (blackjack)|Versicherung|Assicurazione||保险|보험|保険|Страховка|Ubezpieczenie", "Una vez por acto, un fallo de ronda no te cuesta provisión.|Once per act, a failed round costs no provision.|Une fois par acte, une manche ratée ne coûte pas de provision.|Uma vez por ato, uma rodada falhada não custa provisão.|Einmal pro Akt kostet eine verpatzte Runde keinen Proviant.|Una volta per atto, un round fallito non costa una provvista.||每幕一次，失败的回合不会消耗补给。|막마다 한 번, 실패한 라운드에서 식량을 잃지 않습니다.|1幕に1回、失敗したラウンドでプロビジョンを失わない。|Раз за акт проваленный раунд не отнимает запас.|Raz na akt oblana runda nie kosztuje zapasu.", { shieldAct: true });
  def("medkit", "s_pin", 5, 0, "Por cuenta de la casa|On the house|Offert par la maison|Por conta da casa|Auf Kosten des Hauses|Offerto dalla casa||赌场请客|하우스 서비스|店のおごり|За счёт заведения|Na koszt firmy", "Al empezar cada acto recuperas 1 provisión.|At the start of each act you recover 1 provision.|Au début de chaque acte, tu récupères 1 provision.|No início de cada ato você recupera 1 provisão.|Zu Beginn jedes Akts erhältst du 1 Proviant zurück.|All'inizio di ogni atto recuperi 1 provvista.||每一幕开始时恢复 1 份补给。|각 막이 시작될 때 식량 1개를 회복합니다.|各幕の開始時にプロビジョンを1つ回復する。|В начале каждого акта восстанавливается 1 запас.|Na początku każdego aktu odzyskujesz 1 zapas.", { actStart: run => { run.lives = Math.min(run.maxLives, run.lives + 1); } });
  def("heartperk", "s_pin", 8, 2, "Corazón de explorador|Explorer's heart|Cœur d'explorateur|Coração de explorador|Entdeckerherz|Cuore d'esploratore||探险家之心|탐험가의 심장|探検家の心|Сердце исследователя|Serce odkrywcy", "+1 provisión máxima y la recuperas al comprarlo.|+1 max provision, restored on purchase.|+1 provision max, récupérée à l'achat.|+1 provisão máxima, restaurada na compra.|+1 max. Proviant, sofort aufgefüllt.|+1 provvista massima, ripristinata all'acquisto.||最大补给 +1，购买时立即恢复。|최대 식량 +1, 구매 시 회복됩니다.|最大プロビジョン+1、購入時に回復。|+1 к макс. запасу, восстанавливается при покупке.|+1 do maks. zapasów, uzupełniane przy zakupie.", { buy: run => { run.maxLives++; run.lives++; } });
  def("talisman", "s_compass", 9, 2, "Amuleto del apostador|Gambler's charm|Porte-bonheur du parieur|Amuleto do apostador|Glücksbringer des Spielers|Portafortuna dello scommettitore||赌徒护身符|도박사의 부적|ギャンブラーのお守り|Талисман игрока|Amulet hazardzisty", "El primer reto de cada jefe pierde fuerza (nivel 1).|The first challenge of every boss drops to level 1.|Le premier défi de chaque boss retombe au niveau 1.|O primeiro desafio de cada chefe cai para o nível 1.|Die erste Herausforderung jedes Bosses fällt auf Stufe 1.|La prima sfida di ogni boss scende al livello 1.||每个首领的第一个挑战降至 1 级。|모든 보스의 첫 번째 도전이 1단계로 낮아집니다.|すべてのボスの最初のチャレンジがレベル1に下がる。|Первое испытание каждого босса снижается до 1-го уровня.|Pierwsze wyzwanie każdego bossa spada do poziomu 1.", { softenBoss: 1 });
  def("earplugs", "s_palm", 6, 1, "Tapones VIP|VIP earplugs|Bouchons VIP|Tampões VIP|VIP-Ohrstöpsel|Tappi VIP||VIP 耳塞|VIP 귀마개|VIP耳栓|VIP-беруши|Zatyczki VIP", "Inmune a los retos Silencio y Tormenta.|Immune to the Silence and Storm challenges.|Immunisé contre les défis Silence et Tempête.|Imune aos desafios Silêncio e Tempestade.|Immun gegen die Herausforderungen Stille und Gewitter.|Immune alle sfide Silenzio e Tempesta.||免疫“沉默”和“风暴”挑战。|침묵과 폭풍 도전에 면역이 됩니다.|静寂と嵐のチャレンジを無効化する。|Иммунитет к испытаниям «Тишина» и «Буря».|Odporność na wyzwania Cisza i Burza.", { immune: ["silence", "storm"] });


  /* ---------------------------------------------------------------- v0.11: mas ayudas contra retos de texto, mapa y puntero */
  def("shockabsorber", "s_palm", 6, 1, "Amortiguador de la casa|House shock absorber|Amortisseur de la maison|Amortecedor da casa|Stoßdämpfer des Hauses|Ammortizzatore della casa||赌场减震器|하우스 충격 흡수기|ハウスの衝撃吸収材|Амортизатор заведения|Amortyzator kasyna", "Terremoto, deriva y ruleta del mapa se reducen un 70 %.|Earthquake, drift and map spin are cut by 70%.|Séisme, dérive et rotation réduits de 70 %.|Terremoto, deriva e roleta reduzidos em 70%.|Beben, Abdrift und Kartendrehung um 70 % kleiner.|Terremoto, deriva e rotazione ridotti del 70%.||地震、漂移和地图旋转减弱 70%。|지진, 표류, 지도 회전이 70% 줄어듭니다.|地震・漂流・地図の回転が70%軽減される。|Землетрясение, дрейф и вращение карты ослаблены на 70%.|Trzęsienie, dryf i obrót mapy słabną o 70%.", { fx: { quakeMul: 0.3 } });
  def("umbrella", "s_palm", 4, 0, "Paraguas de cóctel|Cocktail umbrella|Parasol à cocktail|Guarda-chuva de coquetel|Cocktailschirmchen|Ombrellino da cocktail||鸡尾酒小伞|칵테일 우산|カクテルの傘|Коктейльный зонтик|Parasolka do drinka", "La lluvia y el humo tapan menos el mapa.|Rain and smoke cover less of the map.|La pluie et la fumée cachent moins la carte.|A chuva e o fumo tapam menos o mapa.|Regen und Rauch verdecken weniger von der Karte.|La pioggia e il fumo coprono meno la mappa.||雨和烟雾遮挡的地图区域变少。|비와 연기가 지도를 덜 가립니다.|雨と煙が地図を覆う範囲が減る。|Дождь и дым закрывают меньше карты.|Deszcz i dym zasłaniają mniej mapy.", { fx: { rainMul: 0.35, cloudMul: 0.6 } });
  def("gamer", "s_pin", 6, 1, "Guante blanco|White glove|Gant blanc|Luva branca|Weißer Handschuh|Guanto bianco||白手套|흰 장갑|白手袋|Белая перчатка|Biała rękawiczka", "Sin retraso en el puntero y sin parpadeos.|No pointer lag and no blinking.|Pas de retard du pointeur ni de clignotement.|Sem atraso no ponteiro e sem piscar.|Keine Zeigerverzögerung und kein Blinken.|Nessun ritardo del puntatore e niente lampeggi.||指针不再延迟，也不再闪烁。|포인터 지연과 깜빡임이 없어집니다.|ポインターの遅れも点滅もなくなる。|Курсор не отстаёт и не мигает.|Kursor się nie spóźnia i nie miga.", { fx: { lagMul: 0.001, noBlink: true } });
  def("spareeye", "s_pin", 5, 1, "Monóculo de repuesto|Spare monocle|Monocle de secours|Monóculo reserva|Ersatzmonokel|Monocolo di riserva||备用单片眼镜|예비 외알 안경|予備のモノクル|Запасной монокль|Zapasowy monokl", "El cursor fantasma queda invisible un 60% menos de tiempo.|The ghost cursor stays invisible 60% less time.|Le curseur fantôme reste invisible 60 % moins longtemps.|O cursor fantasma fica invisível 60% menos tempo.|Der Geisterzeiger bleibt 60 % kürzer unsichtbar.|Il cursore fantasma resta invisibile il 60% in meno.||幽灵光标隐形的时间减少 60%。|유령 커서가 보이지 않는 시간이 60% 줄어듭니다.|幽霊カーソルが見えない時間が60%短くなる。|Курсор-призрак невидим на 60% меньше времени.|Kursor widmo jest niewidoczny o 60% krócej.", { fx: { ghostMul: 0.4 } });

  /* ---------------------------------------------------------------- v0.33: contra los retos de CUARTA PARED */
  def("protector", "s_palm", 5, 0, "Protector de pantalla|Screen protector|Protection d'écran|Película protetora|Displayschutz|Pellicola protettiva||屏幕保护膜|화면 보호 필름|画面保護フィルム|Защитное стекло|Szkło ochronne", "Cristal roto y Pantalla sucia tapan un 60 % menos.|Cracked screen and Greasy screen cover 60% less.|Écran fissuré et Écran gras cachent 60 % de moins.|Tela rachada e Tela engordurada cobrem 60% menos.|Gesprungener und Fettiger Bildschirm verdecken 60 % weniger.|Schermo incrinato e Schermo unto coprono il 60% in meno.||屏幕碎裂和油腻的屏幕遮挡减少 60%。|깨진 화면과 기름 묻은 화면이 60% 덜 가립니다.|割れた画面と脂っぽい画面が覆う範囲が60%減る。|Треснувший и жирный экран закрывают на 60% меньше.|Pęknięty i tłusty ekran zasłaniają o 60% mniej.", { fx: { glassMul: 0.4 } });
  def("powerbank", "s_pin", 5, 0, "Batería externa|Power bank|Batterie externe|Power bank|Powerbank|Power bank||充电宝|보조 배터리|モバイルバッテリー|Пауэрбанк|Powerbank", "Inmune a Batería baja y +2 s por pregunta.|Immune to Low battery and +2 s per question.|Immunisé contre Batterie faible et +2 s par question.|Imune a Bateria fraca e +2 s por pergunta.|Immun gegen Akku schwach und +2 s pro Frage.|Immune a Batteria scarica e +2 s per domanda.||免疫“电量不足”，每题 +2 秒。|배터리 부족에 면역이 되고 문제당 +2초.|バッテリー残量低下を無効化し、1問につき+2秒。|Иммунитет к «Низкому заряду» и +2 с на вопрос.|Odporność na Słabą baterię i +2 s na pytanie.", { immune: ["battery"], round: x => { x.seconds += 2; } });
  def("taskmgr", "s_compass", 4, 0, "Administrador de tareas|Task manager|Gestionnaire des tâches|Gerenciador de tarefas|Task-Manager|Gestione attività||任务管理器|작업 관리자|タスクマネージャー|Диспетчер задач|Menedżer zadań", "Las ventanas de error se cierran solas en 1,5 s.|Error windows close by themselves after 1.5 s.|Les fenêtres d'erreur se ferment seules au bout de 1,5 s.|As janelas de erro fecham sozinhas após 1,5 s.|Fehlerfenster schließen sich nach 1,5 s von selbst.|Le finestre di errore si chiudono da sole dopo 1,5 s.||错误窗口会在 1.5 秒后自动关闭。|오류 창이 1.5초 후 저절로 닫힙니다.|エラーウィンドウが1.5秒で自動的に閉じる。|Окна ошибок закрываются сами через 1,5 с.|Okna błędów zamykają się same po 1,5 s.", { fx: { hangAuto: 1500 } });

  /* ---------------------------------------------------------------- LEGENDARIOS (solo en cofres de jefe) */
  def("philosopher", "s_pin", 14, 3, "Toque de Midas|Midas touch|Toucher de Midas|Toque de Midas|Midas-Berührung|Tocco di Mida||点金手|미다스의 손|ミダスの手|Прикосновение Мидаса|Dotyk Midasa", "Todos los doblones que ganes se duplican.|All doubloons you earn are doubled.|Tous les doublons que tu gagnes sont doublés.|Todos os dobrões que ganhar são dobrados.|Alle verdienten Dublonen werden verdoppelt.|Tutti i dobloni che guadagni sono raddoppiati.||你获得的所有金币翻倍。|획득하는 모든 도블론이 두 배가 됩니다.|獲得するダブロンがすべて2倍になる。|Все заработанные дублоны удваиваются.|Wszystkie zdobyte dublony są podwajane.", { coinX: 2 });
  def("oracle", "s_palm", 14, 3, "Oráculo|Oracle|Oracle|Oráculo|Orakel|Oracolo||神谕|신탁|神託|Оракул|Wyrocznia", "En cada pregunta, el país del lugar se ilumina en el mapa desde el primer segundo.|On every question, the place's country is lit up on the map from the first second.|À chaque question, le pays du lieu est illuminé sur la carte dès la première seconde.|Em cada pergunta, o país do lugar já vem iluminado no mapa desde o primeiro segundo.|Bei jeder Frage ist das Land des Ortes von der ersten Sekunde an auf der Karte beleuchtet.|A ogni domanda, il paese del luogo è illuminato sulla mappa fin dal primo secondo.||每题从第一秒起，地点所在国家就在地图上亮起。|매 문제의 첫 순간부터 장소의 국가가 지도에 표시됩니다.|毎問、最初からその場所の国が地図上で光っている。|На каждом вопросе страна места подсвечена на карте с первой секунды.|W każdym pytaniu kraj miejsca świeci na mapie od pierwszej sekundy.", { open: (api, o) => api.country(o) });
  def("masterkey", "s_peak", 14, 3, "Carta comodín|Wildcard|Carte joker|Carta coringa|Jokerkarte|Carta jolly||万能牌|와일드카드|ワイルドカード|Джокер|Dżoker", "El primer reto de cada ronda queda desactivado.|The first challenge of every round is disabled.|Le premier défi de chaque manche est désactivé.|O primeiro desafio de cada rodada fica desativado.|Die erste Herausforderung jeder Runde entfällt.|La prima sfida di ogni round è disattivata.||每回合的第一个挑战会被禁用。|모든 라운드의 첫 번째 도전이 비활성화됩니다.|毎ラウンド、最初のチャレンジが無効になる。|Первое испытание каждого раунда отключено.|Pierwsze wyzwanie każdej rundy jest wyłączone.", { skipFirst: 1 });

  A.RELICS = P;
  A.RELIC_IDS = Object.keys(P);
})(window.AIQ);
