/*
 * Geolite - catalogo de PERKS de la Aventura (v0.10). Ninguno multiplica ni suma puntos: la puntuacion es solo tu precision.
 * Los perks ayudan a resolver los RETOS del crupier (letras temblorosas, mapa borroso, apagon, fronteras falsas, continentes movidos...),
 * mejoran tu puntero, dan pistas, tiempo, supervivencia o doblones. Cada perk es una carta de poker con palo geografico.
 *
 *   fx {..}         mitigaciones de retos y mejoras del puntero (ver A.chal.fx en js/challenges.js)
 *   round(x,run)    al empezar la ronda (x.seconds)                open(api,o,run)  pistas gratis al empezar cada pregunta (api.laterHalf: a mitad de tiempo)
 *   clear(x,run)    al superar una ronda (x.coins)                 shop(x,run)      tienda (x.price -, x.freeReroll)
 *   post(c,run)     tras puntuar: SOLO doblones (c.coins)          flags: immune[], ignoreBoss, coinX, toolBonus, interest, shieldAct, sonarErr, compass16, spy, skipFirst
 * Texto: n = nombre y d = descripcion en es|en|fr|pt|de|it.
 */
window.AIQ = window.AIQ || {};
(function (A) {
  const L6 = s => { const [es, en, fr, pt, de, it] = s.split("|"); return { es, en, fr, pt, de, it }; };
  const P = {};
  const def = (id, suit, cost, r, n, d, hooks = {}) => { P[id] = { id, ico: id, suit, cost, r, n: L6(n), d: L6(d), ...hooks }; };
  const seeded = (run, tag) => A.rng(`${run.seed}:${tag}:${run.act}:${run.round}:${run.qi}:${run.qTotal || 0}`)();

  /* ---------------------------------------------------------------- contra retos de TEXTO */
  def("steadyhand", "s_compass", 4, 0, "Pulso firme|Steady hand|Main ferme|Mão firme|Ruhige Hand|Mano ferma", "Las letras, el baile de letras y tu puntero tiemblan un 75 % menos.|Letters, dancing letters and your pointer shake 75% less.|Les lettres et ton pointeur tremblent 75 % de moins.|Letras e ponteiro tremem 75% menos.|Buchstaben und Zeiger zittern 75 % weniger.|Lettere e puntatore tremano il 75% in meno.", { fx: { shakeMul: 0.25 } });
  def("dictionary", "s_peak", 5, 0, "Diccionario|Dictionary|Dictionnaire|Dicionário|Wörterbuch|Dizionario", "Las letras borradas vuelven una a una.|Faded letters come back one by one.|Les lettres effacées reviennent une à une.|As letras apagadas voltam uma a uma.|Verblasste Buchstaben kehren einzeln zurück.|Le lettere sbiadite tornano una a una.", { fx: { missingRate: 0.9 } });
  def("handmirror", "s_compass", 4, 0, "Espejo de mano|Hand mirror|Miroir à main|Espelho de mão|Handspiegel|Specchietto", "Nombres en espejo o del revés se leen normal, y el puntero invertido vuelve a su sitio.|Mirrored or upside-down names read normally and a reversed pointer is fixed.|Les noms en miroir ou à l'envers se lisent normalement.|Nomes espelhados ou invertidos ficam normais.|Gespiegelte Namen sind normal lesbar, umgekehrte Steuerung wird korrigiert.|I nomi a specchio o capovolti si leggono normali.", { fx: { unmirror: true } });
  def("spectacles", "s_palm", 6, 1, "Gafas de lectura|Reading glasses|Lunettes de lecture|Óculos de leitura|Lesebrille|Occhiali da lettura", "Todos los retos de texto pesan la mitad.|All text challenges are half as strong.|Tous les défis de texte sont deux fois plus faibles.|Todos os desafios de texto valem metade.|Alle Textreize sind nur halb so stark.|Tutte le sfide di testo valgono la metà.", { fx: { textMul: 0.5 } });

  /* ---------------------------------------------------------------- contra retos del MAPA */
  def("miner", "s_peak", 5, 0, "Linterna de minero|Miner's lamp|Lampe de mineur|Lanterna de mineiro|Grubenlampe|Lampada da minatore", "Tu haz de luz es casi el doble de ancho en un apagón.|Your light beam is almost twice as wide in a blackout.|Ton faisceau est presque deux fois plus large en cas de panne.|Seu feixe de luz é quase o dobro num apagão.|Dein Lichtkegel ist bei Stromausfall fast doppelt so breit.|Il tuo fascio di luce è quasi il doppio in un blackout.", { fx: { darkR: 1.9, halo: true } });
  def("lens", "s_compass", 6, 1, "Lupa de cartógrafo|Cartographer's lens|Loupe de cartographe|Lupa de cartógrafo|Kartografenlupe|Lente da cartografo", "Un círculo nítido sigue a tu puntero en un mapa borroso.|A sharp circle follows your pointer on a blurry map.|Un cercle net suit ton pointeur sur une carte floue.|Um círculo nítido acompanha o ponteiro num mapa desfocado.|Ein scharfer Kreis folgt deinem Zeiger auf unscharfer Karte.|Un cerchio nitido segue il puntatore su una mappa sfocata.", { fx: { lensR: 120 } });
  def("divingmask", "s_palm", 4, 0, "Gafas de buceo|Diving mask|Masque de plongée|Máscara de mergulho|Taucherbrille|Maschera da sub", "El desenfoque del mapa se reduce a menos de la mitad.|Map blur is cut by more than half.|Le flou de la carte est réduit de plus de moitié.|O desfoque do mapa cai mais da metade.|Die Unschärfe sinkt um mehr als die Hälfte.|La sfocatura della mappa si riduce di oltre la metà.", { fx: { blurMul: 0.45 } });
  def("customs", "s_pin", 7, 1, "Sello de aduana|Customs stamp|Tampon de douane|Carimbo da alfândega|Zollstempel|Timbro doganale", "Ves las fronteras verdaderas en un círculo junto a tu puntero.|You see the true borders in a circle around your pointer.|Tu vois les vraies frontières dans un cercle autour de ton pointeur.|Você vê as fronteiras verdadeiras num círculo ao redor do ponteiro.|Du siehst die echten Grenzen in einem Kreis um deinen Zeiger.|Vedi i veri confini in un cerchio attorno al puntatore.", { fx: { trueR: 110, peekR: 110 } });
  def("plates", "s_palm", 8, 2, "Placas tectónicas|Tectonic plates|Plaques tectoniques|Placas tectônicas|Kontinentalplatten|Placche tettoniche", "Los continentes movidos se acercan a su sitio: Pangea y cambios, un 60 % más suaves.|Displaced continents drift back toward home: Pangaea and swaps are 60% milder.|Les continents déplacés se rapprochent de leur place : 60 % plus doux.|Continentes deslocados se aproximam do lugar: 60% mais suaves.|Verschobene Kontinente rücken näher an ihren Platz: 60 % milder.|I continenti spostati si avvicinano al loro posto: 60% più leggeri.", { fx: { plateMul: 0.4 } });
  def("weathervane", "s_compass", 6, 1, "Veleta|Weathervane|Girouette|Cata-vento|Wetterfahne|Banderuola", "Ves un pin fantasma donde caerá el tuyo con el viento.|You see a ghost pin where the wind will drop yours.|Tu vois une épingle fantôme là où le vent posera la tienne.|Você vê um pino fantasma onde o vento vai deixar o seu.|Du siehst einen Geisterpin, wo der Wind deinen ablegt.|Vedi un pin fantasma dove il vento poserà il tuo.", { fx: { windPreview: true } });

  /* ---------------------------------------------------------------- puntero */

  /* ---------------------------------------------------------------- pistas gratis y herramientas */
  def("sextant", "s_palm", 5, 0, "Sextante|Sextant|Sextant|Sextante|Sextant|Sestante", "Cada pregunta: te dicen el continente.|Every question: you're told the continent.|Chaque question : on te donne le continent.|Cada pergunta: você recebe o continente.|Jede Frage: du erfährst den Kontinent.|Ogni domanda: ti dicono il continente.", { open: (api, o) => api.note(api.continent(o), "sextant") });
  def("atlasbook", "s_peak", 6, 1, "Atlas de bolsillo|Pocket atlas|Atlas de poche|Atlas de bolso|Taschenatlas|Atlante tascabile", "En cada pregunta, a mitad de tiempo se ilumina en el mapa el país del lugar.|On every question, halfway through the time the place's country lights up on the map.|À chaque question, à mi-temps, le pays du lieu s'illumine sur la carte.|Em cada pergunta, na metade do tempo o país do lugar se ilumina no mapa.|Bei jeder Frage leuchtet zur Halbzeit das Land des Ortes auf der Karte auf.|A ogni domanda, a metà tempo il paese del luogo si illumina sulla mappa.", { open: (api, o) => api.laterHalf(() => api.country(o)) });
  def("almanac", "s_peak", 6, 1, "Almanaque|Almanac|Almanach|Almanaque|Almanach|Almanacco", "En cada pregunta, lees gratis la nota de campo del lugar.|On every question, read the place's field note for free.|À chaque question, tu lis gratuitement la note de terrain du lieu.|Em cada pergunta, você lê grátis a nota de campo do lugar.|Bei jeder Frage liest du die Feldnotiz des Ortes gratis.|A ogni domanda, leggi gratis la nota di campo del luogo.", { open: (api, o) => api.fact(o) });
  def("sonarplus", "s_compass", 6, 1, "Sonar afinado|Fine-tuned sonar|Sonar affiné|Sonar afinado|Fein abgestimmtes Sonar|Sonar affinato", "El Sonar solo se equivoca un ±2 % (en vez de ±6 %).|Sonar is off by only ±2% (instead of ±6%).|Le sonar ne se trompe que de ±2 % (au lieu de ±6 %).|O Sonar erra só ±2% (em vez de ±6%).|Das Sonar irrt nur um ±2 % (statt ±6 %).|Il Sonar sbaglia solo del ±2% (invece del ±6%).", { sonarErr: 0.02 });
  def("compass16", "s_peak", 6, 1, "Brújula de 16 rumbos|16-point compass|Boussole à 16 rumbs|Bússola de 16 pontos|16-Strich-Kompass|Bussola a 16 punte", "La Brújula señala 16 direcciones en vez de 8.|The Compass points in 16 directions instead of 8.|La boussole indique 16 directions au lieu de 8.|A Bússola aponta 16 direções em vez de 8.|Der Kompass zeigt 16 statt 8 Richtungen.|La Bussola indica 16 direzioni invece di 8.", { compass16: true });
  def("glass", "s_palm", 8, 2, "Catalejo|Spyglass|Longue-vue|Luneta|Fernrohr|Cannocchiale", "+1 carga en todas tus herramientas.|+1 charge on all your tools.|+1 charge sur tous tes outils.|+1 carga em todas as suas ferramentas.|+1 Ladung für alle Werkzeuge.|+1 carica su tutti i tuoi strumenti.", { toolBonus: 1 });
  def("spyhole", "s_pin", 5, 1, "Mirilla|Peephole|Judas|Olho mágico|Türspion|Spioncino", "El Campamento te muestra los retos de las 2 próximas rondas.|Camp shows you the challenges of the next 2 rounds.|Le camp te montre les défis des 2 prochaines manches.|O Acampamento mostra os desafios das 2 próximas rodadas.|Das Lager zeigt die Herausforderungen der nächsten 2 Runden.|Il Campo mostra le sfide dei prossimi 2 round.", { spy: 1 });

  /* ---------------------------------------------------------------- tiempo */
  def("boots", "s_palm", 4, 0, "Botas ligeras|Light boots|Bottes légères|Botas leves|Leichte Stiefel|Stivali leggeri", "+3 s por pregunta.|+3 s per question.|+3 s par question.|+3 s por pergunta.|+3 s pro Frage.|+3 s per domanda.", { round: x => { x.seconds += 3; } });

  /* ---------------------------------------------------------------- economia (doblones y tienda) */
  def("purse", "s_pin", 4, 0, "Faltriquera|Purse|Bourse|Bolsinha|Geldbeutel|Borsello", "+1 doblón por cada acierto bueno (750+ de distancia).|+1 doubloon per good hit (750+ distance).|+1 doublon par bon tir (750+).|+1 dobrão por bom acerto (750+).|+1 Dublone pro guten Treffer (750+).|+1 doblone per buon colpo (750+).", { post: c => (c.dist >= 750 ? (c.coins += 1, "+1") : null) });
  def("hoard", "s_pin", 5, 1, "Tesorero|Treasurer|Trésorier|Tesoureiro|Schatzmeister|Tesoriere", "+3 doblones al superar una ronda.|+3 doubloons when you clear a round.|+3 doublons en réussissant une manche.|+3 dobrões ao superar uma rodada.|+3 Dublonen beim Bestehen einer Runde.|+3 dobloni al superare un round.", { clear: x => { x.coins += 3; return "+3"; } });
  def("coupon", "s_pin", 5, 0, "Cupón|Coupon|Coupon|Cupom|Gutschein|Coupon", "Todo cuesta 1 doblón menos en la tienda.|Everything costs 1 doubloon less in the shop.|Tout coûte 1 doublon de moins à la boutique.|Tudo custa 1 dobrão a menos na loja.|Alles kostet 1 Dublone weniger im Laden.|Tutto costa 1 doblone in meno al negozio.", { shop: x => { x.price -= 1; } });
  def("banker", "s_pin", 8, 2, "Banquero|Banker|Banquier|Banqueiro|Bankier|Banchiere", "El interés (1 doblón por cada 5) llega hasta +6 en vez de +3.|Interest (1 doubloon per 5) caps at +6 instead of +3.|L'intérêt (1 doublon par 5) monte jusqu'à +6 au lieu de +3.|O juro (1 dobrão por 5) chega a +6 em vez de +3.|Zinsen (1 Dublone pro 5) bis +6 statt +3.|L'interesse (1 doblone ogni 5) arriva a +6 invece di +3.", { interest: 6 });

  /* ---------------------------------------------------------------- supervivencia */
  def("shield", "s_palm", 9, 2, "Escudo|Shield|Bouclier|Escudo|Schild|Scudo", "Una vez por acto, un fallo de ronda no te cuesta provisión.|Once per act, a failed round costs no provision.|Une fois par acte, une manche ratée ne coûte pas de provision.|Uma vez por ato, uma rodada falhada não custa provisão.|Einmal pro Akt kostet eine verpatzte Runde keinen Proviant.|Una volta per atto, un round fallito non costa una provvista.", { shieldAct: true });
  def("medkit", "s_pin", 6, 1, "Botiquín|First aid kit|Trousse de secours|Kit de primeiros socorros|Erste-Hilfe-Kasten|Kit di pronto soccorso", "+1 provisión (y máxima) al empezar cada acto.|+1 provision (and max) at the start of each act.|+1 provision (et max) au début de chaque acte.|+1 provisão (e máxima) no início de cada ato.|+1 Proviant (und Max.) zu Beginn jedes Akts.|+1 provvista (e massima) all'inizio di ogni atto.", { actStart: run => { run.maxLives++; run.lives++; } });
  def("heartperk", "s_pin", 8, 2, "Corazón de explorador|Explorer's heart|Cœur d'explorateur|Coração de explorador|Entdeckerherz|Cuore d'esploratore", "+1 provisión máxima y la recuperas al comprarlo.|+1 max provision, restored on purchase.|+1 provision max, récupérée à l'achat.|+1 provisão máxima, restaurada na compra.|+1 max. Proviant, sofort aufgefüllt.|+1 provvista massima, ripristinata all'acquisto.", { buy: run => { run.maxLives++; run.lives++; } });
  def("talisman", "s_compass", 9, 2, "Talismán|Talisman|Talisman|Talismã|Talisman|Talismano", "Ignoras el primer reto de cada jefe.|You ignore the first challenge of every boss.|Tu ignores le premier défi de chaque boss.|Você ignora o primeiro desafio de cada chefe.|Du ignorierst die erste Herausforderung jedes Bosses.|Ignori la prima sfida di ogni boss.", { ignoreBoss: 1 });
  def("earplugs", "s_palm", 6, 1, "Tapones|Earplugs|Bouchons d'oreilles|Tampões de ouvido|Ohrstöpsel|Tappi per le orecchie", "Inmune a los retos Silencio y Tormenta.|Immune to the Silence and Storm challenges.|Immunisé contre les défis Silence et Tempête.|Imune aos desafios Silêncio e Tempestade.|Immun gegen die Herausforderungen Stille und Gewitter.|Immune alle sfide Silenzio e Tempesta.", { immune: ["silence", "storm"] });


  /* ---------------------------------------------------------------- v0.11: mas ayudas contra retos de texto, mapa y puntero */
  def("shockabsorber", "s_palm", 6, 1, "Amortiguador|Shock absorber|Amortisseur|Amortecedor|Stoßdämpfer|Ammortizzatore", "Terremoto, deriva y ruleta del mapa se reducen un 70 %.|Earthquake, drift and map spin are cut by 70%.|Séisme, dérive et rotation réduits de 70 %.|Terremoto, deriva e roleta reduzidos em 70%.|Beben, Abdrift und Kartendrehung um 70 % kleiner.|Terremoto, deriva e rotazione ridotti del 70%.", { fx: { quakeMul: 0.3 } });
  def("umbrella", "s_palm", 4, 0, "Paraguas|Umbrella|Parapluie|Guarda-chuva|Regenschirm|Ombrello", "La lluvia y el humo son mucho menos densos.|Rain and smoke are much thinner.|La pluie et la fumée sont bien plus légères.|Chuva e fumaça ficam bem mais leves.|Regen und Rauch sind viel dünner.|Pioggia e fumo sono molto più leggeri.", { fx: { rainMul: 0.35, cloudMul: 0.6 } });
  def("gamer", "s_pin", 6, 1, "Ratón gaming|Gaming mouse|Souris gamer|Mouse gamer|Gaming-Maus|Mouse gaming", "Sin retraso en el puntero y sin parpadeos.|No pointer lag and no blinking.|Pas de retard du pointeur ni de clignotement.|Sem atraso no ponteiro e sem piscar.|Keine Zeigerverzögerung und kein Blinken.|Nessun ritardo del puntatore e niente lampeggi.", { fx: { lagMul: 0.001, noBlink: true } });

  /* ---------------------------------------------------------------- LEGENDARIOS (solo en cofres de jefe) */
  def("philosopher", "s_pin", 14, 3, "Piedra filosofal|Philosopher's stone|Pierre philosophale|Pedra filosofal|Stein der Weisen|Pietra filosofale", "Todos los doblones que ganes se duplican.|All doubloons you earn are doubled.|Tous les doublons que tu gagnes sont doublés.|Todos os dobrões que ganhar são dobrados.|Alle verdienten Dublonen werden verdoppelt.|Tutti i dobloni che guadagni sono raddoppiati.", { coinX: 2 });
  def("oracle", "s_palm", 14, 3, "Oráculo|Oracle|Oracle|Oráculo|Orakel|Oracolo", "En cada pregunta, el país del lugar se ilumina en el mapa desde el primer segundo.|On every question, the place's country is lit up on the map from the first second.|À chaque question, le pays du lieu est illuminé sur la carte dès la première seconde.|Em cada pergunta, o país do lugar já vem iluminado no mapa desde o primeiro segundo.|Bei jeder Frage ist das Land des Ortes von der ersten Sekunde an auf der Karte beleuchtet.|A ogni domanda, il paese del luogo è illuminato sulla mappa fin dal primo secondo.", { open: (api, o) => api.country(o) });
  def("masterkey", "s_peak", 14, 3, "Llave maestra|Master key|Passe-partout|Chave mestra|Generalschlüssel|Chiave maestra", "El primer reto de cada ronda queda desactivado.|The first challenge of every round is disabled.|Le premier défi de chaque manche est désactivé.|O primeiro desafio de cada rodada fica desativado.|Die erste Herausforderung jeder Runde entfällt.|La prima sfida di ogni round è disattivata.", { skipFirst: 1 });

  A.RELICS = P;
  A.RELIC_IDS = Object.keys(P);
})(window.AIQ);
