#!/usr/bin/env python3
"""Geolite - Don Crupier: la cara (solo desarrollo).
La mascara es RIGIDA: los huecos de los ojos no cambian nunca de forma (consistencia). Lo que expresa es lo de dentro:
  - parpados de piel que bajan/suben por encima del hueco (medio, cerrado, enfado, pena, sospecha, sueno),
  - el brillo del ojo (hacia donde mira), ojos en blanco con pupila (susto) y arcos felices (risa),
  - la boca bajo el bigote (hablar, carcajada, dientes apretados, O de susto, mueca, sonrisa de lado),
  - el bigote (normal, puntas arriba, caido, erizado).
Todo se dibuja sobre la capa head de rig.py; cada funcion devuelve una capa nueva.
"""
import sys
from pathlib import Path
import numpy as np
sys.path.insert(0, str(Path(__file__).parent))
from px import RGB, patch
from master import ch

# ---------------------------------------------------------------- ojos
# Los ojos son la forma del hueco de la mascara (como en los retratos de siempre: arcos al reir, rendija al sospechar...).
# Se dibujan a mano sobre la mascara SIN huecos (holeless) en un marco de 15x10 desde (52, 58) para el ojo izquierdo de la
# imagen; el derecho es su espejo exacto (eje x = 71.5), asi los dos ojos son siempre gemelos. '.' deja la mascara.
EYE_AT = (52, 58)
MIRROR = 143                                                  # x_derecho = MIRROR - x_izquierdo
EYES = {
    "open": """
        |...............
        |.KKKKKKKK......
        |.KKDDDDDK......
        |.KKKDDDDKKK....
        |..KKDDDDDDKK...
        |..KKDDDDDDKK...
        |..KKDDDDDDDKKK.
        |...KDDDDDDDDDK.
        |...KKKKKKKKKKK.
        |...............
    """,
    "half": """
        |...............
        |...............
        |...............
        |..KKKKKKKKK....
        |..KKKKKKKKKKK..
        |..KKDDDDDDKKKK.
        |...KDDDDDDDDDK.
        |...KKKKKKKKKKK.
        |...............
        |...............
    """,
    "closed": """
        |...............
        |...............
        |...............
        |...............
        |..KK...........
        |..KKKKK........
        |....KKKKKKKKK..
        |........KKKKKK.
        |...............
        |...............
    """,
    "happy": """
        |...............
        |...............
        |.....KKKKK.....
        |...KKKKKKKKK...
        |..KKK.....KKK..
        |..KK.......KK..
        |...............
        |...............
        |...............
        |...............
    """,
    "wide": """
        |...KKKKKKK.....
        |..KKWWWWWKK....
        |.KKWWWWWWWKK...
        |.KWWWWWWWWWK...
        |.KWWWDDWWWWK...
        |.KWWWDDWWWWK...
        |.KKWWWWWWWKK...
        |..KKWWWWWKK....
        |...KKKKKKK.....
        |...............
    """,
    "angry": """
        |...............
        |...............
        |.KK............
        |.KKKKK.........
        |..KKDDKKKKK....
        |..KKDDDDDDKKK..
        |...KDDDDDDDDKK.
        |...KKKKKKKKKKK.
        |...............
        |...............
    """,
    "sad": """
        |...............
        |...............
        |..........KK...
        |.......KKKKKK..
        |....KKKKDDDDK..
        |..KKKDDDDDDDK..
        |..KDDDDDDDDKK..
        |..KKKKKKKKKK...
        |...............
        |...............
    """,
    "squint": """
        |...............
        |...............
        |...............
        |...............
        |..KKKKKKKKKKK..
        |..KDDDDDDDDDKK.
        |..KKKKKKKKKKKK.
        |...............
        |...............
        |...............
    """,
    "sleepy": """
        |...............
        |...............
        |...............
        |...............
        |...............
        |..KKKKKKKKKKK..
        |...KDDDDDDDDKK.
        |...KKKKKKKKKKK.
        |...............
        |...............
    """,
    # mas abierto (el hueco crece 2 px por arriba): desconcierto, "¿eh?"
    "big": """
        |.KKKKKK........
        |.KDDDDKKK......
        |.KDDDDDDKK.....
        |.KKDDDDDDKK....
        |..KKDDDDDDKK...
        |..KKDDDDDDKK...
        |..KKDDDDDDDKKK.
        |...KDDDDDDDDDK.
        |...KKKKKKKKKKK.
        |...............
    """,
    # cerrados con cortesia (reverencia): arco suave, mas plano que la risa
    "calm": """
        |...............
        |...............
        |...............
        |.....KKKKKK....
        |...KKKKKKKKKK..
        |..KKK......KK..
        |...............
        |...............
        |...............
        |...............
    """,
    # V extrema (rabieta a gritos)
    "rage": """
        |...............
        |...............
        |.K.............
        |.KKK...........
        |.KKKKKK........
        |..KKDDKKKKK....
        |...KDDDDDDKKK..
        |...KKKKKKKKKKK.
        |...............
        |...............
    """,
    # a oscuras: el hueco encendido (blanco con pupila) y nada mas
    "glow": """
        |...............
        |.KKKKKKKK......
        |.KKWWWWWK......
        |.KKKWWWWKKK....
        |..KKWWWWWWKK...
        |..KKWWWWWWKK...
        |..KKWWWWWWWKKK.
        |...KWWWWWWWWWK.
        |...KKKKKKKKKKK.
        |...............
    """,
    # a oscuras y de fastidio: el hueco encendido en V
    "glowv": """
        |...............
        |...............
        |.KK............
        |.KKKKK.........
        |..KKWWKKKKK....
        |..KKWWWWWWKKK..
        |...KWWWWWWWWKK.
        |...KKKKKKKKKKK.
        |...............
        |...............
    """,
}
# brillo (donde mira) por forma: (x, y) de la mitad izquierda del brillo en el ojo izquierdo; None = sin brillo
GLINT = {"open": (57, 61), "half": (57, 63), "angry": (57, 63), "sad": (58, 63), "squint": (58, 63), "sleepy": (58, 64), "big": (56, 60), "rage": (59, 64)}
PUPIL = {"wide": (57, 62), "glow": (58, 62), "glowv": (58, 63)}
UP = {"open": (56, 60), "big": (55, 59), "wide": (56, 59), "glow": (57, 61)}          # mirada hacia arriba (look = 2): inocente, echando cuentas

def holeless(h):
    """la mascara sin huecos: lo que hay bajo cada ojo cuando se cierra"""
    for y in range(58, 68):
        for x in range(52, 67):
            if ch(h, x, y) in "KDWw" and (y <= 66):
                if y == 66 and x < 55: continue
                h[y, x] = RGB["b" if x <= 53 else "y"]
        for x in range(76, 92):
            if ch(h, x, y) in "KDWw" and (y <= 66):
                if y == 66 and x > 88: continue
                h[y, x] = RGB["y"]
    return h

def _draw(h, rows, side, look, kind):
    x0, y0 = EYE_AT
    for dy, r in enumerate(rows):
        for dx, c in enumerate(r):
            if c == ".": continue
            x = x0 + dx if side == "L" else MIRROR - (x0 + dx)
            h[y0 + dy, x] = RGB[c]
    up = look == 2
    if up: look = 0
    if kind in GLINT and not (up and kind in PUPIL):
        gx, gy = UP[kind] if up and kind in UP else GLINT[kind]; gx += look if side == "L" else -look
        pts = [(gx, gy), (gx + 1, gy)]
        if side == "R": pts = [(MIRROR - x - 1, y) for x, y in pts]    # el brillo no se refleja: la luz viene del mismo lado
        for x, y in pts:
            if ch(h, x, y) == "D": h[y, x] = RGB["W"]
    if kind in PUPIL:
        px_, py = UP[kind] if up and kind in UP else PUPIL[kind]
        cols = [px_, px_ + 1] if side == "L" else [MIRROR - px_ - 1, MIRROR - px_]
        for xx in cols:
            for y in (py, py + 1):
                if ch(h, xx + look, y) in "WD": h[y, xx + look] = RGB["D"]

def eye(h, side, kind="open", look=0):
    rows = [r for r in EYES[kind].split("\n") if "|" in r]
    rows = [r.split("|", 1)[1] for r in rows]
    _draw(h, rows, side, look, kind)
    return h

def eyes(h, kind="open", look=0, kinds=None):
    """kinds=(izquierdo, derecho) para guinos; look -1/0/1 mueve el brillo"""
    holeless(h)
    kl, kr = kinds if kinds else (kind, kind)
    eye(h, "L", kl, look); eye(h, "R", kr, look)
    return h

# ---------------------------------------------------------------- bigote (pieza aparte: sube al reir, baja con pena, tiembla al hablar)
STACHE_BOX = (59, 72, 84, 81)                                  # x0, y0, x1, y1 (incluidos)

def split_stache(h):
    """devuelve (cara sin bigote, capa del bigote). Bajo el bigote queda piel (labio) para cuando se mueve"""
    x0, y0, x1, y1 = STACHE_BOX; base = h.copy(); st = np.zeros_like(h)
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            c = ch(h, x, y)
            if c in "PadDK" and not (x >= 81 and y <= 77) and not (x >= 85):
                st[y, x] = h[y, x]
                if y >= 74: base[y, x] = RGB["r"]
    # labio superior en sombra justo bajo la nariz (se ve si el bigote baja)
    for x in range(64, 80): base[74, x] = RGB["q"]
    return base, st

# ---------------------------------------------------------------- bocas (bajo el bigote; la parte de arriba queda tapada por el)
# marco desde (60, 79), 23 de ancho: centro en x = 71. '.' deja la piel
MOUTH_AT = (60, 79)
MOUTHS = {
    "none": "",
    "smirk": """
        |.......................
        |.......................
        |.......................
        |.......................
        |...............KK......
        |.........KKKKKK........
    """,
    "talk1": """
        |.......................
        |.......................
        |......KKKKKKKKKKK......
        |.......KDDxxxxDDK......
        |........KKKKKKKK.......
    """,
    "talk2": """
        |.......................
        |.......................
        |.....KKKKKKKKKKKKK.....
        |.....KDDDDDDDDDDDK.....
        |......KDDxxxxxDDK......
        |.......KKxxxxxKK.......
        |.........KKKKK.........
    """,
    "talk3": """
        |.......................
        |.......................
        |....KKKKKKKKKKKKKKK....
        |....KWWWWWWWWWWWWWK....
        |....KDDDDDDDDDDDDDK....
        |.....KDDxxxxxxxDDK.....
        |......KKxxxRxxxKK......
        |........KKKKKKK........
    """,
    "laugh": """
        |.......................
        |..KKKKKKKKKKKKKKKKKKK..
        |..KWWWWWWWWWWWWWWWWWK..
        |..KDDDDDDDDDDDDDDDDDK..
        |...KDDDxxxxxxxxxDDDK...
        |....KDxxxxRRRxxxxDK....
        |.....KKxxxxxxxxxKK.....
        |.......KKKKKKKKK.......
    """,
    "grin": """
        |.......................
        |.......................
        |...KKKKKKKKKKKKKKKKK...
        |...KWWWWWWWWWWWWWWWK...
        |....KKKKKKKKKKKKKKK....
    """,
    "grit": """
        |.......................
        |.......................
        |....KKKKKKKKKKKKKKK....
        |....KWWKWWKWWKWWKWK....
        |....KWWKWWKWWKWWKWK....
        |....KKKKKKKKKKKKKKK....
    """,
    "oh": """
        |.......................
        |.......................
        |.........KKKKK.........
        |........KDDDDDK........
        |........KDxxxDK........
        |........KDDxDDK........
        |.........KKKKK.........
    """,
    "frown": """
        |.......................
        |.......................
        |.......................
        |.......................
        |.........KKKKK.........
        |.......KK.....KK.......
        |......K.........K......
    """,
    "yawn": """
        |.......................
        |.......................
        |.......KKKKKKKKK.......
        |......KDDDDDDDDDK......
        |......KDDDDDDDDDK......
        |......KDDxxxxxDDK......
        |.......KDxxxxxDK.......
        |........KKKKKKK........
    """,
    "smile": """
        |.......................
        |.......................
        |.......................
        |.......................
        |......K.........K......
        |.......KKKKKKKKK.......
    """,
    "crooked": """
        |.......................
        |.......................
        |.......................
        |.......................
        |...............KK......
        |.............KK........
        |...........KK..........
    """,
    "shout": """
        |.......................
        |.KKKKKKKKKKKKKKKKKKKKK.
        |.KWWWWWWWWWWWWWWWWWWWK.
        |.KDDDDDDDDDDDDDDDDDDDK.
        |..KDDDDDxxxxxxxDDDDDK..
        |..KDDDxxxxRRRRxxxxDDK..
        |...KDxxxxRRRRRRxxxDK...
        |...KDDxxxxxxxxxxxDDK...
        |....KWWWWWWWWWWWWWK....
        |.....KKKKKKKKKKKKK.....
    """,
    "snore": """
        |.......................
        |.......................
        |.......................
        |..........KKK..........
        |.........KxxxK.........
        |..........KKK..........
    """,
    "flat": """
        |.......................
        |.......................
        |.......................
        |.......................
        |........KKKKKKK........
    """,
    "whistle": """
        |.......................
        |.......................
        |.......................
        |..........KKK..........
        |.........KxxxK.........
        |..........KKK..........
    """,
    "shh": """
        |.......................
        |.......................
        |.......................
        |.......................
        |..........KK...........
        |.........KqqK..........
        |..........KK...........
    """,
}

def mouth(h, kind="none"):
    if not MOUTHS.get(kind): return h
    patch(h, MOUTH_AT[0], MOUTH_AT[1], MOUTHS[kind], keep=".")
    return h
