#!/usr/bin/env python3
"""Geolite - Don Crupier: la mano libre (su izquierda, a la derecha de la imagen) y la manga (solo desarrollo).
Las cartas siguen SIEMPRE en la otra mano. Esta solo aparece para los gestos (dedo que niega, chitón, pellizco, palma, puno,
coger el ala de la chistera) y entra desde abajo a la derecha con su manga del frac.
Cada postura se dibuja a mano con el mismo estilo que el guante de las cartas: contorno 's'/'K', blanco con sombra lavanda a la
derecha ('w') y pliegues 'v'. ANCHOR = punto de la muneca (x, y) dentro del dibujo: ahi se engancha la manga.
"""
import sys, math
from pathlib import Path
import numpy as np
sys.path.insert(0, str(Path(__file__).parent))
from px import RGB, blank, patch, rows_of

GLOVES = {
    # indice arriba EN EL BORDE (lado del pulgar) con el pulgar a la vista: se lee "uno"/"no, no"/"chiton", nunca otra cosa
    "point": ("""
        |.sss..............
        |sWWws.............
        |sWWws.............
        |sWWws.............
        |sWWws.............
        |sWWws.............
        |sWWwsssssss.......
        |sWWwKWWWKWWss.....
        |sWWwKWWWKWWWws....
        |sWWWWWWWWWWWws....
        |sWWWWWWWWWWWws....
        |sKWWvWWWvWWwws....
        |ssKWWWWWWWWwws....
        |sWsKKWWWWWwwws....
        |sWWWsWWWWWwwws....
        |.sWWWWWWWWwwvs....
        |.sKWWWWWWwwwvs....
        |..sKWWWWwwwvs.....
        |...sKKKKKKKKs.....
        |...sWWWWWWWWs.....
        |...swwwwwwwws.....
        |...sKKKKKKKKs.....
    """, (8, 21)),
    # palma abierta hacia ti (encogerse de hombros, "para", tirar fichas)
    "palm": ("""
        |...sss.sss........
        |..sWWwsWWws.......
        |..sWWwsWWwsss.....
        |ss.sWWwsWWwsWWs...
        |sWssWWwsWWwsWws...
        |sWWsWWwsWWwsWws...
        |sWWsWWWWWWWWWws...
        |.sWWWWWWWWWWWws...
        |.sWWWWvWWWvWWws...
        |.sWWWWWvvvWWwws...
        |.sKWWWWWWWWWwws...
        |..sWWWWWWWWwwws...
        |..sKWWWWWWwwwvs...
        |...sKWWWWwwwvs....
        |....sKKKKKKKKs....
        |....sWWWWWWWWs....
        |....swwwwwwwws....
        |....sKKKKKKKKs....
    """, (8, 17)),
    # pellizco: pulgar e indice casi juntos (por los pelos, pajarita, bigote)
    "pinch": ("""
        |..ssss............
        |.sWWWws...........
        |.sWWWwss..........
        |..ssWWWws.........
        |....sssws.........
        |..ss...s..........
        |.sWWs.............
        |sWWWWssssss.......
        |sWWWWWWWKWWs......
        |sKWWWWWWKWWws.....
        |sWWvWWWWWWWws.....
        |sWWWvWWWWWwws.....
        |.sWWWWWWWwwws.....
        |.sKWWWWWwwwvs.....
        |..sKWWWwwwvs......
        |...sKKKKKKKs......
        |...sWWWWWWWs......
        |...swwwwwwws......
        |...sKKKKKKKs......
    """, (7, 18)),
    # puno (golpe, sello, toc-toc)
    "fist": ("""
        |..ssssssssss......
        |.sWWWKWWWKWWs.....
        |sWWWWKWWWKWWws....
        |sWWWWKWWWKWwws....
        |sKKKKKKKKKKwws....
        |sWWWWWWWWWWwws....
        |sWWvWWWWWWwwvs....
        |sWWWvvWWWwwwvs....
        |.sWWWWWWWwwvs.....
        |.sKWWWWWwwwvs.....
        |..sKKKKKKKKs......
        |..sWWWWWWWWs......
        |..swwwwwwwws......
        |..sKKKKKKKKs......
    """, (6, 13)),
    # agarre del ala (dedos por encima del ala, pulgar por debajo; el hueco es donde va el ala)
    "grip": ("""
        |...ssssss.........
        |..sWWWWWws........
        |.sWWWWWWwws.......
        |.sKKKKKKKws.......
        |..................
        |..................
        |..................
        |.sWWWWWWWws.......
        |.sWWvWWWwws.......
        |..sWWWWwwvs.......
        |..sKWWWwwvs.......
        |...sKKKKKs........
        |...sWWWWWs........
        |...swwwwws........
        |...sKKKKKs........
    """, (6, 14)),
}

def glove(kind):
    rows, anchor = GLOVES[kind]
    rr = rows_of(rows); h = len(rr); w = max(len(r) for r in rr)
    a = np.zeros((h, w, 4), np.uint8)
    patch(a, 0, 0, rr, keep=".")
    return a, anchor

EXIT = (106, 134)                                     # la manga sale por abajo a la derecha (fuera del busto)

def sleeve(wrist, exit=EXIT, r=6.4):
    """manga del frac de la muneca al borde: banda gruesa con contorno, luz arriba a la izquierda (como todo el retrato)"""
    a = blank(); (x0, y0), (x1, y1) = wrist, exit
    dx, dy = x1 - x0, y1 - y0; L2 = dx * dx + dy * dy or 1
    nx, ny = -dy / math.sqrt(L2), dx / math.sqrt(L2)          # normal
    if nx > 0: nx, ny = -nx, -ny                                # que apunte hacia la izquierda (la luz)
    for y in range(0, 128):
        for x in range(0, 128):
            t = ((x - x0) * dx + (y - y0) * dy) / L2
            if t < -0.05: continue
            t = min(1, t); px_, py_ = x0 + t * dx, y0 + t * dy
            d = math.hypot(x - px_, y - py_); side = (x - px_) * nx + (y - py_) * ny
            if d <= r: a[y, x] = RGB["L" if side > r - 1.6 else "P" if side > r - 3.2 else "d" if side > -r + 2 else "D"]
            elif d <= r + 1.1: a[y, x] = RGB["s"]
    return a

def arm(wrist, elbow=None):
    """brazo del frac: antebrazo de la muneca al codo y brazo del codo al borde de abajo (el codo puede salir por la derecha)"""
    if elbow is None: return sleeve(wrist)
    a = sleeve(elbow, EXIT); b = sleeve(wrist, elbow)
    m = b[..., 3] > 0; a[m] = b[m]
    return a

def free_hand(kind, wrist, elbow=None):
    """capa de la mano libre con su manga: la muneca del guante en `wrist`"""
    g, (ax, ay) = glove(kind)
    a = arm((wrist[0], wrist[1] + 1), elbow)
    gx, gy = wrist[0] - ax, wrist[1] - ay
    h, w = g.shape[:2]
    for y in range(h):
        for x in range(w):
            if g[y, x, 3] and 0 <= gy + y < 128 and 0 <= gx + x < 128: a[gy + y, gx + x] = g[y, x]
    return a
